-- sync-family-copies-with-templates.sql — OPT-IN, run once after 0036.
--
-- Families clone system templates into their own rows, so 0036 alone does not
-- change what children see. This script updates family copies, but only where
-- the copy still holds the OLD template value (i.e. the parent never edited it).
-- Rewards also receive their age range so the child shop can filter by age.
-- Run in the Supabase SQL editor. Backups are created first.

create table if not exists backup_sync_family_tasks as
  select * from tasks where is_system_template = false;
create table if not exists backup_sync_family_rewards as
  select * from rewards where is_system_template = false;
create table if not exists backup_sync_family_quests as
  select * from family_quests where is_system_template = false;

-- 1. Quest coins (only untouched values)
update tasks t set coin_reward = v.new_coin
from (values
  (null, 'Choose a healthy snack', 3, 3, 'none', false, 'photo', false, 30),
  (null, 'Design a greeting card', 5, 10, 'none', false, 'photo', true, 30),
  ('BQ-COMM-DRAW-EXPLAIN-A07', 'Draw and Explain My Picture', 5, 8, 'none', false, 'audio', false, 60),
  (null, 'Draw something new', 5, 10, 'none', false, 'photo', true, 30),
  (null, 'Healthy Snack Choice', 3, 3, 'photo', false, 'photo', false, 30),
  ('BQ-LIFE-PREP-FRUIT-A07', 'Help Prepare Fruit or a Snack', 5, 5, 'none', false, 'photo', false, 30),
  ('BQ-LEARN-ANIMAL-FACTS-A07', 'Learn 3 Facts About an Animal', 5, 8, 'none', false, 'text', false, 30),
  ('BQ-LEARN-ENG-WORDS-A07', 'Learn 5 English Words', 5, 5, 'none', false, 'text', false, 30),
  (null, 'Learn 5 New English Words', 5, 5, 'text', false, 'text', false, 30),
  (null, 'Learn 5 new words', 5, 5, 'none', false, 'text', false, 30),
  (null, 'Learn a fun fact and share it', 4, 5, 'none', false, 'audio', false, 60),
  (null, 'Make something with your hands', 6, 10, 'none', false, 'photo', true, 30),
  ('BQ-MONEY-NEEDS-WANTS-A07', 'Needs or Wants?', 5, 5, 'none', false, 'text', false, 30),
  (null, 'Outdoor play', 5, 10, 'none', false, 'choice', false, 30),
  ('BQ-COMM-READ-ALOUD-A07', 'Read a Story Aloud', 5, 5, 'none', false, 'audio', false, 60),
  ('BQ-CHAR-KIND-THING-A07', 'Do One Kind Thing', 0, 0, 'none', false, 'parent_observation', false, 30),
  (null, 'Do a Kind Act', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Help Set the Table', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Help Someone', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Help With Dishes', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Help someone today', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Say Thank You', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Drink enough water today', 3, 2, 'none', false, 'choice', false, 30),
  ('BQ-SELF-SCHOOL-BAG-A07', 'Prepare School Bag with Checklist', 3, 3, 'none', false, 'choice', false, 30),
  ('BQ-LEARN-READ-15-A07', 'Read for 15 Minutes', 3, 3, 'none', false, 'choice', false, 30),
  ('BQ-MONEY-SAVE-GOAL-A07', 'Save for One Small Goal', 3, 5, 'none', false, 'choice', false, 30),
  (null, 'Brush Teeth', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-CLEAR-PLATE-A07', 'Clear My Plate', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-MAKE-BED-A07', 'Make My Bed', 0, 0, 'none', false, 'none', false, 30),
  (null, 'Put Away Belongings', 0, 0, 'none', false, 'none', false, 30),
  (null, 'Put Dirty Clothes Away', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-DIRTY-CLOTHES-A07', 'Put Dirty Clothes in the Basket', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-SELF-TIDY-TOYS-A07', 'Put Toys and Books Back', 0, 0, 'none', false, 'none', false, 30),
  (null, 'Set the table for dinner', 0, 0, 'none', false, 'none', false, 30),
  (null, 'Take Care of Plants', 0, 0, 'photo', false, 'none', false, 30),
  (null, 'Tidy one space', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-WATER-PLANTS-A07', 'Water the Plants', 0, 0, 'none', false, 'none', false, 30),
  (null, 'Water the plants', 0, 0, 'none', false, 'none', false, 30),
  (null, 'Beautiful Handwriting', 5, 5, 'photo', false, 'photo', false, 30),
  (null, 'Bike Ride', 5, 10, 'photo', false, 'choice', false, 30),
  ('BQ-MONEY-COMPARE-PRICE-A08', 'Compare the Price of Two Snacks', 5, 5, 'none', false, 'text', false, 30),
  (null, 'Draw Something Creative', 5, 10, 'photo', true, 'photo', true, 30),
  (null, 'English Reading', 7, 5, 'choice', false, 'choice', false, 30),
  (null, 'English Speaking Practice', 10, 8, 'audio', true, 'audio', false, 60),
  (null, 'English speaking practice', 8, 8, 'none', false, 'audio', false, 60),
  (null, 'Exercise 20 Minutes', 5, 8, 'photo', false, 'choice', false, 30),
  (null, 'Exercise for 20 minutes', 5, 8, 'none', false, 'choice', false, 30),
  (null, 'Go for a walk or bike ride', 5, 10, 'none', false, 'choice', false, 30),
  ('BQ-WORLD-COUNTRY-A08', 'Learn About Another Country', 5, 8, 'none', false, 'text', false, 30),
  ('BQ-LIFE-SANDWICH-A08', 'Make a Simple Sandwich', 5, 5, 'none', false, 'photo', false, 30),
  ('BQ-MONEY-SHOP-LIST-A08', 'Make a Small Shopping List', 5, 5, 'none', false, 'photo', false, 30),
  (null, 'Math Practice', 7, 8, 'choice', false, 'choice', false, 30),
  (null, 'Music Practice', 6, 8, 'audio', false, 'audio', false, 60),
  (null, 'Music practice', 6, 8, 'none', false, 'audio', false, 60),
  (null, 'Outdoor Play', 5, 10, 'photo', false, 'choice', false, 30),
  (null, 'Read 20 Minutes', 5, 8, 'choice', false, 'choice', false, 30),
  (null, 'Read for fun', 5, 8, 'none', false, 'choice', false, 30),
  ('BQ-COMM-ENG-SPEAK-A08', 'Speak English for 2 Minutes', 5, 3, 'none', false, 'audio', false, 60),
  (null, 'Swimming Practice', 8, 15, 'photo', false, 'parent_observation', false, 30),
  (null, 'Tell Me What You Learned', 5, 3, 'audio', false, 'audio', false, 60),
  ('BQ-COMM-TELL-LEARNED-A08', 'Tell What I Learned Today', 5, 5, 'none', false, 'audio', false, 60),
  (null, 'Try something new today', 6, 8, 'none', false, 'choice', false, 30),
  (null, 'Watch a nature documentary', 5, 5, 'none', false, 'text', false, 30),
  (null, 'Call Grandparents', 0, 0, 'choice', false, 'parent_observation', false, 30),
  (null, 'Call or chat with grandparents', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Do a random act of kindness', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  ('BQ-CHAR-FEED-PET-A08', 'Feed a Pet', 0, 0, 'none', false, 'none', false, 30),
  (null, 'Help Family Without Being Asked', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Help Sister', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Help a sibling', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Write a thank-you note', 0, 0, 'parent_observation', false, 'photo', false, 30),
  ('BQ-SELF-RESP-FIRST-A08', 'Finish One Responsibility Before Entertainment', 3, 2, 'none', false, 'choice', false, 30),
  (null, 'Keep Desk Organized', 5, 3, 'photo', false, 'photo', false, 30),
  (null, 'Prepare School Bag', 5, 3, 'choice', false, 'choice', false, 30),
  ('BQ-SELF-SCHOOL-BAG-A08', 'Prepare School Bag Independently', 3, 3, 'none', false, 'choice', false, 30),
  (null, 'Prepare tomorrow''s school bag', 4, 3, 'none', false, 'choice', false, 30),
  ('BQ-LEARN-READ-20-A08', 'Read for 20 Minutes', 3, 4, 'none', false, 'choice', false, 30),
  (null, 'Sleep on Time', 15, 10, 'parent_observation', false, 'parent_observation', false, 30),
  ('BQ-LIFE-WEEKLY-TIDY-A08', 'Weekly Tidy-Up', 3, 5, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-TIDY-DESK-A08', 'Keep My Study Desk Tidy', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-PUT-CLOTHES-A08', 'Put Away My Clean Clothes', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-SET-TABLE-A08', 'Set the Dinner Table', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-SORT-LAUNDRY-A08', 'Sort Laundry', 0, 0, 'none', false, 'photo', false, 30),
  (null, 'Cook or bake something simple', 6, 15, 'none', false, 'photo', true, 30),
  ('BQ-MONEY-BUDGET-LIST-A09', 'Create a Shopping List Under 100,000đ', 8, 8, 'none', false, 'photo', false, 30),
  ('BQ-COMM-PRESENT-2-A09', 'Give a 2-Minute Presentation', 8, 5, 'none', false, 'parent_observation', false, 30),
  (null, 'Learn About a Country', 5, 10, 'text', false, 'text', true, 30),
  ('BQ-HEALTH-FIRST-AID-A09', 'Learn Basic First Aid for a Small Scratch', 8, 8, 'none', false, 'parent_observation', false, 30),
  (null, 'Learn about a country', 5, 10, 'none', false, 'text', true, 30),
  ('BQ-WORLD-MAP-NAV-A09', 'Navigate a Familiar Place Using a Map', 8, 10, 'none', false, 'parent_observation', false, 30),
  (null, 'Prepare for Tomorrow', 5, 5, 'choice', false, 'choice', false, 30),
  ('BQ-LEARN-RESEARCH-Q-A09', 'Research One Interesting Question', 8, 10, 'none', false, 'text', true, 30),
  (null, 'Review Today''s Lessons', 5, 8, 'text', false, 'text', false, 30),
  (null, 'Write a short story', 8, 15, 'none', false, 'photo', true, 30),
  ('BQ-CHAR-INTERVIEW-GRANDPARENTS-A09', 'Interview Grandparents About Childhood', 0, 0, 'none', false, 'audio', false, 60),
  (null, 'Vacuum a Room', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  ('BQ-SELF-FOCUS-25-A09', '25-Minute Focus Time', 3, 5, 'none', false, 'choice', false, 30),
  (null, 'Finish Homework', 5, 3, 'choice', false, 'choice', false, 30),
  (null, 'Fold My Clothes', 5, 3, 'photo', false, 'photo', false, 30),
  ('BQ-SELF-PREP-TOMORROW-A09', 'Prepare Tomorrow Before Bed', 3, 3, 'none', false, 'choice', false, 30),
  (null, 'Screen Time Self-Control', 5, 2, 'parent_observation', false, 'choice', false, 30),
  (null, 'Screen time self-control', 8, 2, 'none', false, 'choice', false, 30),
  ('BQ-SELF-HW-NO-REMIND-A09', 'Start Homework Without Reminder', 3, 2, 'none', false, 'choice', false, 30),
  ('BQ-LEARN-WEEKLY-READ-A09', 'Weekly Reading Goal', 3, 5, 'none', false, 'choice', false, 30),
  ('BQ-LIFE-FOLD-CLOTHES-A09', 'Fold and Put Away My Clothes', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-SELF-SCHOOL-SUPPLIES-A09', 'Organize School Supplies', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-CHAR-OWN-AREA-A09', 'Own One Household Area', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-OWN-SNACK-A09', 'Prepare My Own Simple Snack', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-VACUUM-A09', 'Vacuum a Small Area', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-MONEY-COMPARE-3-A10', 'Compare 3 Products Before Choosing', 8, 8, 'none', false, 'text', false, 30),
  ('BQ-LEARN-STEM-EXP-A10', 'Complete a Small STEM Experiment', 8, 15, 'none', false, 'photo', true, 30),
  ('BQ-LIFE-COOK-SIMPLE-A10', 'Cook One Simple Dish with Parent', 8, 15, 'none', false, 'photo', true, 30),
  (null, 'Finish One Book', 40, 50, 'photo', false, 'photo', true, 30),
  ('BQ-COMM-PRESENT-3-A10', 'Give a 3-Minute Presentation', 8, 8, 'none', false, 'parent_observation', false, 30),
  (null, 'Learn 10 New English Words', 10, 10, 'text', false, 'text', true, 30),
  (null, 'Mini research project', 12, 20, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-PACK-TRIP-A10', 'Pack for a Day Trip', 5, 8, 'none', false, 'photo', false, 30),
  (null, 'Read 30 Minutes', 7, 10, 'choice', false, 'choice', false, 30),
  (null, 'Admit a Mistake Honestly', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  ('BQ-CHAR-GAME-NIGHT-A10', 'Plan a Family Game Night', 0, 0, 'none', false, 'parent_observation', false, 30),
  (null, 'Resolve a Conflict Calmly', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  ('BQ-COMM-TEACH-SKILL-A10', 'Teach Someone Something I Know', 0, 0, 'none', false, 'parent_observation', false, 30),
  (null, 'Teach someone something', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Clean My Room', 5, 5, 'photo', false, 'photo', false, 30),
  ('BQ-SELF-TOP3-A10', 'Make Tomorrow''s Top-3 List', 3, 2, 'none', false, 'text', false, 30),
  ('BQ-LIFE-LAUNDRY-HELP-A10', 'Manage My Laundry with Help', 3, 5, 'none', false, 'photo', false, 30),
  ('BQ-LEARN-READ-30-A10', 'Read for 30 Minutes', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-DIGITAL-SCREEN-FREE-A10', 'Screen-Free Study Session', 3, 5, 'none', false, 'choice', false, 30),
  ('BQ-LIFE-ROOM-RESET-A10', 'Weekly Room Reset', 3, 5, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-CLEAN-SHARED-A10', 'Clean One Shared Family Area', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-HELP-DINNER-A10', 'Help Prepare Dinner', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-SELF-SCHOOL-MATERIALS-A10', 'Manage School Materials', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-COOK-MEAL-A11', 'Cook a Simple Meal with Supervision', 8, 15, 'none', false, 'photo', true, 30),
  ('BQ-LEARN-COMPARE-SOURCES-A11', 'Explain Why Two Sources Agree or Disagree', 8, 10, 'none', false, 'text', true, 30),
  ('BQ-DIGITAL-FACT-CHECK-A11', 'Fact-Check an Online Claim', 8, 8, 'none', false, 'text', false, 30),
  ('BQ-LEARN-TWO-SOURCES-A11', 'Find Two Sources About One Topic', 8, 10, 'none', false, 'text', true, 30),
  (null, 'Mini Research Project', 15, 20, 'photo', true, 'photo', true, 30),
  ('BQ-MONEY-PURCHASE-BUDGET-A11', 'Plan a Small Purchase Budget', 8, 10, 'none', false, 'photo', true, 30),
  ('BQ-COMM-EXPLAIN-YOUNGER-A11', 'Explain a Hard Idea to a Younger Child', 0, 0, 'none', false, 'parent_observation', false, 30),
  (null, 'Help Sister With Homework', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  ('BQ-CHAR-HELP-SIBLING-A11', 'Help a Younger Sibling While an Adult Is Home', 0, 0, 'none', false, 'parent_observation', false, 30),
  (null, 'Teach Sister Something', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  ('BQ-LIFE-FULL-LAUNDRY-A11', 'Do a Full Laundry Cycle with Guidance', 3, 8, 'none', false, 'photo', false, 30),
  ('BQ-MONEY-SPENDING-LOG-A11', 'Keep a Spending Log for One Week', 3, 2, 'none', false, 'text', false, 30),
  ('BQ-SELF-HW-INDEPENDENT-A11', 'Manage Homework Without Reminders', 3, 2, 'none', false, 'choice', false, 30),
  ('BQ-SELF-PLAN-WEEK-A11', 'Plan My Week', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-SELF-TRACK-DEADLINES-A11', 'Track School Deadlines', 3, 3, 'none', false, 'text', false, 30),
  ('BQ-LIFE-CHANGE-SHEETS-A11', 'Change My Bedsheets', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-CLEAN-BATH-A11', 'Clean Part of the Bathroom', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-CLEAN-KITCHEN-A11', 'Help Clean the Kitchen', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LEARN-STEM-PROJECT-A12', 'Build a Mini STEM Project', 12, 20, 'none', false, 'photo', true, 30),
  ('BQ-DIGITAL-AI-VERIFY-A12', 'Compare an AI Answer with a Trusted Source', 8, 8, 'none', false, 'text', false, 30),
  ('BQ-LIFE-COOK-BASIC-A12', 'Cook a Basic Meal with Supervision', 8, 20, 'none', false, 'photo', true, 30),
  ('BQ-LEARN-7DAY-SKILL-A12', 'Learn a Skill for 7 Days', 12, 50, 'none', false, 'text', true, 30),
  ('BQ-LEARN-READ-NONFICTION-A12', 'Read a Nonfiction Book', 8, 20, 'none', false, 'text', true, 30),
  ('BQ-DIGITAL-PHISHING-A12', 'Recognize Phishing or Scam Examples', 8, 8, 'none', false, 'text', false, 30),
  ('BQ-CHAR-CREATE-USEFUL-A12', 'Create Something Useful for the Family', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-SELF-FOCUS-45-A12', '45-Minute Focus Session', 3, 8, 'none', false, 'choice', false, 30),
  ('BQ-MONEY-SAVINGS-GOAL-A12', 'Track a Savings Goal', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-SELF-WEEKLY-PLAN-A12', 'Weekly Planning', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-SELF-WEEKLY-REFLECT-A12', 'Weekly Reflection', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-LIFE-CLEAN-ROOM-A12', 'Clean My Room Fully', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-PERSONAL-LAUNDRY-A12', 'Do Personal Laundry', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-CHAR-SHARED-SPACE-A12', 'Maintain One Shared Family Space', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-SELF-SCHOOL-PREP-A12', 'Manage School Preparation Independently', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-SELF-7DAY-PROJECT-A13', 'Complete a 7-Day Personal Project', 15, 50, 'none', false, 'photo', true, 30),
  ('BQ-COMM-PRESENT-5-A13', 'Give a 5-Minute Presentation', 10, 10, 'none', false, 'parent_observation', false, 30),
  ('BQ-WORLD-CAREER-INTERVIEW-A13', 'Interview an Adult About Their Profession', 10, 15, 'none', false, 'text', true, 30),
  ('BQ-MONEY-MEAL-BUDGET-A13', 'Plan a Meal Within a Budget', 10, 20, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-TRAVEL-ROUTE-A13', 'Travel a Familiar Route Independently', 8, 10, 'none', false, 'parent_observation', false, 30),
  ('BQ-CHAR-COMMUNITY-SERVICE-A13', 'Help in a Community or Family Service Activity', 0, 0, 'none', false, 'parent_observation', false, 30),
  ('BQ-SELF-PRIORITIES-A13', 'Choose My Top 3 Priorities', 3, 2, 'none', false, 'text', false, 30),
  ('BQ-HEALTH-EMOTIONS-A13', 'Notice and Manage Emotional Triggers', 3, 3, 'none', false, 'choice', false, 30),
  ('BQ-HEALTH-EXERCISE-A13', 'Regular Physical Activity', 3, 5, 'none', false, 'choice', false, 30),
  ('BQ-SELF-WEEKLY-REVIEW-A13', 'Weekly Review', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-LIFE-LAUNDRY-INDEPENDENT-A13', 'Complete Personal Laundry Independently', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-COOK-BASIC-MEAL-A13', 'Cook a Basic Meal', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-SELF-STUDY-AREA-A13', 'Maintain My Study Area', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-MONEY-ALLOWANCE-A13', 'Manage My Allowance', 0, 0, 'none', false, 'text', false, 30),
  ('BQ-CHAR-WEEKLY-CHORE-A13', 'Own One Weekly Family Chore', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LEARN-CREATIVE-PROJECT-A14', 'Build a Small Software, Art or Science Project', 15, 30, 'none', false, 'photo', true, 30),
  ('BQ-MONEY-COMPARE-PRODUCTS-A14', 'Compare Three Products Before a Purchase', 10, 10, 'none', false, 'text', true, 30),
  ('BQ-COMM-PRESENT-ISSUE-A14', 'Create a Presentation Explaining an Issue', 10, 20, 'none', false, 'parent_observation', false, 30),
  ('BQ-DIGITAL-FACT-CHECK-3-A14', 'Fact-Check 3 Social-Media Claims', 10, 10, 'none', false, 'text', true, 30),
  ('BQ-WORLD-CAREER-COMPARE-A14', 'Interview Two People About a Career', 10, 20, 'none', false, 'text', true, 30),
  ('BQ-DIGITAL-PRIVACY-A14', 'Review My Privacy Settings', 8, 10, 'none', false, 'text', true, 30),
  ('BQ-CHAR-ORGANIZE-ACTIVITY-A14', 'Organize a Family Activity', 0, 0, 'none', false, 'parent_observation', false, 30),
  ('BQ-LIFE-COOK-MULTIPLE-A14', 'Cook 2-3 Basic Dishes', 3, 10, 'none', false, 'photo', false, 30),
  ('BQ-DIGITAL-PHONE-AWAY-A14', 'Focus Session with Phone Away', 3, 8, 'none', false, 'choice', false, 30),
  ('BQ-LEARN-LONG-READ-A14', 'Read Long-Form Content', 3, 8, 'none', false, 'text', false, 30),
  ('BQ-SELF-PLAN-INDEPENDENT-A14', 'Weekly Planning Without Parent Doing It', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-SELF-STUDY-SCHEDULE-A14', 'Manage My Study Schedule', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-MONEY-PERSONAL-SPENDING-A14', 'Manage Personal Spending', 0, 0, 'none', false, 'text', false, 30),
  ('BQ-CHAR-HOUSEHOLD-CHORE-A14', 'Own a Shared Household Chore', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-GROCERY-PLAN-A14', 'Participate in Grocery Planning', 0, 0, 'none', false, 'text', false, 30),
  ('BQ-LEARN-2WEEK-BUILD-A15', 'Build Something Over 2 Weeks', 20, 75, 'none', false, 'photo', true, 30),
  ('BQ-LIFE-COOK-FAMILY-A15', 'Cook for the Family', 10, 25, 'none', false, 'photo', true, 30),
  ('BQ-MONEY-BUDGET-SHEET-A15', 'Create a Household Budget Spreadsheet', 10, 20, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-PORTFOLIO-A15', 'Create a Personal Portfolio Project', 15, 30, 'none', false, 'photo', true, 30),
  ('BQ-COMM-TALK-10-A15', 'Give a 5-10 Minute Talk', 10, 15, 'none', false, 'parent_observation', false, 30),
  ('BQ-WORLD-CAREER-RESEARCH-A15', 'Research Three Possible Careers', 10, 20, 'none', false, 'text', true, 30),
  ('BQ-COMM-PRO-EMAIL-A15', 'Write a Professional Email', 8, 8, 'none', false, 'text', false, 30),
  ('BQ-CHAR-RESOLVE-DISAGREE-A15', 'Resolve a Disagreement Calmly', 0, 0, 'none', false, 'parent_observation', false, 30),
  ('BQ-DIGITAL-DISTRACTION-A15', 'Manage Digital Distraction', 3, 3, 'none', false, 'choice', false, 30),
  ('BQ-SELF-MONTHLY-GOAL-A15', 'Set a Monthly Goal', 3, 10, 'none', false, 'text', false, 30),
  ('BQ-SELF-REVIEW-RESET-A15', 'Weekly Review and Reset', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-LIFE-MEAL-PLAN-A15', 'Help Plan Family Meals', 0, 0, 'none', false, 'text', false, 30),
  ('BQ-SELF-PERSONAL-ITEMS-A15', 'Maintain Important Personal Items', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-MONEY-MONTHLY-SPENDING-A15', 'Manage Personal Monthly Spending', 0, 0, 'none', false, 'text', false, 30),
  ('BQ-SELF-DEADLINES-INDEPENDENT-A15', 'Track School Deadlines Independently', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-MONEY-ANALYZE-SPENDING-A16', 'Analyze One Month of Spending', 10, 15, 'none', false, 'text', true, 30),
  ('BQ-MONEY-PAYMENT-METHODS-A16', 'Compare Cash, Debit and Credit', 10, 10, 'none', false, 'text', true, 30),
  ('BQ-SELF-30DAY-PROJECT-A16', 'Complete a 30-Day Personal Project', 25, 120, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-FIRST-CV-A16', 'Create My First CV', 15, 20, 'none', false, 'photo', true, 30),
  ('BQ-MONEY-GROCERY-BUDGET-A16', 'Do Grocery Shopping from List and Budget', 10, 20, 'none', false, 'photo', true, 30),
  ('BQ-MONEY-COMPOUND-INTEREST-A16', 'Explain Compound Interest', 10, 10, 'none', false, 'audio', true, 60),
  ('BQ-DIGITAL-FINANCIAL-SCAM-A16', 'Identify a Financial Scam', 10, 10, 'none', false, 'text', true, 30),
  ('BQ-COMM-JOB-INTERVIEW-A16', 'Practice a Job Interview', 10, 10, 'none', false, 'parent_observation', false, 30),
  ('BQ-WORLD-EDUCATION-ROUTES-A16', 'Research University or Education Routes', 10, 20, 'none', false, 'text', true, 30),
  ('BQ-DIGITAL-AI-VERIFY-A16', 'Use AI, Then Verify the Result', 10, 10, 'none', false, 'text', true, 30),
  ('BQ-MONEY-MONTHLY-BUDGET-A16', 'Make a Monthly Budget', 3, 10, 'none', false, 'text', false, 30),
  ('BQ-LIFE-COOK-SEVERAL-A16', 'Cook Several Complete Meals', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-DIGITAL-INFO-SAFETY-A16', 'Handle Important Personal Information Safely', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-LAUNDRY-FULL-A16', 'Manage Laundry Completely', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-SELF-PERSONAL-SCHEDULE-A16', 'Manage My Personal Schedule', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-WORLD-COMPARE-ROUTES-A17', 'Compare 3 University or Career Routes', 10, 20, 'none', false, 'text', true, 30),
  ('BQ-SELF-1MONTH-PROJECT-A17', 'Complete a One-Month Independent Project', 30, 120, 'none', false, 'photo', true, 30),
  ('BQ-LIFE-FULL-DINNER-A17', 'Cook a Complete Dinner for the Family', 10, 30, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-DECISION-MATRIX-A17', 'Create an Education/Career Decision Matrix', 15, 20, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-3DAY-TRIP-A17', 'Plan a 3-Day Trip Itinerary and Budget', 20, 30, 'none', false, 'photo', true, 30),
  ('BQ-COMM-RECOMMEND-A17', 'Present a Recommendation to Parents', 8, 10, 'none', false, 'parent_observation', false, 30),
  ('BQ-COMM-FORMAL-WRITE-A17', 'Write a Formal Request or Email', 8, 8, 'none', false, 'text', false, 30),
  ('BQ-CHAR-LEAD-ACTIVITY-A17', 'Lead a Family or Community Activity', 0, 0, 'none', false, 'parent_observation', false, 30),
  ('BQ-COMM-TEACH-YOUNGER-A17', 'Teach a Younger Person a Useful Skill', 0, 0, 'none', false, 'parent_observation', false, 30),
  ('BQ-LIFE-LAUNDRY-ROOM-A17', 'Manage Laundry and Room Maintenance', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-SELF-SCHEDULE-AUTONOMOUS-A17', 'Manage My Schedule Without Reminders', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-MONEY-PERSONAL-BUDGET-A17', 'Manage a Personal Budget', 0, 0, 'none', false, 'text', false, 30),
  ('BQ-SELF-DOCUMENTS-A17', 'Organize Personal Documents', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-WORLD-TRANSPORT-A17', 'Plan My Transport', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-COOK-INDEPENDENT-A17', 'Prepare Family Meals Independently', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-MONEY-EMERGENCY-BUDGET-A18', 'Build an Emergency-Budget Simulation', 15, 15, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-COMPARE-OFFERS-A18', 'Compare Two Education or Job Offers', 15, 20, 'none', false, 'text', true, 30),
  ('BQ-SELF-LONGTERM-PROJECT-A18', 'Complete a Long-Term Personal Project', 30, 150, 'none', false, 'photo', true, 30),
  ('BQ-SELF-1YEAR-PLAN-A18', 'Create My 1-Year Personal Development Plan', 20, 50, 'none', false, 'text', true, 30),
  ('BQ-WORLD-CV-PORTFOLIO-A18', 'Create a CV and Portfolio', 15, 30, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-APPOINTMENT-A18', 'Organize an Important Appointment', 10, 10, 'none', false, 'parent_observation', false, 30),
  ('BQ-WORLD-INDEPENDENT-TRAVEL-A18', 'Plan Independent Travel', 15, 30, 'none', false, 'text', true, 30),
  ('BQ-LIFE-MEAL-WEEK-A18', 'Plan One Week of Meals and Grocery Cost', 15, 20, 'none', false, 'photo', true, 30),
  ('BQ-MONEY-1MONTH-BUDGET-A18', 'Run a One-Month Personal Budget', 15, 75, 'none', false, 'text', true, 30),
  ('BQ-CHAR-VOLUNTEER-LEAD-A18', 'Lead a Volunteer or Community Project', 0, 0, 'none', false, 'parent_observation', false, 30),
  ('BQ-CHAR-LEARN-FROM-PARENT-A18', 'Learn One Adult Skill from a Parent', 0, 0, 'none', false, 'parent_observation', false, 30),
  ('BQ-DIGITAL-PRO-IDENTITY-A18', 'Protect My Professional Digital Identity', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-LIFE-MAINTAIN-SPACE-A18', 'Maintain Clothing and Living Space', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-SELF-MANAGE-SCHEDULE-A18', 'Manage Appointments and Schedule', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-COOK-ADULT-A18', 'Plan and Cook Meals Independently', 0, 0, 'none', false, 'none', false, 30)
) as v(key, name, old_coin, new_coin, old_ev, old_req, new_ev, new_req, sec)
where t.is_system_template = false
  and (t.source_template_key = v.key or (t.source_template_key is null and t.name = v.name))
  and t.coin_reward = v.old_coin;

-- 2. Quest evidence (only untouched values)
update tasks t set evidence_type = v.new_ev, evidence_required = v.new_req, max_audio_seconds = v.sec
from (values
  (null, 'Choose a healthy snack', 3, 3, 'none', false, 'photo', false, 30),
  (null, 'Design a greeting card', 5, 10, 'none', false, 'photo', true, 30),
  ('BQ-COMM-DRAW-EXPLAIN-A07', 'Draw and Explain My Picture', 5, 8, 'none', false, 'audio', false, 60),
  (null, 'Draw something new', 5, 10, 'none', false, 'photo', true, 30),
  (null, 'Healthy Snack Choice', 3, 3, 'photo', false, 'photo', false, 30),
  ('BQ-LIFE-PREP-FRUIT-A07', 'Help Prepare Fruit or a Snack', 5, 5, 'none', false, 'photo', false, 30),
  ('BQ-LEARN-ANIMAL-FACTS-A07', 'Learn 3 Facts About an Animal', 5, 8, 'none', false, 'text', false, 30),
  ('BQ-LEARN-ENG-WORDS-A07', 'Learn 5 English Words', 5, 5, 'none', false, 'text', false, 30),
  (null, 'Learn 5 New English Words', 5, 5, 'text', false, 'text', false, 30),
  (null, 'Learn 5 new words', 5, 5, 'none', false, 'text', false, 30),
  (null, 'Learn a fun fact and share it', 4, 5, 'none', false, 'audio', false, 60),
  (null, 'Make something with your hands', 6, 10, 'none', false, 'photo', true, 30),
  ('BQ-MONEY-NEEDS-WANTS-A07', 'Needs or Wants?', 5, 5, 'none', false, 'text', false, 30),
  (null, 'Outdoor play', 5, 10, 'none', false, 'choice', false, 30),
  ('BQ-COMM-READ-ALOUD-A07', 'Read a Story Aloud', 5, 5, 'none', false, 'audio', false, 60),
  ('BQ-CHAR-KIND-THING-A07', 'Do One Kind Thing', 0, 0, 'none', false, 'parent_observation', false, 30),
  (null, 'Do a Kind Act', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Help Set the Table', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Help Someone', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Help With Dishes', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Help someone today', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Say Thank You', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Drink enough water today', 3, 2, 'none', false, 'choice', false, 30),
  ('BQ-SELF-SCHOOL-BAG-A07', 'Prepare School Bag with Checklist', 3, 3, 'none', false, 'choice', false, 30),
  ('BQ-LEARN-READ-15-A07', 'Read for 15 Minutes', 3, 3, 'none', false, 'choice', false, 30),
  ('BQ-MONEY-SAVE-GOAL-A07', 'Save for One Small Goal', 3, 5, 'none', false, 'choice', false, 30),
  (null, 'Brush Teeth', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-CLEAR-PLATE-A07', 'Clear My Plate', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-MAKE-BED-A07', 'Make My Bed', 0, 0, 'none', false, 'none', false, 30),
  (null, 'Put Away Belongings', 0, 0, 'none', false, 'none', false, 30),
  (null, 'Put Dirty Clothes Away', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-DIRTY-CLOTHES-A07', 'Put Dirty Clothes in the Basket', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-SELF-TIDY-TOYS-A07', 'Put Toys and Books Back', 0, 0, 'none', false, 'none', false, 30),
  (null, 'Set the table for dinner', 0, 0, 'none', false, 'none', false, 30),
  (null, 'Take Care of Plants', 0, 0, 'photo', false, 'none', false, 30),
  (null, 'Tidy one space', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-WATER-PLANTS-A07', 'Water the Plants', 0, 0, 'none', false, 'none', false, 30),
  (null, 'Water the plants', 0, 0, 'none', false, 'none', false, 30),
  (null, 'Beautiful Handwriting', 5, 5, 'photo', false, 'photo', false, 30),
  (null, 'Bike Ride', 5, 10, 'photo', false, 'choice', false, 30),
  ('BQ-MONEY-COMPARE-PRICE-A08', 'Compare the Price of Two Snacks', 5, 5, 'none', false, 'text', false, 30),
  (null, 'Draw Something Creative', 5, 10, 'photo', true, 'photo', true, 30),
  (null, 'English Reading', 7, 5, 'choice', false, 'choice', false, 30),
  (null, 'English Speaking Practice', 10, 8, 'audio', true, 'audio', false, 60),
  (null, 'English speaking practice', 8, 8, 'none', false, 'audio', false, 60),
  (null, 'Exercise 20 Minutes', 5, 8, 'photo', false, 'choice', false, 30),
  (null, 'Exercise for 20 minutes', 5, 8, 'none', false, 'choice', false, 30),
  (null, 'Go for a walk or bike ride', 5, 10, 'none', false, 'choice', false, 30),
  ('BQ-WORLD-COUNTRY-A08', 'Learn About Another Country', 5, 8, 'none', false, 'text', false, 30),
  ('BQ-LIFE-SANDWICH-A08', 'Make a Simple Sandwich', 5, 5, 'none', false, 'photo', false, 30),
  ('BQ-MONEY-SHOP-LIST-A08', 'Make a Small Shopping List', 5, 5, 'none', false, 'photo', false, 30),
  (null, 'Math Practice', 7, 8, 'choice', false, 'choice', false, 30),
  (null, 'Music Practice', 6, 8, 'audio', false, 'audio', false, 60),
  (null, 'Music practice', 6, 8, 'none', false, 'audio', false, 60),
  (null, 'Outdoor Play', 5, 10, 'photo', false, 'choice', false, 30),
  (null, 'Read 20 Minutes', 5, 8, 'choice', false, 'choice', false, 30),
  (null, 'Read for fun', 5, 8, 'none', false, 'choice', false, 30),
  ('BQ-COMM-ENG-SPEAK-A08', 'Speak English for 2 Minutes', 5, 3, 'none', false, 'audio', false, 60),
  (null, 'Swimming Practice', 8, 15, 'photo', false, 'parent_observation', false, 30),
  (null, 'Tell Me What You Learned', 5, 3, 'audio', false, 'audio', false, 60),
  ('BQ-COMM-TELL-LEARNED-A08', 'Tell What I Learned Today', 5, 5, 'none', false, 'audio', false, 60),
  (null, 'Try something new today', 6, 8, 'none', false, 'choice', false, 30),
  (null, 'Watch a nature documentary', 5, 5, 'none', false, 'text', false, 30),
  (null, 'Call Grandparents', 0, 0, 'choice', false, 'parent_observation', false, 30),
  (null, 'Call or chat with grandparents', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Do a random act of kindness', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  ('BQ-CHAR-FEED-PET-A08', 'Feed a Pet', 0, 0, 'none', false, 'none', false, 30),
  (null, 'Help Family Without Being Asked', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Help Sister', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Help a sibling', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Write a thank-you note', 0, 0, 'parent_observation', false, 'photo', false, 30),
  ('BQ-SELF-RESP-FIRST-A08', 'Finish One Responsibility Before Entertainment', 3, 2, 'none', false, 'choice', false, 30),
  (null, 'Keep Desk Organized', 5, 3, 'photo', false, 'photo', false, 30),
  (null, 'Prepare School Bag', 5, 3, 'choice', false, 'choice', false, 30),
  ('BQ-SELF-SCHOOL-BAG-A08', 'Prepare School Bag Independently', 3, 3, 'none', false, 'choice', false, 30),
  (null, 'Prepare tomorrow''s school bag', 4, 3, 'none', false, 'choice', false, 30),
  ('BQ-LEARN-READ-20-A08', 'Read for 20 Minutes', 3, 4, 'none', false, 'choice', false, 30),
  (null, 'Sleep on Time', 15, 10, 'parent_observation', false, 'parent_observation', false, 30),
  ('BQ-LIFE-WEEKLY-TIDY-A08', 'Weekly Tidy-Up', 3, 5, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-TIDY-DESK-A08', 'Keep My Study Desk Tidy', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-PUT-CLOTHES-A08', 'Put Away My Clean Clothes', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-SET-TABLE-A08', 'Set the Dinner Table', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-SORT-LAUNDRY-A08', 'Sort Laundry', 0, 0, 'none', false, 'photo', false, 30),
  (null, 'Cook or bake something simple', 6, 15, 'none', false, 'photo', true, 30),
  ('BQ-MONEY-BUDGET-LIST-A09', 'Create a Shopping List Under 100,000đ', 8, 8, 'none', false, 'photo', false, 30),
  ('BQ-COMM-PRESENT-2-A09', 'Give a 2-Minute Presentation', 8, 5, 'none', false, 'parent_observation', false, 30),
  (null, 'Learn About a Country', 5, 10, 'text', false, 'text', true, 30),
  ('BQ-HEALTH-FIRST-AID-A09', 'Learn Basic First Aid for a Small Scratch', 8, 8, 'none', false, 'parent_observation', false, 30),
  (null, 'Learn about a country', 5, 10, 'none', false, 'text', true, 30),
  ('BQ-WORLD-MAP-NAV-A09', 'Navigate a Familiar Place Using a Map', 8, 10, 'none', false, 'parent_observation', false, 30),
  (null, 'Prepare for Tomorrow', 5, 5, 'choice', false, 'choice', false, 30),
  ('BQ-LEARN-RESEARCH-Q-A09', 'Research One Interesting Question', 8, 10, 'none', false, 'text', true, 30),
  (null, 'Review Today''s Lessons', 5, 8, 'text', false, 'text', false, 30),
  (null, 'Write a short story', 8, 15, 'none', false, 'photo', true, 30),
  ('BQ-CHAR-INTERVIEW-GRANDPARENTS-A09', 'Interview Grandparents About Childhood', 0, 0, 'none', false, 'audio', false, 60),
  (null, 'Vacuum a Room', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  ('BQ-SELF-FOCUS-25-A09', '25-Minute Focus Time', 3, 5, 'none', false, 'choice', false, 30),
  (null, 'Finish Homework', 5, 3, 'choice', false, 'choice', false, 30),
  (null, 'Fold My Clothes', 5, 3, 'photo', false, 'photo', false, 30),
  ('BQ-SELF-PREP-TOMORROW-A09', 'Prepare Tomorrow Before Bed', 3, 3, 'none', false, 'choice', false, 30),
  (null, 'Screen Time Self-Control', 5, 2, 'parent_observation', false, 'choice', false, 30),
  (null, 'Screen time self-control', 8, 2, 'none', false, 'choice', false, 30),
  ('BQ-SELF-HW-NO-REMIND-A09', 'Start Homework Without Reminder', 3, 2, 'none', false, 'choice', false, 30),
  ('BQ-LEARN-WEEKLY-READ-A09', 'Weekly Reading Goal', 3, 5, 'none', false, 'choice', false, 30),
  ('BQ-LIFE-FOLD-CLOTHES-A09', 'Fold and Put Away My Clothes', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-SELF-SCHOOL-SUPPLIES-A09', 'Organize School Supplies', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-CHAR-OWN-AREA-A09', 'Own One Household Area', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-OWN-SNACK-A09', 'Prepare My Own Simple Snack', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-VACUUM-A09', 'Vacuum a Small Area', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-MONEY-COMPARE-3-A10', 'Compare 3 Products Before Choosing', 8, 8, 'none', false, 'text', false, 30),
  ('BQ-LEARN-STEM-EXP-A10', 'Complete a Small STEM Experiment', 8, 15, 'none', false, 'photo', true, 30),
  ('BQ-LIFE-COOK-SIMPLE-A10', 'Cook One Simple Dish with Parent', 8, 15, 'none', false, 'photo', true, 30),
  (null, 'Finish One Book', 40, 50, 'photo', false, 'photo', true, 30),
  ('BQ-COMM-PRESENT-3-A10', 'Give a 3-Minute Presentation', 8, 8, 'none', false, 'parent_observation', false, 30),
  (null, 'Learn 10 New English Words', 10, 10, 'text', false, 'text', true, 30),
  (null, 'Mini research project', 12, 20, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-PACK-TRIP-A10', 'Pack for a Day Trip', 5, 8, 'none', false, 'photo', false, 30),
  (null, 'Read 30 Minutes', 7, 10, 'choice', false, 'choice', false, 30),
  (null, 'Admit a Mistake Honestly', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  ('BQ-CHAR-GAME-NIGHT-A10', 'Plan a Family Game Night', 0, 0, 'none', false, 'parent_observation', false, 30),
  (null, 'Resolve a Conflict Calmly', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  ('BQ-COMM-TEACH-SKILL-A10', 'Teach Someone Something I Know', 0, 0, 'none', false, 'parent_observation', false, 30),
  (null, 'Teach someone something', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  (null, 'Clean My Room', 5, 5, 'photo', false, 'photo', false, 30),
  ('BQ-SELF-TOP3-A10', 'Make Tomorrow''s Top-3 List', 3, 2, 'none', false, 'text', false, 30),
  ('BQ-LIFE-LAUNDRY-HELP-A10', 'Manage My Laundry with Help', 3, 5, 'none', false, 'photo', false, 30),
  ('BQ-LEARN-READ-30-A10', 'Read for 30 Minutes', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-DIGITAL-SCREEN-FREE-A10', 'Screen-Free Study Session', 3, 5, 'none', false, 'choice', false, 30),
  ('BQ-LIFE-ROOM-RESET-A10', 'Weekly Room Reset', 3, 5, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-CLEAN-SHARED-A10', 'Clean One Shared Family Area', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-HELP-DINNER-A10', 'Help Prepare Dinner', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-SELF-SCHOOL-MATERIALS-A10', 'Manage School Materials', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-COOK-MEAL-A11', 'Cook a Simple Meal with Supervision', 8, 15, 'none', false, 'photo', true, 30),
  ('BQ-LEARN-COMPARE-SOURCES-A11', 'Explain Why Two Sources Agree or Disagree', 8, 10, 'none', false, 'text', true, 30),
  ('BQ-DIGITAL-FACT-CHECK-A11', 'Fact-Check an Online Claim', 8, 8, 'none', false, 'text', false, 30),
  ('BQ-LEARN-TWO-SOURCES-A11', 'Find Two Sources About One Topic', 8, 10, 'none', false, 'text', true, 30),
  (null, 'Mini Research Project', 15, 20, 'photo', true, 'photo', true, 30),
  ('BQ-MONEY-PURCHASE-BUDGET-A11', 'Plan a Small Purchase Budget', 8, 10, 'none', false, 'photo', true, 30),
  ('BQ-COMM-EXPLAIN-YOUNGER-A11', 'Explain a Hard Idea to a Younger Child', 0, 0, 'none', false, 'parent_observation', false, 30),
  (null, 'Help Sister With Homework', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  ('BQ-CHAR-HELP-SIBLING-A11', 'Help a Younger Sibling While an Adult Is Home', 0, 0, 'none', false, 'parent_observation', false, 30),
  (null, 'Teach Sister Something', 0, 0, 'parent_observation', false, 'parent_observation', false, 30),
  ('BQ-LIFE-FULL-LAUNDRY-A11', 'Do a Full Laundry Cycle with Guidance', 3, 8, 'none', false, 'photo', false, 30),
  ('BQ-MONEY-SPENDING-LOG-A11', 'Keep a Spending Log for One Week', 3, 2, 'none', false, 'text', false, 30),
  ('BQ-SELF-HW-INDEPENDENT-A11', 'Manage Homework Without Reminders', 3, 2, 'none', false, 'choice', false, 30),
  ('BQ-SELF-PLAN-WEEK-A11', 'Plan My Week', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-SELF-TRACK-DEADLINES-A11', 'Track School Deadlines', 3, 3, 'none', false, 'text', false, 30),
  ('BQ-LIFE-CHANGE-SHEETS-A11', 'Change My Bedsheets', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-CLEAN-BATH-A11', 'Clean Part of the Bathroom', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-CLEAN-KITCHEN-A11', 'Help Clean the Kitchen', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LEARN-STEM-PROJECT-A12', 'Build a Mini STEM Project', 12, 20, 'none', false, 'photo', true, 30),
  ('BQ-DIGITAL-AI-VERIFY-A12', 'Compare an AI Answer with a Trusted Source', 8, 8, 'none', false, 'text', false, 30),
  ('BQ-LIFE-COOK-BASIC-A12', 'Cook a Basic Meal with Supervision', 8, 20, 'none', false, 'photo', true, 30),
  ('BQ-LEARN-7DAY-SKILL-A12', 'Learn a Skill for 7 Days', 12, 50, 'none', false, 'text', true, 30),
  ('BQ-LEARN-READ-NONFICTION-A12', 'Read a Nonfiction Book', 8, 20, 'none', false, 'text', true, 30),
  ('BQ-DIGITAL-PHISHING-A12', 'Recognize Phishing or Scam Examples', 8, 8, 'none', false, 'text', false, 30),
  ('BQ-CHAR-CREATE-USEFUL-A12', 'Create Something Useful for the Family', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-SELF-FOCUS-45-A12', '45-Minute Focus Session', 3, 8, 'none', false, 'choice', false, 30),
  ('BQ-MONEY-SAVINGS-GOAL-A12', 'Track a Savings Goal', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-SELF-WEEKLY-PLAN-A12', 'Weekly Planning', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-SELF-WEEKLY-REFLECT-A12', 'Weekly Reflection', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-LIFE-CLEAN-ROOM-A12', 'Clean My Room Fully', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-PERSONAL-LAUNDRY-A12', 'Do Personal Laundry', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-CHAR-SHARED-SPACE-A12', 'Maintain One Shared Family Space', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-SELF-SCHOOL-PREP-A12', 'Manage School Preparation Independently', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-SELF-7DAY-PROJECT-A13', 'Complete a 7-Day Personal Project', 15, 50, 'none', false, 'photo', true, 30),
  ('BQ-COMM-PRESENT-5-A13', 'Give a 5-Minute Presentation', 10, 10, 'none', false, 'parent_observation', false, 30),
  ('BQ-WORLD-CAREER-INTERVIEW-A13', 'Interview an Adult About Their Profession', 10, 15, 'none', false, 'text', true, 30),
  ('BQ-MONEY-MEAL-BUDGET-A13', 'Plan a Meal Within a Budget', 10, 20, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-TRAVEL-ROUTE-A13', 'Travel a Familiar Route Independently', 8, 10, 'none', false, 'parent_observation', false, 30),
  ('BQ-CHAR-COMMUNITY-SERVICE-A13', 'Help in a Community or Family Service Activity', 0, 0, 'none', false, 'parent_observation', false, 30),
  ('BQ-SELF-PRIORITIES-A13', 'Choose My Top 3 Priorities', 3, 2, 'none', false, 'text', false, 30),
  ('BQ-HEALTH-EMOTIONS-A13', 'Notice and Manage Emotional Triggers', 3, 3, 'none', false, 'choice', false, 30),
  ('BQ-HEALTH-EXERCISE-A13', 'Regular Physical Activity', 3, 5, 'none', false, 'choice', false, 30),
  ('BQ-SELF-WEEKLY-REVIEW-A13', 'Weekly Review', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-LIFE-LAUNDRY-INDEPENDENT-A13', 'Complete Personal Laundry Independently', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-COOK-BASIC-MEAL-A13', 'Cook a Basic Meal', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-SELF-STUDY-AREA-A13', 'Maintain My Study Area', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-MONEY-ALLOWANCE-A13', 'Manage My Allowance', 0, 0, 'none', false, 'text', false, 30),
  ('BQ-CHAR-WEEKLY-CHORE-A13', 'Own One Weekly Family Chore', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LEARN-CREATIVE-PROJECT-A14', 'Build a Small Software, Art or Science Project', 15, 30, 'none', false, 'photo', true, 30),
  ('BQ-MONEY-COMPARE-PRODUCTS-A14', 'Compare Three Products Before a Purchase', 10, 10, 'none', false, 'text', true, 30),
  ('BQ-COMM-PRESENT-ISSUE-A14', 'Create a Presentation Explaining an Issue', 10, 20, 'none', false, 'parent_observation', false, 30),
  ('BQ-DIGITAL-FACT-CHECK-3-A14', 'Fact-Check 3 Social-Media Claims', 10, 10, 'none', false, 'text', true, 30),
  ('BQ-WORLD-CAREER-COMPARE-A14', 'Interview Two People About a Career', 10, 20, 'none', false, 'text', true, 30),
  ('BQ-DIGITAL-PRIVACY-A14', 'Review My Privacy Settings', 8, 10, 'none', false, 'text', true, 30),
  ('BQ-CHAR-ORGANIZE-ACTIVITY-A14', 'Organize a Family Activity', 0, 0, 'none', false, 'parent_observation', false, 30),
  ('BQ-LIFE-COOK-MULTIPLE-A14', 'Cook 2-3 Basic Dishes', 3, 10, 'none', false, 'photo', false, 30),
  ('BQ-DIGITAL-PHONE-AWAY-A14', 'Focus Session with Phone Away', 3, 8, 'none', false, 'choice', false, 30),
  ('BQ-LEARN-LONG-READ-A14', 'Read Long-Form Content', 3, 8, 'none', false, 'text', false, 30),
  ('BQ-SELF-PLAN-INDEPENDENT-A14', 'Weekly Planning Without Parent Doing It', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-SELF-STUDY-SCHEDULE-A14', 'Manage My Study Schedule', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-MONEY-PERSONAL-SPENDING-A14', 'Manage Personal Spending', 0, 0, 'none', false, 'text', false, 30),
  ('BQ-CHAR-HOUSEHOLD-CHORE-A14', 'Own a Shared Household Chore', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-LIFE-GROCERY-PLAN-A14', 'Participate in Grocery Planning', 0, 0, 'none', false, 'text', false, 30),
  ('BQ-LEARN-2WEEK-BUILD-A15', 'Build Something Over 2 Weeks', 20, 75, 'none', false, 'photo', true, 30),
  ('BQ-LIFE-COOK-FAMILY-A15', 'Cook for the Family', 10, 25, 'none', false, 'photo', true, 30),
  ('BQ-MONEY-BUDGET-SHEET-A15', 'Create a Household Budget Spreadsheet', 10, 20, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-PORTFOLIO-A15', 'Create a Personal Portfolio Project', 15, 30, 'none', false, 'photo', true, 30),
  ('BQ-COMM-TALK-10-A15', 'Give a 5-10 Minute Talk', 10, 15, 'none', false, 'parent_observation', false, 30),
  ('BQ-WORLD-CAREER-RESEARCH-A15', 'Research Three Possible Careers', 10, 20, 'none', false, 'text', true, 30),
  ('BQ-COMM-PRO-EMAIL-A15', 'Write a Professional Email', 8, 8, 'none', false, 'text', false, 30),
  ('BQ-CHAR-RESOLVE-DISAGREE-A15', 'Resolve a Disagreement Calmly', 0, 0, 'none', false, 'parent_observation', false, 30),
  ('BQ-DIGITAL-DISTRACTION-A15', 'Manage Digital Distraction', 3, 3, 'none', false, 'choice', false, 30),
  ('BQ-SELF-MONTHLY-GOAL-A15', 'Set a Monthly Goal', 3, 10, 'none', false, 'text', false, 30),
  ('BQ-SELF-REVIEW-RESET-A15', 'Weekly Review and Reset', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-LIFE-MEAL-PLAN-A15', 'Help Plan Family Meals', 0, 0, 'none', false, 'text', false, 30),
  ('BQ-SELF-PERSONAL-ITEMS-A15', 'Maintain Important Personal Items', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-MONEY-MONTHLY-SPENDING-A15', 'Manage Personal Monthly Spending', 0, 0, 'none', false, 'text', false, 30),
  ('BQ-SELF-DEADLINES-INDEPENDENT-A15', 'Track School Deadlines Independently', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-MONEY-ANALYZE-SPENDING-A16', 'Analyze One Month of Spending', 10, 15, 'none', false, 'text', true, 30),
  ('BQ-MONEY-PAYMENT-METHODS-A16', 'Compare Cash, Debit and Credit', 10, 10, 'none', false, 'text', true, 30),
  ('BQ-SELF-30DAY-PROJECT-A16', 'Complete a 30-Day Personal Project', 25, 120, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-FIRST-CV-A16', 'Create My First CV', 15, 20, 'none', false, 'photo', true, 30),
  ('BQ-MONEY-GROCERY-BUDGET-A16', 'Do Grocery Shopping from List and Budget', 10, 20, 'none', false, 'photo', true, 30),
  ('BQ-MONEY-COMPOUND-INTEREST-A16', 'Explain Compound Interest', 10, 10, 'none', false, 'audio', true, 60),
  ('BQ-DIGITAL-FINANCIAL-SCAM-A16', 'Identify a Financial Scam', 10, 10, 'none', false, 'text', true, 30),
  ('BQ-COMM-JOB-INTERVIEW-A16', 'Practice a Job Interview', 10, 10, 'none', false, 'parent_observation', false, 30),
  ('BQ-WORLD-EDUCATION-ROUTES-A16', 'Research University or Education Routes', 10, 20, 'none', false, 'text', true, 30),
  ('BQ-DIGITAL-AI-VERIFY-A16', 'Use AI, Then Verify the Result', 10, 10, 'none', false, 'text', true, 30),
  ('BQ-MONEY-MONTHLY-BUDGET-A16', 'Make a Monthly Budget', 3, 10, 'none', false, 'text', false, 30),
  ('BQ-LIFE-COOK-SEVERAL-A16', 'Cook Several Complete Meals', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-DIGITAL-INFO-SAFETY-A16', 'Handle Important Personal Information Safely', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-LAUNDRY-FULL-A16', 'Manage Laundry Completely', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-SELF-PERSONAL-SCHEDULE-A16', 'Manage My Personal Schedule', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-WORLD-COMPARE-ROUTES-A17', 'Compare 3 University or Career Routes', 10, 20, 'none', false, 'text', true, 30),
  ('BQ-SELF-1MONTH-PROJECT-A17', 'Complete a One-Month Independent Project', 30, 120, 'none', false, 'photo', true, 30),
  ('BQ-LIFE-FULL-DINNER-A17', 'Cook a Complete Dinner for the Family', 10, 30, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-DECISION-MATRIX-A17', 'Create an Education/Career Decision Matrix', 15, 20, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-3DAY-TRIP-A17', 'Plan a 3-Day Trip Itinerary and Budget', 20, 30, 'none', false, 'photo', true, 30),
  ('BQ-COMM-RECOMMEND-A17', 'Present a Recommendation to Parents', 8, 10, 'none', false, 'parent_observation', false, 30),
  ('BQ-COMM-FORMAL-WRITE-A17', 'Write a Formal Request or Email', 8, 8, 'none', false, 'text', false, 30),
  ('BQ-CHAR-LEAD-ACTIVITY-A17', 'Lead a Family or Community Activity', 0, 0, 'none', false, 'parent_observation', false, 30),
  ('BQ-COMM-TEACH-YOUNGER-A17', 'Teach a Younger Person a Useful Skill', 0, 0, 'none', false, 'parent_observation', false, 30),
  ('BQ-LIFE-LAUNDRY-ROOM-A17', 'Manage Laundry and Room Maintenance', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-SELF-SCHEDULE-AUTONOMOUS-A17', 'Manage My Schedule Without Reminders', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-MONEY-PERSONAL-BUDGET-A17', 'Manage a Personal Budget', 0, 0, 'none', false, 'text', false, 30),
  ('BQ-SELF-DOCUMENTS-A17', 'Organize Personal Documents', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-WORLD-TRANSPORT-A17', 'Plan My Transport', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-COOK-INDEPENDENT-A17', 'Prepare Family Meals Independently', 0, 0, 'none', false, 'photo', false, 30),
  ('BQ-MONEY-EMERGENCY-BUDGET-A18', 'Build an Emergency-Budget Simulation', 15, 15, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-COMPARE-OFFERS-A18', 'Compare Two Education or Job Offers', 15, 20, 'none', false, 'text', true, 30),
  ('BQ-SELF-LONGTERM-PROJECT-A18', 'Complete a Long-Term Personal Project', 30, 150, 'none', false, 'photo', true, 30),
  ('BQ-SELF-1YEAR-PLAN-A18', 'Create My 1-Year Personal Development Plan', 20, 50, 'none', false, 'text', true, 30),
  ('BQ-WORLD-CV-PORTFOLIO-A18', 'Create a CV and Portfolio', 15, 30, 'none', false, 'photo', true, 30),
  ('BQ-WORLD-APPOINTMENT-A18', 'Organize an Important Appointment', 10, 10, 'none', false, 'parent_observation', false, 30),
  ('BQ-WORLD-INDEPENDENT-TRAVEL-A18', 'Plan Independent Travel', 15, 30, 'none', false, 'text', true, 30),
  ('BQ-LIFE-MEAL-WEEK-A18', 'Plan One Week of Meals and Grocery Cost', 15, 20, 'none', false, 'photo', true, 30),
  ('BQ-MONEY-1MONTH-BUDGET-A18', 'Run a One-Month Personal Budget', 15, 75, 'none', false, 'text', true, 30),
  ('BQ-CHAR-VOLUNTEER-LEAD-A18', 'Lead a Volunteer or Community Project', 0, 0, 'none', false, 'parent_observation', false, 30),
  ('BQ-CHAR-LEARN-FROM-PARENT-A18', 'Learn One Adult Skill from a Parent', 0, 0, 'none', false, 'parent_observation', false, 30),
  ('BQ-DIGITAL-PRO-IDENTITY-A18', 'Protect My Professional Digital Identity', 3, 5, 'none', false, 'text', false, 30),
  ('BQ-LIFE-MAINTAIN-SPACE-A18', 'Maintain Clothing and Living Space', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-SELF-MANAGE-SCHEDULE-A18', 'Manage Appointments and Schedule', 0, 0, 'none', false, 'none', false, 30),
  ('BQ-LIFE-COOK-ADULT-A18', 'Plan and Cook Meals Independently', 0, 0, 'none', false, 'none', false, 30)
) as v(key, name, old_coin, new_coin, old_ev, old_req, new_ev, new_req, sec)
where t.is_system_template = false
  and (t.source_template_key = v.key or (t.source_template_key is null and t.name = v.name))
  and t.evidence_type = v.old_ev and t.evidence_required = v.old_req;

-- 3. Legacy quest age ranges (only untouched recommended_age)
update tasks t set min_age = v.min_age, recommended_age = v.rec_age, max_age = v.max_age
from (values
  ('Choose a healthy snack', 7, 5, 6, 12),
  ('Design a greeting card', 7, 5, 6, 14),
  ('Draw something new', 7, 5, 6, 14),
  ('Learn 5 new words', 7, 6, 6, 12),
  ('Learn a fun fact and share it', 7, 5, 6, 14),
  ('Make something with your hands', 7, 5, 6, 14),
  ('Outdoor play', 7, 5, 6, 14),
  ('Help someone today', 7, 5, 6, 18),
  ('Drink enough water today', 7, 5, 6, 14),
  ('Set the table for dinner', 7, 5, 6, 14),
  ('Tidy one space', 7, 5, 6, 14),
  ('Water the plants', 7, 5, 6, 18),
  ('English speaking practice', 8, 7, 9, 14),
  ('Exercise for 20 minutes', 8, 5, 12, 18),
  ('Go for a walk or bike ride', 8, 6, 14, 18),
  ('Music practice', 8, 6, 10, 18),
  ('Try something new today', 8, 6, 13, 16),
  ('Watch a nature documentary', 8, 6, 9, 14),
  ('Call or chat with grandparents', 8, 6, 11, 18),
  ('Do a random act of kindness', 8, 6, 15, 18),
  ('Help a sibling', 8, 6, 16, 18),
  ('Write a thank-you note', 8, 6, 10, 14),
  ('Cook or bake something simple', 9, 7, 11, 14),
  ('Write a short story', 9, 7, 13, 15),
  ('Screen time self-control', 9, 7, 16, 17),
  ('Mini research project', 10, 8, 14, 15),
  ('Teach someone something', 10, 8, 17, 18)
) as v(name, old_rec, min_age, rec_age, max_age)
where t.is_system_template = false and t.source_template_key is null
  and t.name = v.name and t.recommended_age is not distinct from v.old_rec;

-- 4. Reward cost/category (only untouched values) + age range and price reference (always)
update rewards r set
  coin_cost = case when r.coin_cost = v.old_coin then v.new_coin else r.coin_cost end,
  category = case when r.category is not distinct from v.old_cat then v.new_cat else r.category end,
  min_age = coalesce(r.min_age, v.min_age),
  recommended_age = coalesce(r.recommended_age, v.rec_age),
  max_age = coalesce(r.max_age, v.max_age),
  reference_price_vnd = coalesce(r.reference_price_vnd, v.vnd),
  source_template_key = coalesce(r.source_template_key, v.key)
from (values
  ('Sticker', 'BQ-RWD-STICKER', 30, 20, 'small', 'small', 20000, 6, 7, 10),
  ('Favorite snack', 'BQ-RWD-FAVORITE-SNACK', 60, 15, 'small', 'small', 15000, 6, 9, 17),
  ('Choose tonight''s dessert', 'BQ-RWD-CHOOSE-TONIGHT-S-DESSERT', 100, 20, 'small', 'small', null, 6, 9, 17),
  ('Ice cream', 'BQ-RWD-ICE-CREAM', 100, 25, 'small', 'small', 25000, 6, 9, 17),
  ('Choose family movie', 'BQ-RWD-CHOOSE-FAMILY-MOVIE', 120, 20, 'small', 'small', null, 6, 10, 17),
  ('Extra 20 min screen time', 'BQ-RWD-EXTRA-20-MIN-SCREEN-TIME', 150, 30, 'small', 'small', null, 6, 10, 17),
  ('Small stationery item', 'BQ-RWD-SMALL-STATIONERY-ITEM', 150, 15, 'small', 'small', 15000, 6, 9, 14),
  ('Cute notebook', 'BQ-RWD-CUTE-NOTEBOOK', 200, 40, 'small', 'small', 40000, 7, 10, 15),
  ('Bubble tea', 'BQ-RWD-BUBBLE-TEA', 250, 50, 'medium', 'small', 50000, 7, 12, 17),
  ('Choose weekend breakfast', 'BQ-RWD-CHOOSE-WEEKEND-BREAKFAST', 300, 50, 'medium', 'small', null, 6, 10, 17),
  ('Small toy', 'BQ-RWD-SMALL-TOY', 300, 120, 'small', 'medium', 120000, 6, 7, 10),
  ('New book', 'BQ-RWD-NEW-BOOK', 500, 90, 'medium', 'small', 90000, 6, 10, 17),
  ('Movie theater', 'BQ-RWD-MOVIE-THEATER', 500, 130, 'medium', 'experience', 130000, 6, 11, 17),
  ('Small LEGO set', 'BQ-RWD-SMALL-LEGO-SET', 700, 420, 'medium', 'medium', 420000, 6, 9, 14),
  ('Art supplies', 'BQ-RWD-ART-SUPPLIES', 700, 120, 'medium', 'medium', 120000, 6, 9, 15),
  ('Eat at favorite restaurant', 'BQ-RWD-EAT-AT-FAVORITE-RESTAURANT', 800, 190, 'medium', 'experience', 190000, 6, 11, 17),
  ('Toy or accessory', 'BQ-RWD-TOY-OR-ACCESSORY', 1000, 350, 'medium', 'medium', 350000, 7, 10, 13),
  ('New T-shirt', 'BQ-RWD-NEW-T-SHIRT', 1000, 200, 'medium', 'medium', 200000, 6, 12, 17),
  ('Family activity of choice', 'BQ-RWD-FAMILY-ACTIVITY-OF-CHOICE', 1200, 140, 'medium', 'experience', 140000, 6, 10, 17),
  ('Large LEGO set', 'BQ-RWD-LARGE-LEGO-SET', 2000, 2200, 'large', 'large', 2200000, 8, 11, 16),
  ('Day trip', 'BQ-RWD-DAY-TRIP', 2500, 750, 'large', 'experience', 750000, 6, 11, 17),
  ('Nice headphones', 'BQ-RWD-NICE-HEADPHONES', 2500, 900, 'large', 'medium', 900000, 9, 13, 17),
  ('Theme park', 'BQ-RWD-THEME-PARK', 3000, 280, 'large', 'experience', 280000, 6, 10, 15),
  ('Bicycle', 'BQ-RWD-BICYCLE', 5000, 2200, 'dream', 'large', 2200000, 6, 9, 14),
  ('Smart watch', 'BQ-RWD-SMART-WATCH', 5000, 2000, 'large', 'large', 2000000, 6, 8, 11),
  ('Apple Watch', 'BQ-RWD-APPLE-WATCH', 6000, 6400, 'dream', 'dream', 6400000, 12, 14, 17),
  ('iPad', 'BQ-RWD-IPAD', 8000, 12000, 'dream', 'dream', 12000000, 8, 12, 17),
  ('Special family resort trip', 'BQ-RWD-SPECIAL-FAMILY-RESORT-TRIP', 10000, 5000, 'dream', 'dream', 5000000, 6, 11, 17),
  ('Singapore Adventure', 'BQ-RWD-SINGAPORE-ADVENTURE', 15000, 12500, 'dream', 'dream', 12500000, 6, 12, 17)
) as v(name, key, old_coin, new_coin, old_cat, new_cat, vnd, min_age, rec_age, max_age)
where r.is_system_template = false and r.name = v.name;

-- 5. Family quests in progress (only untouched values)
update family_quests f set coin_reward = v.new_coin
from (values
  ('Read 5 Books Together', 300, 50),
  ('Family Walk Week', 200, 30),
  ('Screen-Free Evening', 250, 25),
  ('Math Masters', 400, 100),
  ('English Conversation Week', 300, 25),
  ('Game Night x4', 200, 20),
  ('Cook Together', 150, 45),
  ('Family Reading Week', 200, 35),
  ('Tidy House Challenge', 0, 0),
  ('Morning Routine Streak', 0, 0)
) as v(title, old_coin, new_coin)
where f.is_system_template = false and f.title = v.title and f.coin_reward = v.old_coin;
