-- 0027_seed_curriculum.sql — Seed System Quest templates (Ages 7-12, ~90 templates)
-- Source: docs/BloomQuest_System_Quest_Curriculum_Implementation_Plan.md §25

-- =============================================
-- AGE 7 — "I can do things by myself" (15 templates)
-- =============================================
INSERT INTO tasks (
  family_id, name, name_vi, description, description_vi,
  category, skill_domain, behavior_type, availability_type,
  coin_reward, star_reward, difficulty, independence_level,
  min_age, recommended_age, max_age,
  development_goal, development_goal_vi, parent_tip, parent_tip_vi,
  template_key, skill_ladder_key, skill_ladder_level,
  requires_approval, requires_supervision, in_pool, pool_max_per_day,
  estimated_minutes, recommended_frequency,
  is_system_template, active
) VALUES
(
  '00000000-0000-0000-0000-000000000000',
  'Make My Bed', 'Dọn Giường Mỗi Sáng',
  'Make your bed neatly every morning', 'Tự dọn giường gọn gàng mỗi sáng',
  'responsibility', 'LIFE_HOME', 'responsibility', 'assigned_only',
  0, 0, 1, 'GUIDED',
  6, 7, 9,
  'Build the habit of starting the day with a completed task.',
  'Tập thói quen bắt đầu ngày mới bằng việc hoàn thành một công việc.',
  'Show the steps once, then let the child try independently.',
  'Hướng dẫn một lần, sau đó để con tự làm.',
  'BQ-LIFE-MAKE-BED-A07', 'HOUSEHOLD_CARE', 1,
  false, false, false, null,
  5, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Put Dirty Clothes in the Basket', 'Bỏ Đồ Bẩn Vào Giỏ',
  'Put your dirty clothes in the laundry basket after changing', 'Bỏ quần áo bẩn vào giỏ sau khi thay đồ',
  'responsibility', 'LIFE_HOME', 'responsibility', 'assigned_only',
  0, 0, 1, 'GUIDED',
  6, 7, 9,
  'Learn to manage personal belongings responsibly.',
  'Học cách quản lý đồ dùng cá nhân có trách nhiệm.',
  'Place the basket where the child can reach it easily.',
  'Đặt giỏ ở nơi con dễ với tới.',
  'BQ-LIFE-DIRTY-CLOTHES-A07', 'HOUSEHOLD_CARE', 1,
  false, false, false, null,
  2, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Clear My Plate', 'Dọn Đĩa Sau Khi Ăn',
  'Bring your plate and utensils to the kitchen after eating', 'Mang đĩa và đồ ăn vào bếp sau khi ăn xong',
  'responsibility', 'LIFE_HOME', 'responsibility', 'both',
  0, 0, 1, 'GUIDED',
  6, 7, 9,
  'Contribute to family meal routine and learn personal responsibility.',
  'Góp phần vào nếp sinh hoạt gia đình và học trách nhiệm cá nhân.',
  'Praise effort even if they need reminding at first.',
  'Khen ngợi nỗ lực dù con cần nhắc nhở lúc đầu.',
  'BQ-LIFE-CLEAR-PLATE-A07', 'HOUSEHOLD_CARE', 1,
  false, false, true, 1,
  2, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Put Toys and Books Back', 'Cất Đồ Chơi và Sách',
  'Put toys and books back in their places when done', 'Cất đồ chơi và sách vào đúng chỗ khi chơi xong',
  'responsibility', 'SELF_MANAGEMENT', 'responsibility', 'both',
  0, 0, 1, 'GUIDED',
  6, 7, 9,
  'Learn to finish a task completely by cleaning up afterwards.',
  'Học cách hoàn thành công việc bằng cách dọn dẹp sau khi chơi.',
  'Make sure storage is accessible and clearly labeled.',
  'Đảm bảo nơi cất đồ dễ với và có nhãn rõ ràng.',
  'BQ-SELF-TIDY-TOYS-A07', 'PERSONAL_ORGANIZATION', 1,
  false, false, true, 1,
  5, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Prepare School Bag with Checklist', 'Chuẩn Bị Cặp Sách Theo Danh Sách',
  'Pack your school bag using a checklist the night before', 'Chuẩn bị cặp sách theo danh sách tối hôm trước',
  'responsibility', 'SELF_MANAGEMENT', 'habit_building', 'assigned_only',
  3, 1, 2, 'GUIDED',
  6, 7, 9,
  'Build a preparation routine that prevents morning rush.',
  'Xây dựng thói quen chuẩn bị giúp tránh vội vàng buổi sáng.',
  'Create a simple visual checklist together.',
  'Cùng con tạo một danh sách kiểm tra đơn giản bằng hình ảnh.',
  'BQ-SELF-SCHOOL-BAG-A07', 'PERSONAL_ORGANIZATION', 1,
  true, false, false, null,
  10, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Water the Plants', 'Tưới Cây',
  'Water the house plants regularly', 'Tưới cây trong nhà thường xuyên',
  'responsibility', 'LIFE_HOME', 'responsibility', 'both',
  0, 0, 1, 'GUIDED',
  6, 7, 9,
  'Care for shared household needs and learn consistency.',
  'Chăm sóc nhu cầu chung của gia đình và học tính kiên trì.',
  'Show how much water each plant needs once.',
  'Hướng dẫn lượng nước mỗi cây cần một lần.',
  'BQ-LIFE-WATER-PLANTS-A07', 'HOUSEHOLD_CARE', 1,
  false, false, true, 1,
  5, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Read for 15 Minutes', 'Đọc Sách 15 Phút',
  'Read a book or story for at least 15 minutes', 'Đọc sách hoặc truyện ít nhất 15 phút',
  'learning', 'LEARNING', 'habit_building', 'both',
  3, 1, 2, 'GUIDED',
  6, 7, 9,
  'Build consistent reading habit and improve literacy.',
  'Xây dựng thói quen đọc sách đều đặn và cải thiện khả năng đọc.',
  'Let the child choose what to read. Sit together if possible.',
  'Để con chọn sách. Ngồi cùng nếu có thể.',
  'BQ-LEARN-READ-15-A07', 'READING', 1,
  true, false, true, 1,
  15, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Read a Story Aloud', 'Đọc Truyện Thành Tiếng',
  'Read a short story aloud to practice speaking', 'Đọc một câu chuyện ngắn thành tiếng để luyện nói',
  'learning', 'COMMUNICATION', 'challenge', 'choice_pool',
  5, 1, 3, 'GUIDED',
  6, 7, 9,
  'Build speaking confidence and pronunciation skills.',
  'Xây dựng tự tin khi nói và kỹ năng phát âm.',
  'Listen actively and praise effort over perfection.',
  'Lắng nghe chủ động và khen ngợi nỗ lực hơn sự hoàn hảo.',
  'BQ-COMM-READ-ALOUD-A07', 'COMMUNICATION', 1,
  true, false, true, 1,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Learn 5 English Words', 'Học 5 Từ Tiếng Anh',
  'Learn and practice 5 new English vocabulary words', 'Học và luyện tập 5 từ vựng tiếng Anh mới',
  'learning', 'LEARNING', 'challenge', 'choice_pool',
  5, 1, 3, 'GUIDED',
  6, 7, 9,
  'Build vocabulary through regular small learning goals.',
  'Xây dựng vốn từ vựng qua các mục tiêu nhỏ thường xuyên.',
  'Use flashcards or games. Make it fun, not like a test.',
  'Dùng thẻ từ hoặc trò chơi. Làm cho vui, không giống bài kiểm tra.',
  'BQ-LEARN-ENG-WORDS-A07', 'READING', 1,
  true, false, true, 1,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Draw and Explain My Picture', 'Vẽ và Giải Thích Bức Tranh',
  'Draw something creative and explain what it is', 'Vẽ một bức tranh sáng tạo và giải thích nó là gì',
  'creativity', 'COMMUNICATION', 'challenge', 'choice_pool',
  5, 1, 3, 'GUIDED',
  6, 7, 9,
  'Practice creative expression and verbal explanation.',
  'Luyện biểu đạt sáng tạo và giải thích bằng lời.',
  'Ask open questions about the drawing. No right or wrong.',
  'Đặt câu hỏi mở về bức tranh. Không có đúng sai.',
  'BQ-COMM-DRAW-EXPLAIN-A07', null, null,
  true, false, true, 1,
  20, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Learn 3 Facts About an Animal', 'Tìm Hiểu 3 Điều Về Một Con Vật',
  'Research and share 3 interesting facts about an animal', 'Tìm hiểu và chia sẻ 3 điều thú vị về một con vật',
  'learning', 'LEARNING', 'challenge', 'choice_pool',
  5, 1, 3, 'GUIDED',
  6, 7, 9,
  'Spark curiosity and practice simple research skills.',
  'Khơi dậy sự tò mò và luyện kỹ năng tìm hiểu đơn giản.',
  'Help find a book or website. Let the child choose the animal.',
  'Giúp tìm sách hoặc trang web. Để con chọn con vật.',
  'BQ-LEARN-ANIMAL-FACTS-A07', 'RESEARCH', 1,
  true, false, true, 1,
  20, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Help Prepare Fruit or a Snack', 'Giúp Chuẩn Bị Trái Cây Hoặc Đồ Ăn Nhẹ',
  'Help wash and prepare fruit or a simple snack', 'Giúp rửa và chuẩn bị trái cây hoặc đồ ăn nhẹ đơn giản',
  'responsibility', 'LIFE_HOME', 'challenge', 'choice_pool',
  5, 1, 2, 'GUIDED',
  6, 7, 9,
  'Introduction to food preparation in a safe way.',
  'Bước đầu làm quen với việc chuẩn bị thức ăn an toàn.',
  'Supervise but let the child do the work. Use safe tools.',
  'Giám sát nhưng để con tự làm. Dùng dụng cụ an toàn.',
  'BQ-LIFE-PREP-FRUIT-A07', 'COOKING', 1,
  true, true, true, 1,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Do One Kind Thing', 'Làm Một Điều Tốt',
  'Notice and do one kind thing for someone today', 'Để ý và làm một điều tốt cho ai đó hôm nay',
  'family', 'CHARACTER_FAMILY', 'character', 'choice_pool',
  0, 2, 2, 'GUIDED',
  6, 7, 10,
  'Notice opportunities to help and practice empathy.',
  'Để ý cơ hội giúp đỡ và luyện sự đồng cảm.',
  'Ask at dinner: "What kind thing did you do today?"',
  'Hỏi lúc ăn tối: "Hôm nay con đã làm điều tốt gì?"',
  'BQ-CHAR-KIND-THING-A07', 'FAMILY_CONTRIBUTION', 1,
  true, false, true, 1,
  5, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Needs or Wants?', 'Cần Hay Muốn?',
  'Look at 5 items and decide if each is a need or a want', 'Xem 5 món đồ và quyết định mỗi thứ là cần thiết hay muốn có',
  'learning', 'MONEY', 'challenge', 'choice_pool',
  5, 1, 2, 'GUIDED',
  6, 7, 9,
  'Learn basic spending judgment — needs vs wants.',
  'Học phán đoán chi tiêu cơ bản — cần thiết hay mong muốn.',
  'Use real examples from a store or catalog.',
  'Dùng ví dụ thực từ cửa hàng hoặc tờ quảng cáo.',
  'BQ-MONEY-NEEDS-WANTS-A07', 'MONEY', 1,
  true, false, true, 1,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Save for One Small Goal', 'Tiết Kiệm Cho Một Mục Tiêu Nhỏ',
  'Set a small savings goal and track progress towards it', 'Đặt mục tiêu tiết kiệm nhỏ và theo dõi tiến độ',
  'learning', 'MONEY', 'habit_building', 'both',
  3, 1, 2, 'GUIDED',
  6, 7, 9,
  'Practice delayed gratification and goal-setting.',
  'Luyện tập trì hoãn mong muốn tức thời và đặt mục tiêu.',
  'Help set a realistic small goal. Celebrate when reached.',
  'Giúp đặt mục tiêu nhỏ thực tế. Chúc mừng khi đạt được.',
  'BQ-MONEY-SAVE-GOAL-A07', 'MONEY', 2,
  true, false, true, 1,
  10, 'weekly',
  true, true
)
ON CONFLICT DO NOTHING;

-- =============================================
-- AGE 8 — "I can remember my responsibilities" (15 templates)
-- =============================================
INSERT INTO tasks (
  family_id, name, name_vi, description, description_vi,
  category, skill_domain, behavior_type, availability_type,
  coin_reward, star_reward, difficulty, independence_level,
  min_age, recommended_age, max_age,
  development_goal, development_goal_vi, parent_tip, parent_tip_vi,
  template_key, skill_ladder_key, skill_ladder_level,
  requires_approval, requires_supervision, in_pool, pool_max_per_day,
  estimated_minutes, recommended_frequency,
  is_system_template, active
) VALUES
(
  '00000000-0000-0000-0000-000000000000',
  'Keep My Study Desk Tidy', 'Giữ Bàn Học Gọn Gàng',
  'Keep your study desk organized and clean', 'Giữ bàn học ngăn nắp và sạch sẽ',
  'responsibility', 'LIFE_HOME', 'responsibility', 'assigned_only',
  0, 0, 2, 'SUPPORTED',
  7, 8, 10,
  'Maintain an organized workspace for better focus.',
  'Duy trì không gian làm việc ngăn nắp để tập trung tốt hơn.',
  'Help set up desk organization systems that work for the child.',
  'Giúp thiết lập hệ thống sắp xếp bàn phù hợp với con.',
  'BQ-LIFE-TIDY-DESK-A08', 'PERSONAL_ORGANIZATION', 2,
  false, false, false, null,
  10, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Set the Dinner Table', 'Bày Bàn Ăn Tối',
  'Set the table for family dinner with correct placement', 'Bày bàn ăn tối cho gia đình đúng cách',
  'responsibility', 'LIFE_HOME', 'responsibility', 'both',
  0, 0, 2, 'SUPPORTED',
  7, 8, 10,
  'Contribute to family mealtime and learn routine.',
  'Góp phần vào bữa ăn gia đình và học nề nếp.',
  'Show the layout once, then let them do it independently.',
  'Hướng dẫn cách bày một lần, sau đó để con tự làm.',
  'BQ-LIFE-SET-TABLE-A08', 'HOUSEHOLD_CARE', 2,
  false, false, true, 1,
  5, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Sort Laundry', 'Phân Loại Quần Áo',
  'Sort dirty laundry by color (darks, lights, whites)', 'Phân loại quần áo bẩn theo màu (tối, sáng, trắng)',
  'responsibility', 'LIFE_HOME', 'responsibility', 'both',
  0, 0, 2, 'SUPPORTED',
  7, 8, 10,
  'Learn laundry basics and contribute to household routine.',
  'Học cơ bản về giặt giũ và góp phần vào sinh hoạt gia đình.',
  'Make it a game: "Can you sort these into the right piles?"',
  'Biến thành trò chơi: "Con phân loại vào đúng đống nhé?"',
  'BQ-LIFE-SORT-LAUNDRY-A08', 'HOUSEHOLD_CARE', 2,
  false, false, true, 1,
  10, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Put Away My Clean Clothes', 'Cất Quần Áo Sạch',
  'Fold and put away clean clothes in the right places', 'Gấp và cất quần áo sạch vào đúng chỗ',
  'responsibility', 'LIFE_HOME', 'responsibility', 'assigned_only',
  0, 0, 2, 'SUPPORTED',
  7, 8, 10,
  'Build independence in managing personal belongings.',
  'Xây dựng tính tự lập trong quản lý đồ dùng cá nhân.',
  'Label drawers or shelves to make it easier.',
  'Dán nhãn ngăn kéo hoặc kệ để dễ cất hơn.',
  'BQ-LIFE-PUT-CLOTHES-A08', 'HOUSEHOLD_CARE', 2,
  false, false, false, null,
  10, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Feed a Pet', 'Cho Thú Cưng Ăn',
  'Feed and give water to a family pet on time', 'Cho thú cưng ăn và uống nước đúng giờ',
  'family', 'CHARACTER_FAMILY', 'responsibility', 'both',
  0, 0, 2, 'SUPPORTED',
  7, 8, 10,
  'Learn consistent care and responsibility for a living being.',
  'Học chăm sóc đều đặn và trách nhiệm với sinh vật sống.',
  'Set a reminder together at first, then phase it out.',
  'Cùng đặt nhắc nhở lúc đầu, sau đó dần bỏ.',
  'BQ-CHAR-FEED-PET-A08', 'FAMILY_CONTRIBUTION', 2,
  false, false, true, 1,
  5, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Prepare School Bag Independently', 'Tự Chuẩn Bị Cặp Sách',
  'Pack your school bag without needing a checklist', 'Chuẩn bị cặp sách mà không cần danh sách',
  'responsibility', 'SELF_MANAGEMENT', 'habit_building', 'assigned_only',
  3, 1, 2, 'SUPPORTED',
  7, 8, 10,
  'Transition from checklist-guided to memory-based preparation.',
  'Chuyển từ chuẩn bị theo danh sách sang chuẩn bị bằng trí nhớ.',
  'Check occasionally but don''t nag. Let natural consequences teach.',
  'Thỉnh thoảng kiểm tra nhưng không cằn nhằn. Để hậu quả tự nhiên dạy con.',
  'BQ-SELF-SCHOOL-BAG-A08', 'PERSONAL_ORGANIZATION', 2,
  true, false, false, null,
  10, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Read for 20 Minutes', 'Đọc Sách 20 Phút',
  'Read a book of your choice for at least 20 minutes', 'Đọc sách tự chọn ít nhất 20 phút',
  'learning', 'LEARNING', 'habit_building', 'both',
  3, 1, 2, 'SUPPORTED',
  7, 8, 10,
  'Extend reading stamina and build a daily habit.',
  'Tăng sức bền đọc sách và xây dựng thói quen hàng ngày.',
  'Provide a variety of reading material. Don''t force a specific book.',
  'Cung cấp đa dạng tài liệu đọc. Không ép đọc sách cụ thể.',
  'BQ-LEARN-READ-20-A08', 'READING', 2,
  true, false, true, 1,
  20, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Finish One Responsibility Before Entertainment', 'Hoàn Thành Một Trách Nhiệm Trước Khi Giải Trí',
  'Complete at least one responsibility before screen time or play', 'Hoàn thành ít nhất một trách nhiệm trước khi xem màn hình hay chơi',
  'responsibility', 'SELF_MANAGEMENT', 'habit_building', 'assigned_only',
  3, 1, 3, 'SUPPORTED',
  7, 8, 10,
  'Build the habit of prioritizing responsibilities over entertainment.',
  'Xây dựng thói quen ưu tiên trách nhiệm hơn giải trí.',
  'Be consistent with the rule. Praise when they do it without reminding.',
  'Kiên định với quy tắc. Khen khi con tự làm mà không cần nhắc.',
  'BQ-SELF-RESP-FIRST-A08', 'PERSONAL_ORGANIZATION', 2,
  true, false, false, null,
  5, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Weekly Tidy-Up', 'Dọn Dẹp Cuối Tuần',
  'Spend 15 minutes tidying your room and personal spaces', 'Dành 15 phút dọn dẹp phòng và khu vực cá nhân',
  'responsibility', 'LIFE_HOME', 'habit_building', 'both',
  3, 1, 2, 'SUPPORTED',
  7, 8, 10,
  'Maintain personal space through regular tidying.',
  'Duy trì không gian cá nhân bằng việc dọn dẹp thường xuyên.',
  'Set a timer together. Make it a routine, not a punishment.',
  'Đặt hẹn giờ cùng nhau. Biến thành thói quen, không phải hình phạt.',
  'BQ-LIFE-WEEKLY-TIDY-A08', 'HOUSEHOLD_CARE', 2,
  true, false, true, 1,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Make a Simple Sandwich', 'Làm Một Chiếc Bánh Mì Đơn Giản',
  'Make a sandwich or simple snack by yourself', 'Tự làm một chiếc bánh mì hoặc đồ ăn nhẹ đơn giản',
  'responsibility', 'LIFE_HOME', 'challenge', 'choice_pool',
  5, 1, 3, 'SUPPORTED',
  7, 8, 10,
  'Build basic food preparation skills independently.',
  'Xây dựng kỹ năng chuẩn bị thức ăn cơ bản.',
  'Show once, then let them try. Accept imperfection.',
  'Hướng dẫn một lần, sau đó để con thử. Chấp nhận sự chưa hoàn hảo.',
  'BQ-LIFE-SANDWICH-A08', 'COOKING', 2,
  true, false, true, 1,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Tell What I Learned Today', 'Kể Điều Con Học Được Hôm Nay',
  'Share one thing you learned at school or from reading', 'Chia sẻ một điều con học được ở trường hoặc từ sách',
  'learning', 'COMMUNICATION', 'challenge', 'choice_pool',
  5, 1, 3, 'SUPPORTED',
  7, 8, 10,
  'Practice verbal expression and reflection on learning.',
  'Luyện diễn đạt bằng lời và phản ánh về việc học.',
  'Listen actively. Ask follow-up questions to show interest.',
  'Lắng nghe chủ động. Đặt câu hỏi tiếp theo để thể hiện sự quan tâm.',
  'BQ-COMM-TELL-LEARNED-A08', 'COMMUNICATION', 2,
  true, false, true, 1,
  10, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Speak English for 2 Minutes', 'Nói Tiếng Anh 2 Phút',
  'Have a short English conversation for at least 2 minutes', 'Trò chuyện bằng tiếng Anh ít nhất 2 phút',
  'learning', 'COMMUNICATION', 'challenge', 'choice_pool',
  5, 1, 3, 'SUPPORTED',
  7, 8, 10,
  'Build confidence speaking English in everyday situations.',
  'Xây dựng tự tin khi nói tiếng Anh trong tình huống hàng ngày.',
  'Speak English together casually. Don''t correct every mistake.',
  'Nói tiếng Anh cùng con một cách thoải mái. Không sửa mọi lỗi.',
  'BQ-COMM-ENG-SPEAK-A08', 'COMMUNICATION', 2,
  true, false, true, 1,
  5, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Learn About Another Country', 'Tìm Hiểu Về Một Nước Khác',
  'Research and share 3 facts about a country you pick', 'Tìm hiểu và chia sẻ 3 điều về một đất nước con chọn',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  5, 1, 3, 'SUPPORTED',
  7, 8, 10,
  'Develop curiosity about the wider world and different cultures.',
  'Phát triển sự tò mò về thế giới rộng lớn và các nền văn hóa khác.',
  'Help find kid-friendly resources. Let the child choose the country.',
  'Giúp tìm nguồn tài liệu phù hợp. Để con chọn quốc gia.',
  'BQ-WORLD-COUNTRY-A08', 'TRAVEL_NAVIGATION', 1,
  true, false, true, 1,
  20, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Make a Small Shopping List', 'Lập Danh Sách Mua Sắm Nhỏ',
  'Write a shopping list for a simple meal or snack', 'Viết danh sách mua sắm cho một bữa ăn nhẹ đơn giản',
  'learning', 'MONEY', 'challenge', 'choice_pool',
  5, 1, 3, 'SUPPORTED',
  7, 8, 10,
  'Practice planning and listing items needed for a goal.',
  'Luyện lập kế hoạch và liệt kê các thứ cần cho một mục tiêu.',
  'Go shopping together and check off the list items.',
  'Đi mua sắm cùng nhau và đánh dấu các mục trong danh sách.',
  'BQ-MONEY-SHOP-LIST-A08', 'MONEY', 3,
  true, false, true, 1,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Compare the Price of Two Snacks', 'So Sánh Giá Hai Món Ăn Vặt',
  'At a store, compare two snacks and choose the better value', 'Ở cửa hàng, so sánh hai món ăn vặt và chọn giá trị tốt hơn',
  'learning', 'MONEY', 'challenge', 'choice_pool',
  5, 1, 3, 'SUPPORTED',
  7, 8, 10,
  'Practice comparing prices and making informed spending decisions.',
  'Luyện so sánh giá và đưa ra quyết định chi tiêu thông minh.',
  'Let the child make the final choice. Discuss reasoning afterwards.',
  'Để con đưa ra lựa chọn cuối cùng. Thảo luận lý do sau đó.',
  'BQ-MONEY-COMPARE-PRICE-A08', 'MONEY', 2,
  true, false, true, 1,
  15, 'weekly',
  true, true
)
ON CONFLICT DO NOTHING;

-- =============================================
-- AGE 9 — "I can organize myself" (15 templates)
-- =============================================
INSERT INTO tasks (
  family_id, name, name_vi, description, description_vi,
  category, skill_domain, behavior_type, availability_type,
  coin_reward, star_reward, difficulty, independence_level,
  min_age, recommended_age, max_age,
  development_goal, development_goal_vi, parent_tip, parent_tip_vi,
  template_key, skill_ladder_key, skill_ladder_level,
  requires_approval, requires_supervision, in_pool, pool_max_per_day,
  estimated_minutes, recommended_frequency,
  is_system_template, active
) VALUES
(
  '00000000-0000-0000-0000-000000000000',
  'Fold and Put Away My Clothes', 'Gấp và Cất Quần Áo',
  'Fold clean laundry and put everything in the right place', 'Gấp quần áo sạch và cất vào đúng chỗ',
  'responsibility', 'LIFE_HOME', 'responsibility', 'assigned_only',
  0, 0, 2, 'SUPPORTED',
  8, 9, 11,
  'Build laundry independence step by step.',
  'Xây dựng tính tự lập trong giặt giũ từng bước.',
  'Teach folding techniques once, then let them practice.',
  'Dạy cách gấp một lần, sau đó để con tự luyện.',
  'BQ-LIFE-FOLD-CLOTHES-A09', 'HOUSEHOLD_CARE', 3,
  false, false, false, null,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Vacuum a Small Area', 'Hút Bụi Một Khu Vực Nhỏ',
  'Vacuum your room or a small area of the house', 'Hút bụi phòng con hoặc một khu vực nhỏ trong nhà',
  'responsibility', 'LIFE_HOME', 'responsibility', 'both',
  0, 0, 2, 'SUPPORTED',
  8, 9, 11,
  'Learn to maintain shared living spaces.',
  'Học cách duy trì không gian sống chung.',
  'Show how to use the vacuum safely. Let them own the task.',
  'Hướng dẫn cách dùng máy hút bụi an toàn. Để con tự chịu trách nhiệm.',
  'BQ-LIFE-VACUUM-A09', 'HOUSEHOLD_CARE', 3,
  false, false, true, 1,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Prepare My Own Simple Snack', 'Tự Chuẩn Bị Đồ Ăn Nhẹ',
  'Prepare a simple snack or breakfast independently', 'Tự chuẩn bị đồ ăn nhẹ hoặc bữa sáng đơn giản',
  'responsibility', 'LIFE_HOME', 'responsibility', 'both',
  0, 0, 2, 'SUPPORTED',
  8, 9, 11,
  'Grow food preparation independence for simple meals.',
  'Phát triển tính tự lập trong chuẩn bị bữa ăn đơn giản.',
  'Stock safe, accessible ingredients. Accept creative results.',
  'Chuẩn bị nguyên liệu an toàn, dễ lấy. Chấp nhận kết quả sáng tạo.',
  'BQ-LIFE-OWN-SNACK-A09', 'COOKING', 3,
  false, false, true, 1,
  15, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Organize School Supplies', 'Sắp Xếp Đồ Dùng Học Tập',
  'Keep school supplies organized and replenished', 'Giữ đồ dùng học tập ngăn nắp và đầy đủ',
  'responsibility', 'SELF_MANAGEMENT', 'responsibility', 'assigned_only',
  0, 0, 2, 'SUPPORTED',
  8, 9, 11,
  'Take ownership of academic preparation.',
  'Tự chịu trách nhiệm chuẩn bị học tập.',
  'Check together weekly at first, then let them manage alone.',
  'Kiểm tra cùng nhau hàng tuần lúc đầu, sau đó để con tự quản lý.',
  'BQ-SELF-SCHOOL-SUPPLIES-A09', 'PERSONAL_ORGANIZATION', 3,
  false, false, false, null,
  10, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Own One Household Area', 'Phụ Trách Một Khu Vực Trong Nhà',
  'Take responsibility for keeping one area of the house clean', 'Chịu trách nhiệm giữ sạch một khu vực trong nhà',
  'family', 'CHARACTER_FAMILY', 'responsibility', 'assigned_only',
  0, 0, 3, 'SUPPORTED',
  8, 9, 11,
  'Build a sense of family contribution and ownership.',
  'Xây dựng tinh thần đóng góp cho gia đình và ý thức sở hữu.',
  'Let the child choose their area. Review together weekly.',
  'Để con chọn khu vực. Kiểm tra cùng nhau hàng tuần.',
  'BQ-CHAR-OWN-AREA-A09', 'FAMILY_CONTRIBUTION', 2,
  false, false, false, null,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  '25-Minute Focus Time', 'Tập Trung 25 Phút',
  'Study or work on a task with focus for 25 minutes', 'Học hoặc làm việc tập trung trong 25 phút',
  'learning', 'SELF_MANAGEMENT', 'habit_building', 'both',
  3, 1, 3, 'SUPPORTED',
  8, 9, 11,
  'Build sustained attention and focus stamina.',
  'Xây dựng sự chú ý bền bỉ và sức bền tập trung.',
  'Use a timer. Start with 15 minutes if 25 is too long.',
  'Dùng đồng hồ hẹn giờ. Bắt đầu 15 phút nếu 25 phút quá dài.',
  'BQ-SELF-FOCUS-25-A09', 'PLANNING', 1,
  true, false, true, 1,
  25, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Start Homework Without Reminder', 'Tự Bắt Đầu Bài Tập',
  'Begin homework at the regular time without being told', 'Tự bắt đầu làm bài tập đúng giờ mà không cần nhắc',
  'responsibility', 'SELF_MANAGEMENT', 'habit_building', 'assigned_only',
  3, 1, 3, 'SUPPORTED',
  8, 9, 11,
  'Build internal motivation for academic responsibilities.',
  'Xây dựng động lực nội tại cho trách nhiệm học tập.',
  'Set up a consistent study time. Praise initiative over results.',
  'Thiết lập thời gian học cố định. Khen ngợi sự chủ động hơn kết quả.',
  'BQ-SELF-HW-NO-REMIND-A09', 'PLANNING', 1,
  true, false, false, null,
  5, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Prepare Tomorrow Before Bed', 'Chuẩn Bị Ngày Mai Trước Khi Ngủ',
  'Lay out clothes and check bag for tomorrow before bedtime', 'Chuẩn bị quần áo và kiểm tra cặp cho ngày mai trước giờ ngủ',
  'responsibility', 'SELF_MANAGEMENT', 'habit_building', 'assigned_only',
  3, 1, 2, 'SUPPORTED',
  8, 9, 11,
  'Build a nightly preparation routine for smoother mornings.',
  'Xây dựng thói quen chuẩn bị tối để buổi sáng suôn sẻ hơn.',
  'Make it part of the bedtime routine, not a separate chore.',
  'Biến thành phần của thói quen trước giờ ngủ, không phải việc riêng.',
  'BQ-SELF-PREP-TOMORROW-A09', 'PERSONAL_ORGANIZATION', 3,
  true, false, false, null,
  10, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Weekly Reading Goal', 'Mục Tiêu Đọc Sách Tuần',
  'Set and track a weekly reading goal (pages or minutes)', 'Đặt và theo dõi mục tiêu đọc sách hàng tuần (trang hoặc phút)',
  'learning', 'LEARNING', 'habit_building', 'both',
  3, 1, 3, 'SUPPORTED',
  8, 9, 11,
  'Transition from daily reminders to self-tracked weekly goals.',
  'Chuyển từ nhắc nhở hàng ngày sang tự theo dõi mục tiêu tuần.',
  'Let the child set their own realistic goal.',
  'Để con tự đặt mục tiêu thực tế của mình.',
  'BQ-LEARN-WEEKLY-READ-A09', 'READING', 3,
  true, false, true, 1,
  30, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Create a Shopping List Under 100,000đ', 'Lập Danh Sách Mua Sắm Dưới 100.000đ',
  'Plan a shopping list for a meal or snack within a budget', 'Lập danh sách mua sắm cho một bữa ăn trong ngân sách',
  'learning', 'MONEY', 'challenge', 'choice_pool',
  8, 2, 4, 'SUPPORTED',
  8, 9, 11,
  'Practice budgeting within a limit.',
  'Luyện lập ngân sách trong giới hạn.',
  'Let the child make the first list. Ask questions instead of correcting.',
  'Để con lập danh sách đầu tiên. Hỏi thay vì sửa.',
  'BQ-MONEY-BUDGET-LIST-A09', 'MONEY', 3,
  true, false, true, 1,
  20, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Research One Interesting Question', 'Tìm Hiểu Một Câu Hỏi Thú Vị',
  'Pick a question you''re curious about and find the answer', 'Chọn một câu hỏi con tò mò và tìm câu trả lời',
  'learning', 'LEARNING', 'challenge', 'choice_pool',
  8, 2, 4, 'SUPPORTED',
  8, 9, 11,
  'Build research skills and structured curiosity.',
  'Xây dựng kỹ năng nghiên cứu và tính tò mò có hệ thống.',
  'Help find reliable sources. Guide, don''t give the answer.',
  'Giúp tìm nguồn đáng tin cậy. Hướng dẫn, không cho câu trả lời.',
  'BQ-LEARN-RESEARCH-Q-A09', 'RESEARCH', 1,
  true, false, true, 1,
  30, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Give a 2-Minute Presentation', 'Thuyết Trình 2 Phút',
  'Present something you learned to your family for 2 minutes', 'Thuyết trình một điều con học được cho gia đình trong 2 phút',
  'learning', 'COMMUNICATION', 'challenge', 'choice_pool',
  8, 2, 4, 'SUPPORTED',
  8, 9, 11,
  'Build public speaking confidence and organization skills.',
  'Xây dựng tự tin thuyết trình và kỹ năng tổ chức ý.',
  'Be an enthusiastic audience. Clap and ask questions.',
  'Làm khán giả nhiệt tình. Vỗ tay và đặt câu hỏi.',
  'BQ-COMM-PRESENT-2-A09', 'COMMUNICATION', 3,
  true, false, true, 1,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Learn Basic First Aid for a Small Scratch', 'Học Sơ Cứu Cơ Bản Cho Vết Xước Nhỏ',
  'Learn how to clean and bandage a small cut or scratch', 'Học cách rửa và băng một vết cắt hoặc trầy xước nhỏ',
  'health', 'HEALTH', 'challenge', 'choice_pool',
  8, 2, 4, 'SUPPORTED',
  8, 9, 11,
  'Learn basic self-care and safety skills.',
  'Học kỹ năng tự chăm sóc và an toàn cơ bản.',
  'Practice together with a first aid kit. Supervise closely.',
  'Luyện tập cùng nhau với bộ sơ cứu. Giám sát chặt chẽ.',
  'BQ-HEALTH-FIRST-AID-A09', null, null,
  true, true, true, 1,
  20, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Interview Grandparents About Childhood', 'Phỏng Vấn Ông Bà Về Thời Thơ Ấu',
  'Ask grandparents about their childhood and share what you learned', 'Hỏi ông bà về thời thơ ấu và chia sẻ điều con học được',
  'family', 'CHARACTER_FAMILY', 'challenge', 'choice_pool',
  8, 2, 4, 'SUPPORTED',
  8, 9, 11,
  'Strengthen family connections and practice interview skills.',
  'Gắn kết gia đình và luyện kỹ năng phỏng vấn.',
  'Help prepare 3-5 questions beforehand. Record if possible.',
  'Giúp chuẩn bị 3-5 câu hỏi trước. Ghi âm nếu có thể.',
  'BQ-CHAR-INTERVIEW-GRANDPARENTS-A09', 'FAMILY_CONTRIBUTION', 3,
  true, false, true, 1,
  30, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Navigate a Familiar Place Using a Map', 'Tìm Đường Bằng Bản Đồ Ở Nơi Quen',
  'Use a map to navigate a familiar neighborhood or park', 'Dùng bản đồ để tìm đường ở khu phố hoặc công viên quen thuộc',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  8, 2, 4, 'SUPPORTED',
  8, 9, 11,
  'Build spatial awareness and navigation skills.',
  'Xây dựng nhận thức không gian và kỹ năng tìm đường.',
  'Walk together. Let the child lead with the map.',
  'Đi cùng nhau. Để con dẫn đường với bản đồ.',
  'BQ-WORLD-MAP-NAV-A09', 'TRAVEL_NAVIGATION', 1,
  true, true, true, 1,
  30, 'once',
  true, true
)
ON CONFLICT DO NOTHING;

-- =============================================
-- AGE 10 — "I can plan ahead" (15 templates)
-- =============================================
INSERT INTO tasks (
  family_id, name, name_vi, description, description_vi,
  category, skill_domain, behavior_type, availability_type,
  coin_reward, star_reward, difficulty, independence_level,
  min_age, recommended_age, max_age,
  development_goal, development_goal_vi, parent_tip, parent_tip_vi,
  template_key, skill_ladder_key, skill_ladder_level,
  requires_approval, requires_supervision, in_pool, pool_max_per_day,
  estimated_minutes, recommended_frequency,
  is_system_template, active
) VALUES
(
  '00000000-0000-0000-0000-000000000000',
  'Help Prepare Dinner', 'Giúp Chuẩn Bị Bữa Tối',
  'Help with dinner preparation (washing, cutting safe items, setting up)', 'Giúp chuẩn bị bữa tối (rửa, cắt đồ an toàn, bày biện)',
  'responsibility', 'LIFE_HOME', 'responsibility', 'both',
  0, 0, 3, 'SUPPORTED',
  9, 10, 12,
  'Contribute meaningfully to family meal preparation.',
  'Đóng góp có ý nghĩa vào việc chuẩn bị bữa ăn gia đình.',
  'Assign age-appropriate tasks. Supervise sharp tools.',
  'Giao việc phù hợp tuổi. Giám sát dụng cụ sắc nhọn.',
  'BQ-LIFE-HELP-DINNER-A10', 'COOKING', 4,
  false, true, true, 1,
  30, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Clean One Shared Family Area', 'Dọn Một Khu Vực Chung',
  'Thoroughly clean one shared area (living room, bathroom, etc.)', 'Dọn dẹp kỹ một khu vực chung (phòng khách, phòng tắm, v.v.)',
  'responsibility', 'LIFE_HOME', 'responsibility', 'assigned_only',
  0, 0, 3, 'SUPPORTED',
  9, 10, 12,
  'Take responsibility for shared family spaces.',
  'Chịu trách nhiệm về không gian chung của gia đình.',
  'Show the standard once, then trust the child to maintain it.',
  'Hướng dẫn tiêu chuẩn một lần, sau đó tin tưởng con duy trì.',
  'BQ-LIFE-CLEAN-SHARED-A10', 'HOUSEHOLD_CARE', 4,
  false, false, false, null,
  20, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Manage My Laundry with Help', 'Quản Lý Giặt Giũ Với Sự Giúp Đỡ',
  'Sort, wash, and fold your own laundry with some parent help', 'Phân loại, giặt và gấp quần áo của con với sự hỗ trợ của bố mẹ',
  'responsibility', 'LIFE_HOME', 'habit_building', 'assigned_only',
  3, 1, 3, 'SUPPORTED',
  9, 10, 12,
  'Build full laundry cycle awareness with support.',
  'Xây dựng nhận thức về toàn bộ chu trình giặt giũ với sự hỗ trợ.',
  'Walk through each step together, then gradually step back.',
  'Cùng làm từng bước, sau đó dần rút lui.',
  'BQ-LIFE-LAUNDRY-HELP-A10', 'HOUSEHOLD_CARE', 4,
  true, false, false, null,
  30, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Pack for a Day Trip', 'Chuẩn Bị Đồ Cho Chuyến Đi Ngày',
  'Pack everything you need for a day trip independently', 'Tự chuẩn bị mọi thứ cần cho chuyến đi trong ngày',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'both',
  5, 1, 3, 'SUPPORTED',
  9, 10, 12,
  'Practice planning and packing for independent outings.',
  'Luyện lập kế hoạch và chuẩn bị đồ cho chuyến đi tự lập.',
  'Give a packing list the first time, then let them plan.',
  'Cho danh sách lần đầu, sau đó để con tự lên kế hoạch.',
  'BQ-WORLD-PACK-TRIP-A10', 'TRAVEL_NAVIGATION', 2,
  true, false, true, 1,
  20, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Manage School Materials', 'Quản Lý Vật Dụng Học Tập',
  'Keep track of school materials and tell parents when supplies are low', 'Theo dõi vật dụng học tập và báo bố mẹ khi sắp hết',
  'responsibility', 'SELF_MANAGEMENT', 'responsibility', 'assigned_only',
  0, 0, 3, 'SUPPORTED',
  9, 10, 12,
  'Take proactive ownership of academic supplies.',
  'Chủ động quản lý đồ dùng học tập.',
  'Trust them to notice and report. Don''t pre-check everything.',
  'Tin tưởng con tự nhận biết và báo. Không kiểm tra trước mọi thứ.',
  'BQ-SELF-SCHOOL-MATERIALS-A10', 'PERSONAL_ORGANIZATION', 4,
  false, false, false, null,
  5, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Make Tomorrow''s Top-3 List', 'Lập Danh Sách 3 Việc Quan Trọng Ngày Mai',
  'Each evening, write down the 3 most important things for tomorrow', 'Mỗi tối, viết 3 việc quan trọng nhất cho ngày mai',
  'learning', 'SELF_MANAGEMENT', 'habit_building', 'both',
  3, 1, 3, 'SUPPORTED',
  9, 10, 12,
  'Build the habit of prioritizing and planning ahead.',
  'Xây dựng thói quen ưu tiên và lập kế hoạch trước.',
  'Review the list together initially. Celebrate completed items.',
  'Xem danh sách cùng nhau lúc đầu. Chúc mừng các mục hoàn thành.',
  'BQ-SELF-TOP3-A10', 'PLANNING', 2,
  true, false, true, 1,
  5, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Read for 30 Minutes', 'Đọc Sách 30 Phút',
  'Read for at least 30 minutes without interruption', 'Đọc sách ít nhất 30 phút không bị gián đoạn',
  'learning', 'LEARNING', 'habit_building', 'both',
  3, 1, 3, 'SUPPORTED',
  9, 10, 12,
  'Build sustained reading and deep focus.',
  'Xây dựng khả năng đọc bền bỉ và tập trung sâu.',
  'Create a quiet reading environment. Model reading behavior.',
  'Tạo môi trường đọc yên tĩnh. Làm gương bằng cách cùng đọc.',
  'BQ-LEARN-READ-30-A10', 'READING', 4,
  true, false, true, 1,
  30, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Screen-Free Study Session', 'Học Không Màn Hình',
  'Study for 30 minutes with all screens put away', 'Học 30 phút với tất cả màn hình được cất đi',
  'learning', 'DIGITAL', 'habit_building', 'both',
  3, 1, 4, 'SUPPORTED',
  9, 10, 12,
  'Practice focused study without digital distraction.',
  'Luyện tập học tập trung mà không bị màn hình làm xao nhãng.',
  'Put your own phone away too. Lead by example.',
  'Cất điện thoại của mình đi luôn. Làm gương.',
  'BQ-DIGITAL-SCREEN-FREE-A10', 'DIGITAL_SAFETY', 1,
  true, false, true, 1,
  30, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Weekly Room Reset', 'Dọn Phòng Hàng Tuần',
  'Do a thorough tidy-up and reset of your room each week', 'Dọn dẹp kỹ và sắp xếp lại phòng mỗi tuần',
  'responsibility', 'LIFE_HOME', 'habit_building', 'both',
  3, 1, 3, 'SUPPORTED',
  9, 10, 12,
  'Maintain personal spaces through regular reset routines.',
  'Duy trì không gian cá nhân qua thói quen dọn dẹp định kỳ.',
  'Create a checklist of room reset tasks together.',
  'Cùng tạo danh sách các việc dọn phòng.',
  'BQ-LIFE-ROOM-RESET-A10', 'HOUSEHOLD_CARE', 4,
  true, false, true, 1,
  30, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Cook One Simple Dish with Parent', 'Nấu Một Món Đơn Giản Cùng Bố Mẹ',
  'Cook a simple dish together with a parent supervising', 'Nấu một món ăn đơn giản với sự giám sát của bố mẹ',
  'responsibility', 'LIFE_HOME', 'challenge', 'choice_pool',
  8, 2, 4, 'SUPPORTED',
  9, 10, 12,
  'Build cooking skills with guided practice.',
  'Xây dựng kỹ năng nấu ăn với sự hướng dẫn.',
  'Let the child lead. Stay nearby for safety with heat and knives.',
  'Để con dẫn dắt. Ở gần để đảm bảo an toàn với lửa và dao.',
  'BQ-LIFE-COOK-SIMPLE-A10', 'COOKING', 4,
  true, true, true, 1,
  45, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Compare 3 Products Before Choosing', 'So Sánh 3 Sản Phẩm Trước Khi Chọn',
  'When shopping, compare 3 options and choose the best value', 'Khi mua sắm, so sánh 3 lựa chọn và chọn giá trị tốt nhất',
  'learning', 'MONEY', 'challenge', 'choice_pool',
  8, 2, 4, 'SUPPORTED',
  9, 10, 12,
  'Practice comparing price and quality before spending.',
  'Luyện so sánh giá và chất lượng trước khi chi tiêu.',
  'Let the child make the decision. Discuss reasoning after.',
  'Để con đưa ra quyết định. Thảo luận lý do sau.',
  'BQ-MONEY-COMPARE-3-A10', 'MONEY', 4,
  true, false, true, 1,
  20, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Give a 3-Minute Presentation', 'Thuyết Trình 3 Phút',
  'Present a topic you chose for 3 minutes to family', 'Thuyết trình một chủ đề con chọn trong 3 phút cho gia đình',
  'learning', 'COMMUNICATION', 'challenge', 'choice_pool',
  8, 2, 4, 'SUPPORTED',
  9, 10, 12,
  'Build structured speaking and presentation skills.',
  'Xây dựng kỹ năng nói có cấu trúc và thuyết trình.',
  'Help them prepare but let them present independently.',
  'Giúp chuẩn bị nhưng để con tự thuyết trình.',
  'BQ-COMM-PRESENT-3-A10', 'COMMUNICATION', 4,
  true, false, true, 1,
  20, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Plan a Family Game Night', 'Lên Kế Hoạch Tối Chơi Game Gia Đình',
  'Choose, prepare, and organize a game night for the family', 'Chọn, chuẩn bị và tổ chức một tối chơi game cho gia đình',
  'family', 'CHARACTER_FAMILY', 'challenge', 'choice_pool',
  8, 2, 4, 'SUPPORTED',
  9, 10, 12,
  'Practice planning, organizing, and family leadership.',
  'Luyện lập kế hoạch, tổ chức và khả năng lãnh đạo gia đình.',
  'Let them plan everything. Participate enthusiastically.',
  'Để con lên kế hoạch mọi thứ. Tham gia nhiệt tình.',
  'BQ-CHAR-GAME-NIGHT-A10', 'FAMILY_CONTRIBUTION', 3,
  true, false, true, 1,
  60, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Complete a Small STEM Experiment', 'Hoàn Thành Một Thí Nghiệm STEM Nhỏ',
  'Do a simple science experiment and explain what happened', 'Làm một thí nghiệm khoa học đơn giản và giải thích kết quả',
  'learning', 'LEARNING', 'challenge', 'choice_pool',
  8, 2, 5, 'SUPPORTED',
  9, 10, 12,
  'Build scientific thinking and hands-on experimentation skills.',
  'Xây dựng tư duy khoa học và kỹ năng thí nghiệm thực hành.',
  'Find age-appropriate experiments online. Supervise as needed.',
  'Tìm thí nghiệm phù hợp tuổi trên mạng. Giám sát khi cần.',
  'BQ-LEARN-STEM-EXP-A10', 'RESEARCH', 2,
  true, true, true, 1,
  45, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Teach Someone Something I Know', 'Dạy Ai Đó Một Điều Con Biết',
  'Choose something you know well and teach it to a family member', 'Chọn một điều con biết rõ và dạy cho một thành viên gia đình',
  'family', 'COMMUNICATION', 'character', 'choice_pool',
  0, 2, 4, 'SUPPORTED',
  9, 10, 12,
  'Deepen understanding through teaching and build empathy.',
  'Hiểu sâu hơn qua việc dạy và xây dựng sự đồng cảm.',
  'Be a willing student. Ask questions to encourage explanation.',
  'Làm học trò nhiệt tình. Đặt câu hỏi để khuyến khích giải thích.',
  'BQ-COMM-TEACH-SKILL-A10', 'COMMUNICATION', 4,
  true, false, true, 1,
  20, 'weekly',
  true, true
)
ON CONFLICT DO NOTHING;

-- =============================================
-- AGE 11 — "I can manage more of my own life" (15 templates)
-- =============================================
INSERT INTO tasks (
  family_id, name, name_vi, description, description_vi,
  category, skill_domain, behavior_type, availability_type,
  coin_reward, star_reward, difficulty, independence_level,
  min_age, recommended_age, max_age,
  development_goal, development_goal_vi, parent_tip, parent_tip_vi,
  template_key, skill_ladder_key, skill_ladder_level,
  requires_approval, requires_supervision, in_pool, pool_max_per_day,
  estimated_minutes, recommended_frequency,
  is_system_template, active
) VALUES
(
  '00000000-0000-0000-0000-000000000000',
  'Change My Bedsheets', 'Thay Ga Giường',
  'Change and replace your bedsheets weekly', 'Thay ga giường hàng tuần',
  'responsibility', 'LIFE_HOME', 'responsibility', 'assigned_only',
  0, 0, 3, 'SUPPORTED',
  10, 11, 13,
  'Own complete bedroom maintenance.',
  'Tự chịu trách nhiệm toàn bộ việc dọn phòng ngủ.',
  'Show once, then let them handle it independently.',
  'Hướng dẫn một lần, sau đó để con tự làm.',
  'BQ-LIFE-CHANGE-SHEETS-A11', 'HOUSEHOLD_CARE', 5,
  false, false, false, null,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Do a Full Laundry Cycle with Guidance', 'Giặt Đồ Trọn Bộ Với Hướng Dẫn',
  'Sort, wash, dry, fold and put away your laundry with minimal help', 'Phân loại, giặt, phơi, gấp và cất quần áo với ít sự giúp đỡ',
  'responsibility', 'LIFE_HOME', 'habit_building', 'assigned_only',
  3, 1, 4, 'SUPPORTED',
  10, 11, 13,
  'Build toward full laundry independence.',
  'Xây dựng hướng tới tự lập hoàn toàn về giặt giũ.',
  'Be available for questions but don''t take over.',
  'Sẵn sàng trả lời câu hỏi nhưng không làm thay.',
  'BQ-LIFE-FULL-LAUNDRY-A11', 'HOUSEHOLD_CARE', 5,
  true, false, false, null,
  45, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Clean Part of the Bathroom', 'Dọn Một Phần Phòng Tắm',
  'Clean the sink, mirror, or floor area of the bathroom', 'Dọn bồn rửa, gương hoặc sàn phòng tắm',
  'responsibility', 'LIFE_HOME', 'responsibility', 'assigned_only',
  0, 0, 3, 'SUPPORTED',
  10, 11, 13,
  'Build household cleaning skills and responsibility.',
  'Xây dựng kỹ năng dọn dẹp nhà và trách nhiệm.',
  'Provide appropriate cleaning supplies and show safety.',
  'Cung cấp đồ dọn phù hợp và hướng dẫn an toàn.',
  'BQ-LIFE-CLEAN-BATH-A11', 'HOUSEHOLD_CARE', 5,
  false, false, false, null,
  20, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Help Clean the Kitchen', 'Giúp Dọn Bếp',
  'Help clean the kitchen after meals (dishes, counters, floor)', 'Giúp dọn bếp sau bữa ăn (rửa bát, lau bàn, quét sàn)',
  'responsibility', 'LIFE_HOME', 'responsibility', 'both',
  0, 0, 3, 'SUPPORTED',
  10, 11, 13,
  'Contribute to family kitchen maintenance.',
  'Góp phần duy trì bếp gia đình.',
  'Rotate kitchen duties among family members.',
  'Luân phiên công việc bếp giữa các thành viên.',
  'BQ-LIFE-CLEAN-KITCHEN-A11', 'HOUSEHOLD_CARE', 5,
  false, false, true, 1,
  20, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Cook a Simple Meal with Supervision', 'Nấu Một Bữa Ăn Đơn Giản Có Giám Sát',
  'Cook a simple complete meal with a parent nearby for safety', 'Nấu một bữa ăn hoàn chỉnh đơn giản với bố mẹ ở gần để an toàn',
  'responsibility', 'LIFE_HOME', 'challenge', 'both',
  8, 2, 5, 'SUPPORTED',
  10, 11, 13,
  'Progress on the cooking ladder toward independent meals.',
  'Tiến bộ trên bậc thang nấu ăn hướng tới bữa ăn tự lập.',
  'Let them choose the recipe. Stay nearby for safety only.',
  'Để con chọn công thức. Chỉ ở gần để đảm bảo an toàn.',
  'BQ-LIFE-COOK-MEAL-A11', 'COOKING', 5,
  true, true, true, 1,
  45, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Manage Homework Without Reminders', 'Tự Quản Lý Bài Tập Không Cần Nhắc',
  'Complete all homework on time without parent reminders', 'Hoàn thành tất cả bài tập đúng hạn mà không cần bố mẹ nhắc',
  'responsibility', 'SELF_MANAGEMENT', 'habit_building', 'assigned_only',
  3, 1, 4, 'SUPPORTED',
  10, 11, 13,
  'Build internal responsibility for academic work.',
  'Xây dựng trách nhiệm nội tại đối với việc học.',
  'Trust but verify gently. Celebrate consistency.',
  'Tin tưởng nhưng kiểm tra nhẹ nhàng. Khen sự đều đặn.',
  'BQ-SELF-HW-INDEPENDENT-A11', 'PLANNING', 3,
  true, false, false, null,
  5, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Plan My Week', 'Lập Kế Hoạch Tuần',
  'Write a simple plan for the week ahead (school, activities, study)', 'Viết kế hoạch đơn giản cho tuần tới (trường, hoạt động, học)',
  'learning', 'SELF_MANAGEMENT', 'habit_building', 'both',
  3, 1, 4, 'SUPPORTED',
  10, 11, 13,
  'Build weekly planning habits for better time management.',
  'Xây dựng thói quen lập kế hoạch tuần để quản lý thời gian tốt hơn.',
  'Review the plan together on Sunday. Let them make it.',
  'Xem kế hoạch cùng nhau vào Chủ Nhật. Để con tự lập.',
  'BQ-SELF-PLAN-WEEK-A11', 'PLANNING', 3,
  true, false, true, 1,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Track School Deadlines', 'Theo Dõi Hạn Nộp Bài',
  'Keep track of all school deadlines in a planner or calendar', 'Theo dõi tất cả hạn nộp bài trong sổ hoặc lịch',
  'responsibility', 'SELF_MANAGEMENT', 'habit_building', 'assigned_only',
  3, 1, 4, 'SUPPORTED',
  10, 11, 13,
  'Develop proactive deadline management skills.',
  'Phát triển kỹ năng quản lý hạn chót chủ động.',
  'Help set up a system (paper or digital). Check in weekly.',
  'Giúp thiết lập hệ thống (giấy hoặc số). Kiểm tra hàng tuần.',
  'BQ-SELF-TRACK-DEADLINES-A11', 'PLANNING', 3,
  true, false, false, null,
  10, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Find Two Sources About One Topic', 'Tìm Hai Nguồn Về Một Chủ Đề',
  'Research a topic and find at least two different sources', 'Tìm hiểu một chủ đề và tìm ít nhất hai nguồn khác nhau',
  'learning', 'LEARNING', 'challenge', 'choice_pool',
  8, 2, 5, 'SUPPORTED',
  10, 11, 13,
  'Build research skills with multiple sources.',
  'Xây dựng kỹ năng nghiên cứu với nhiều nguồn.',
  'Discuss why different sources matter. Guide source evaluation.',
  'Thảo luận tại sao nhiều nguồn quan trọng. Hướng dẫn đánh giá nguồn.',
  'BQ-LEARN-TWO-SOURCES-A11', 'RESEARCH', 2,
  true, false, true, 1,
  30, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Explain Why Two Sources Agree or Disagree', 'Giải Thích Tại Sao Hai Nguồn Đồng Ý Hay Khác Nhau',
  'Compare two sources on a topic and explain their agreement or differences', 'So sánh hai nguồn về một chủ đề và giải thích sự đồng ý hoặc khác biệt',
  'learning', 'LEARNING', 'challenge', 'choice_pool',
  8, 2, 5, 'SUPPORTED',
  10, 11, 13,
  'Develop critical thinking and source comparison skills.',
  'Phát triển tư duy phản biện và kỹ năng so sánh nguồn.',
  'Ask guiding questions. Don''t give the answer directly.',
  'Đặt câu hỏi dẫn dắt. Không cho câu trả lời trực tiếp.',
  'BQ-LEARN-COMPARE-SOURCES-A11', 'RESEARCH', 3,
  true, false, true, 1,
  30, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Fact-Check an Online Claim', 'Kiểm Tra Một Thông Tin Trên Mạng',
  'Find an online claim and verify if it''s true using trusted sources', 'Tìm một thông tin trên mạng và xác minh bằng nguồn đáng tin cậy',
  'learning', 'DIGITAL', 'challenge', 'choice_pool',
  8, 2, 5, 'SUPPORTED',
  10, 11, 13,
  'Build digital literacy and critical thinking about online information.',
  'Xây dựng khả năng đọc hiểu kỹ thuật số và tư duy phản biện về thông tin trực tuyến.',
  'Do this together at first. Discuss what makes a source trustworthy.',
  'Làm cùng nhau lúc đầu. Thảo luận điều gì khiến nguồn đáng tin cậy.',
  'BQ-DIGITAL-FACT-CHECK-A11', 'DIGITAL_SAFETY', 2,
  true, false, true, 1,
  20, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Explain a Hard Idea to a Younger Child', 'Giải Thích Một Ý Khó Cho Em Nhỏ',
  'Take something complex and explain it simply to a younger child', 'Lấy một điều phức tạp và giải thích đơn giản cho em nhỏ hơn',
  'family', 'COMMUNICATION', 'character', 'choice_pool',
  0, 2, 4, 'SUPPORTED',
  10, 11, 13,
  'Deepen understanding through teaching and develop patience.',
  'Hiểu sâu hơn qua việc dạy và phát triển tính kiên nhẫn.',
  'Praise the effort to explain, not just the accuracy.',
  'Khen ngợi nỗ lực giải thích, không chỉ sự chính xác.',
  'BQ-COMM-EXPLAIN-YOUNGER-A11', 'COMMUNICATION', 5,
  true, false, true, 1,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Plan a Small Purchase Budget', 'Lập Ngân Sách Mua Sắm Nhỏ',
  'Plan what to buy within a set budget (e.g., 200,000đ for school supplies)', 'Lập kế hoạch mua sắm trong ngân sách (vd: 200.000đ cho đồ dùng học tập)',
  'learning', 'MONEY', 'challenge', 'choice_pool',
  8, 2, 5, 'SUPPORTED',
  10, 11, 13,
  'Practice real-world budgeting with a defined limit.',
  'Luyện lập ngân sách thực tế với giới hạn cụ thể.',
  'Give real money and let them make real decisions.',
  'Cho tiền thật và để con đưa ra quyết định thật.',
  'BQ-MONEY-PURCHASE-BUDGET-A11', 'MONEY', 5,
  true, false, true, 1,
  30, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Keep a Spending Log for One Week', 'Ghi Chép Chi Tiêu Một Tuần',
  'Track everything you spend money on for one whole week', 'Ghi lại tất cả chi tiêu trong một tuần',
  'learning', 'MONEY', 'habit_building', 'both',
  3, 1, 4, 'SUPPORTED',
  10, 11, 13,
  'Build awareness of spending patterns through tracking.',
  'Xây dựng nhận thức về thói quen chi tiêu qua việc ghi chép.',
  'Provide a simple log template. Review together at week end.',
  'Cung cấp mẫu ghi chép đơn giản. Xem cùng nhau cuối tuần.',
  'BQ-MONEY-SPENDING-LOG-A11', 'MONEY', 5,
  true, false, true, 1,
  5, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Help a Younger Sibling While an Adult Is Home', 'Giúp Em Nhỏ Khi Có Người Lớn Ở Nhà',
  'Watch over and help a younger sibling with an activity while a parent is nearby', 'Trông và giúp em nhỏ hơn một hoạt động khi bố mẹ ở gần',
  'family', 'CHARACTER_FAMILY', 'character', 'both',
  0, 2, 4, 'SUPPORTED',
  10, 11, 13,
  'Build care responsibility and mentoring skills.',
  'Xây dựng trách nhiệm chăm sóc và kỹ năng hướng dẫn.',
  'Stay nearby but let them lead. Praise patience and care.',
  'Ở gần nhưng để con dẫn dắt. Khen tính kiên nhẫn và sự chăm sóc.',
  'BQ-CHAR-HELP-SIBLING-A11', 'FAMILY_CONTRIBUTION', 4,
  true, true, true, 1,
  30, 'weekly',
  true, true
)
ON CONFLICT DO NOTHING;

-- =============================================
-- AGE 12 — "I can set goals" (15 templates)
-- =============================================
INSERT INTO tasks (
  family_id, name, name_vi, description, description_vi,
  category, skill_domain, behavior_type, availability_type,
  coin_reward, star_reward, difficulty, independence_level,
  min_age, recommended_age, max_age,
  development_goal, development_goal_vi, parent_tip, parent_tip_vi,
  template_key, skill_ladder_key, skill_ladder_level,
  requires_approval, requires_supervision, in_pool, pool_max_per_day,
  estimated_minutes, recommended_frequency,
  is_system_template, active
) VALUES
(
  '00000000-0000-0000-0000-000000000000',
  'Manage School Preparation Independently', 'Tự Quản Lý Chuẩn Bị Đi Học',
  'Handle all school preparation without any parent reminders', 'Tự chuẩn bị mọi thứ đi học mà không cần bố mẹ nhắc',
  'responsibility', 'SELF_MANAGEMENT', 'responsibility', 'assigned_only',
  0, 0, 4, 'INDEPENDENT',
  11, 12, 14,
  'Full ownership of school preparation routine.',
  'Tự chịu trách nhiệm hoàn toàn về việc chuẩn bị đi học.',
  'Trust completely. Only intervene if pattern of forgetting emerges.',
  'Tin tưởng hoàn toàn. Chỉ can thiệp nếu xuất hiện xu hướng hay quên.',
  'BQ-SELF-SCHOOL-PREP-A12', 'PERSONAL_ORGANIZATION', 5,
  false, false, false, null,
  10, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Do Personal Laundry', 'Tự Giặt Đồ Cá Nhân',
  'Complete your personal laundry cycle from start to finish', 'Hoàn thành chu trình giặt đồ cá nhân từ đầu đến cuối',
  'responsibility', 'LIFE_HOME', 'responsibility', 'assigned_only',
  0, 0, 4, 'SUPPORTED',
  11, 12, 14,
  'Full laundry cycle ownership building toward independence.',
  'Tự chủ toàn bộ chu trình giặt giũ hướng tới tự lập.',
  'Offer help if asked but don''t volunteer it.',
  'Giúp nếu con hỏi nhưng không chủ động đề nghị.',
  'BQ-LIFE-PERSONAL-LAUNDRY-A12', 'HOUSEHOLD_CARE', 6,
  false, false, false, null,
  45, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Clean My Room Fully', 'Dọn Phòng Sạch Sẽ',
  'Do a complete room cleaning including dusting, vacuuming, and organizing', 'Dọn phòng hoàn chỉnh gồm lau bụi, hút bụi và sắp xếp',
  'responsibility', 'LIFE_HOME', 'responsibility', 'assigned_only',
  0, 0, 4, 'INDEPENDENT',
  11, 12, 14,
  'Own complete room maintenance independently.',
  'Tự chịu trách nhiệm hoàn toàn về việc dọn phòng.',
  'Set a standard together, then let them maintain it.',
  'Cùng đặt tiêu chuẩn, sau đó để con tự duy trì.',
  'BQ-LIFE-CLEAN-ROOM-A12', 'HOUSEHOLD_CARE', 6,
  false, false, false, null,
  30, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Cook a Basic Meal with Supervision', 'Nấu Bữa Ăn Cơ Bản Có Giám Sát',
  'Cook a complete basic meal independently with parent nearby', 'Tự nấu một bữa ăn cơ bản hoàn chỉnh với bố mẹ ở gần',
  'responsibility', 'LIFE_HOME', 'challenge', 'both',
  8, 2, 5, 'SUPPORTED',
  11, 12, 14,
  'Build toward cooking meals independently.',
  'Xây dựng hướng tới nấu bữa ăn tự lập.',
  'Let them choose the menu and shop for ingredients.',
  'Để con chọn thực đơn và mua nguyên liệu.',
  'BQ-LIFE-COOK-BASIC-A12', 'COOKING', 5,
  true, true, true, 1,
  60, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Maintain One Shared Family Space', 'Duy Trì Một Không Gian Chung Gia Đình',
  'Take full responsibility for keeping one shared space clean weekly', 'Chịu trách nhiệm hoàn toàn giữ sạch một không gian chung hàng tuần',
  'family', 'CHARACTER_FAMILY', 'responsibility', 'assigned_only',
  0, 0, 4, 'INDEPENDENT',
  11, 12, 14,
  'Build ownership of shared family spaces.',
  'Xây dựng ý thức sở hữu với không gian chung gia đình.',
  'Let them set their own schedule. Check quality weekly.',
  'Để con tự đặt lịch. Kiểm tra chất lượng hàng tuần.',
  'BQ-CHAR-SHARED-SPACE-A12', 'FAMILY_CONTRIBUTION', 4,
  false, false, false, null,
  20, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Weekly Planning', 'Lập Kế Hoạch Tuần',
  'Create a complete plan for the week including priorities and deadlines', 'Lập kế hoạch hoàn chỉnh cho tuần gồm ưu tiên và hạn chót',
  'learning', 'SELF_MANAGEMENT', 'habit_building', 'both',
  3, 1, 4, 'INDEPENDENT',
  11, 12, 14,
  'Build independent weekly planning habits.',
  'Xây dựng thói quen lập kế hoạch tuần tự lập.',
  'Review together at first, then let them own it.',
  'Xem cùng nhau lúc đầu, sau đó để con tự chủ.',
  'BQ-SELF-WEEKLY-PLAN-A12', 'PLANNING', 4,
  true, false, true, 1,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Weekly Reflection', 'Nhìn Lại Tuần',
  'Spend 10 minutes reflecting on what went well and what to improve', 'Dành 10 phút nhìn lại điều tốt và điều cần cải thiện',
  'learning', 'SELF_MANAGEMENT', 'habit_building', 'both',
  3, 1, 4, 'INDEPENDENT',
  11, 12, 14,
  'Build self-awareness through regular reflection.',
  'Xây dựng tự nhận thức qua việc nhìn lại thường xuyên.',
  'Share your own reflections too. Make it a dialogue.',
  'Chia sẻ suy nghĩ của mình luôn. Biến thành cuộc trò chuyện.',
  'BQ-SELF-WEEKLY-REFLECT-A12', 'PLANNING', 4,
  true, false, true, 1,
  10, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  '45-Minute Focus Session', 'Tập Trung 45 Phút',
  'Work on a task with deep focus for 45 minutes', 'Làm việc tập trung sâu trong 45 phút',
  'learning', 'SELF_MANAGEMENT', 'habit_building', 'choice_pool',
  3, 1, 4, 'INDEPENDENT',
  11, 12, 14,
  'Extend sustained attention and deep work capabilities.',
  'Mở rộng khả năng chú ý bền bỉ và làm việc sâu.',
  'Provide a distraction-free environment. Respect their focus time.',
  'Tạo môi trường không bị xao nhãng. Tôn trọng thời gian tập trung.',
  'BQ-SELF-FOCUS-45-A12', 'PLANNING', 4,
  true, false, true, 1,
  45, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Track a Savings Goal', 'Theo Dõi Mục Tiêu Tiết Kiệm',
  'Set a savings goal, track progress, and adjust as needed', 'Đặt mục tiêu tiết kiệm, theo dõi tiến độ và điều chỉnh khi cần',
  'learning', 'MONEY', 'habit_building', 'both',
  3, 1, 4, 'INDEPENDENT',
  11, 12, 14,
  'Build financial goal-setting and tracking habits.',
  'Xây dựng thói quen đặt mục tiêu tài chính và theo dõi.',
  'Help set a realistic goal. Celebrate milestones along the way.',
  'Giúp đặt mục tiêu thực tế. Chúc mừng các mốc trên hành trình.',
  'BQ-MONEY-SAVINGS-GOAL-A12', 'MONEY', 6,
  true, false, true, 1,
  10, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Learn a Skill for 7 Days', 'Học Một Kỹ Năng Trong 7 Ngày',
  'Pick a new skill and practice it every day for a week', 'Chọn một kỹ năng mới và luyện tập mỗi ngày trong một tuần',
  'learning', 'LEARNING', 'challenge', 'choice_pool',
  12, 4, 6, 'INDEPENDENT',
  11, 12, 14,
  'Practice deliberate skill-building over sustained effort.',
  'Luyện tập xây dựng kỹ năng có chủ đích qua nỗ lực bền bỉ.',
  'Help choose an achievable skill. Check in daily on progress.',
  'Giúp chọn kỹ năng khả thi. Theo dõi tiến độ hàng ngày.',
  'BQ-LEARN-7DAY-SKILL-A12', null, null,
  true, false, true, 1,
  30, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Build a Mini STEM Project', 'Xây Dựng Một Dự Án STEM Nhỏ',
  'Design and build a small STEM project (robot, circuit, code, etc.)', 'Thiết kế và xây dựng một dự án STEM nhỏ (robot, mạch, code, v.v.)',
  'learning', 'LEARNING', 'challenge', 'choice_pool',
  12, 4, 6, 'SUPPORTED',
  11, 12, 14,
  'Apply STEM knowledge in a hands-on creative project.',
  'Áp dụng kiến thức STEM trong dự án sáng tạo thực hành.',
  'Provide materials and space. Help troubleshoot if they''re stuck.',
  'Cung cấp vật liệu và không gian. Giúp gỡ rối nếu con bí.',
  'BQ-LEARN-STEM-PROJECT-A12', 'PROJECT_EXECUTION', 1,
  true, false, true, 1,
  60, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Read a Nonfiction Book', 'Đọc Một Cuốn Sách Phi Hư Cấu',
  'Read a nonfiction book about a topic you''re interested in', 'Đọc một cuốn sách phi hư cấu về chủ đề con quan tâm',
  'learning', 'LEARNING', 'challenge', 'choice_pool',
  8, 2, 5, 'INDEPENDENT',
  11, 12, 14,
  'Expand reading beyond fiction to informational texts.',
  'Mở rộng đọc sách ngoài tiểu thuyết sang sách thông tin.',
  'Help find age-appropriate nonfiction. Discuss what they learned.',
  'Giúp tìm sách phi hư cấu phù hợp tuổi. Thảo luận điều con học.',
  'BQ-LEARN-READ-NONFICTION-A12', 'READING', 5,
  true, false, true, 1,
  60, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Recognize Phishing or Scam Examples', 'Nhận Biết Ví Dụ Lừa Đảo',
  'Study examples of phishing emails or scam messages and explain the warning signs', 'Nghiên cứu ví dụ email lừa đảo và giải thích dấu hiệu cảnh báo',
  'learning', 'DIGITAL', 'challenge', 'choice_pool',
  8, 2, 5, 'SUPPORTED',
  11, 12, 14,
  'Build practical digital safety awareness.',
  'Xây dựng nhận thức an toàn kỹ thuật số thực tế.',
  'Show real (redacted) examples. Make it a detective game.',
  'Cho xem ví dụ thật (đã che). Biến thành trò chơi trinh thám.',
  'BQ-DIGITAL-PHISHING-A12', 'DIGITAL_SAFETY', 3,
  true, false, true, 1,
  20, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Compare an AI Answer with a Trusted Source', 'So Sánh Câu Trả Lời AI Với Nguồn Đáng Tin',
  'Ask an AI a question, then verify the answer with a trusted source', 'Hỏi AI một câu hỏi, sau đó kiểm tra câu trả lời với nguồn đáng tin cậy',
  'learning', 'DIGITAL', 'challenge', 'choice_pool',
  8, 2, 5, 'SUPPORTED',
  11, 12, 14,
  'Build AI literacy and critical verification habits.',
  'Xây dựng hiểu biết về AI và thói quen kiểm chứng phản biện.',
  'Do this together. Discuss why AI can be wrong.',
  'Làm cùng nhau. Thảo luận tại sao AI có thể sai.',
  'BQ-DIGITAL-AI-VERIFY-A12', 'AI_LITERACY', 1,
  true, false, true, 1,
  20, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Create Something Useful for the Family', 'Tạo Một Thứ Hữu Ích Cho Gia Đình',
  'Make or build something that helps the family (organizer, recipe card, etc.)', 'Làm hoặc tạo một thứ giúp ích cho gia đình (hộp sắp xếp, thẻ công thức, v.v.)',
  'family', 'CHARACTER_FAMILY', 'challenge', 'choice_pool',
  8, 2, 5, 'SUPPORTED',
  11, 12, 14,
  'Apply creativity and skills to contribute to family life.',
  'Áp dụng sáng tạo và kỹ năng để đóng góp cho cuộc sống gia đình.',
  'Let them identify the need. Provide materials and encouragement.',
  'Để con tự nhận ra nhu cầu. Cung cấp vật liệu và khích lệ.',
  'BQ-CHAR-CREATE-USEFUL-A12', 'FAMILY_CONTRIBUTION', 5,
  true, false, true, 1,
  60, 'once',
  true, true
)
ON CONFLICT DO NOTHING;
