-- 0028_seed_curriculum_teens.sql — Seed System Quest templates (Ages 13-18, ~90 templates)
-- Source: docs/BloomQuest_System_Quest_Curriculum_Implementation_Plan.md §25

-- =============================================
-- AGE 13 — "I manage myself, not just my tasks" (15 templates)
-- =============================================
INSERT INTO tasks (
  family_id, name, name_vi, description, description_vi,
  category, skill_domain, behavior_type, availability_type,
  coin_reward, star_reward, difficulty, independence_level,
  min_age, recommended_age, max_age,
  development_goal, development_goal_vi, parent_tip, parent_tip_vi,
  template_key, skill_ladder_key, skill_ladder_level,
  requires_approval, requires_supervision, in_pool, pool_max_per_day,
  estimated_minutes, recommended_frequency,
  is_system_template, active
) VALUES
(
  '00000000-0000-0000-0000-000000000000',
  'Complete Personal Laundry Independently', 'Tự Giặt Đồ Hoàn Toàn',
  'Handle your entire laundry cycle without any help', 'Tự xử lý toàn bộ chu trình giặt giũ mà không cần giúp đỡ',
  'responsibility', 'LIFE_HOME', 'responsibility', 'assigned_only',
  0, 0, 4, 'INDEPENDENT',
  12, 13, 15,
  'Full independence in personal laundry management.',
  'Tự lập hoàn toàn trong quản lý giặt giũ cá nhân.',
  'This should be routine by now. Only comment if something goes wrong.',
  'Đây nên là thói quen rồi. Chỉ nhận xét khi có vấn đề.',
  'BQ-LIFE-LAUNDRY-INDEPENDENT-A13', 'HOUSEHOLD_CARE', 7,
  false, false, false, null,
  45, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Cook a Basic Meal', 'Nấu Bữa Ăn Cơ Bản',
  'Plan and cook a complete basic meal independently', 'Tự lên kế hoạch và nấu một bữa ăn cơ bản hoàn chỉnh',
  'responsibility', 'LIFE_HOME', 'responsibility', 'both',
  0, 0, 5, 'INDEPENDENT',
  12, 13, 15,
  'Cooking as a normal life skill, not a special challenge.',
  'Nấu ăn như kỹ năng sống bình thường, không phải thử thách đặc biệt.',
  'Transition from challenge to normal expectation.',
  'Chuyển từ thử thách sang kỳ vọng bình thường.',
  'BQ-LIFE-COOK-BASIC-MEAL-A13', 'COOKING', 6,
  false, false, true, 1,
  60, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Own One Weekly Family Chore', 'Phụ Trách Một Việc Nhà Hàng Tuần',
  'Take full ownership of one recurring family chore', 'Tự chịu trách nhiệm hoàn toàn một việc nhà lặp lại hàng tuần',
  'family', 'CHARACTER_FAMILY', 'responsibility', 'assigned_only',
  0, 0, 4, 'INDEPENDENT',
  12, 13, 15,
  'Build ownership of family household contribution.',
  'Xây dựng ý thức sở hữu trong đóng góp cho gia đình.',
  'Let them choose their chore. Trust them to do it.',
  'Để con chọn việc. Tin tưởng con sẽ làm.',
  'BQ-CHAR-WEEKLY-CHORE-A13', 'FAMILY_CONTRIBUTION', 5,
  false, false, false, null,
  30, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Manage My Allowance', 'Quản Lý Tiền Tiêu Vặt',
  'Manage your weekly/monthly allowance responsibly', 'Quản lý tiền tiêu vặt hàng tuần/tháng một cách có trách nhiệm',
  'responsibility', 'MONEY', 'responsibility', 'both',
  0, 0, 5, 'INDEPENDENT',
  12, 13, 15,
  'Practice real money management with personal funds.',
  'Luyện quản lý tiền thật với tiền cá nhân.',
  'Give a set amount and let them learn from choices.',
  'Cho một số tiền nhất định và để con học từ lựa chọn.',
  'BQ-MONEY-ALLOWANCE-A13', 'MONEY', 7,
  false, false, true, 1,
  10, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Maintain My Study Area', 'Duy Trì Khu Vực Học Tập',
  'Keep your study area organized, clean, and well-supplied', 'Giữ khu vực học tập ngăn nắp, sạch sẽ và đầy đủ',
  'responsibility', 'SELF_MANAGEMENT', 'responsibility', 'assigned_only',
  0, 0, 4, 'INDEPENDENT',
  12, 13, 15,
  'Own your learning environment completely.',
  'Hoàn toàn tự chủ môi trường học tập.',
  'This should be assumed, not reminded.',
  'Đây nên là điều đương nhiên, không cần nhắc.',
  'BQ-SELF-STUDY-AREA-A13', 'PERSONAL_ORGANIZATION', 6,
  false, false, false, null,
  10, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Choose My Top 3 Priorities', 'Chọn 3 Ưu Tiên Hàng Đầu',
  'Each day, identify and focus on your 3 most important priorities', 'Mỗi ngày, xác định và tập trung vào 3 ưu tiên quan trọng nhất',
  'learning', 'SELF_MANAGEMENT', 'habit_building', 'both',
  3, 1, 5, 'INDEPENDENT',
  12, 13, 15,
  'Build daily prioritization as an internalized habit.',
  'Xây dựng ưu tiên hóa hàng ngày thành thói quen bên trong.',
  'Ask about priorities, don''t set them.',
  'Hỏi về ưu tiên, không đặt chúng.',
  'BQ-SELF-PRIORITIES-A13', 'PLANNING', 5,
  true, false, true, 1,
  5, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Weekly Review', 'Nhìn Lại Tuần',
  'Review your week: what you accomplished, what to improve, and plan next week', 'Nhìn lại tuần: những gì đã làm, cần cải thiện, và lên kế hoạch tuần tới',
  'learning', 'SELF_MANAGEMENT', 'habit_building', 'both',
  3, 1, 5, 'INDEPENDENT',
  12, 13, 15,
  'Build structured self-reflection and planning habits.',
  'Xây dựng thói quen tự phản ánh và lập kế hoạch có cấu trúc.',
  'Have a brief weekly check-in. Keep it conversational.',
  'Có buổi trao đổi ngắn hàng tuần. Giữ thoải mái như trò chuyện.',
  'BQ-SELF-WEEKLY-REVIEW-A13', 'PLANNING', 5,
  true, false, true, 1,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Regular Physical Activity', 'Vận Động Thường Xuyên',
  'Do at least 30 minutes of physical activity', 'Vận động ít nhất 30 phút',
  'health', 'HEALTH', 'habit_building', 'both',
  3, 1, 3, 'INDEPENDENT',
  12, 13, 16,
  'Build sustainable exercise habits.',
  'Xây dựng thói quen tập thể dục bền vững.',
  'Let them choose the activity. Support, don''t push.',
  'Để con chọn hoạt động. Ủng hộ, không ép.',
  'BQ-HEALTH-EXERCISE-A13', null, null,
  true, false, true, 1,
  30, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Notice and Manage Emotional Triggers', 'Nhận Biết và Quản Lý Cảm Xúc',
  'Practice recognizing when you feel stressed or upset and use calming strategies', 'Luyện nhận biết khi cảm thấy căng thẳng hoặc buồn bực và dùng chiến lược bình tĩnh',
  'health', 'HEALTH', 'habit_building', 'both',
  3, 1, 5, 'SUPPORTED',
  12, 13, 15,
  'Build emotional self-awareness and regulation.',
  'Xây dựng tự nhận thức và điều chỉnh cảm xúc.',
  'Share your own strategies. Normalize emotions.',
  'Chia sẻ chiến lược của mình. Bình thường hóa cảm xúc.',
  'BQ-HEALTH-EMOTIONS-A13', null, null,
  true, false, true, 1,
  10, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Plan a Meal Within a Budget', 'Lên Kế Hoạch Bữa Ăn Trong Ngân Sách',
  'Plan a meal for the family within a given budget', 'Lên kế hoạch bữa ăn cho gia đình trong ngân sách cho trước',
  'learning', 'MONEY', 'challenge', 'choice_pool',
  10, 3, 6, 'SUPPORTED',
  12, 13, 15,
  'Combine cooking planning with budget management.',
  'Kết hợp lên kế hoạch nấu ăn với quản lý ngân sách.',
  'Give a real budget. Let them shop and cook.',
  'Cho ngân sách thật. Để con mua sắm và nấu.',
  'BQ-MONEY-MEAL-BUDGET-A13', 'MONEY', 7,
  true, false, true, 1,
  60, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Travel a Familiar Route Independently', 'Tự Đi Một Tuyến Đường Quen',
  'Travel a familiar route (school, relative''s home) with increasing independence', 'Tự đi một tuyến đường quen (trường, nhà họ hàng) với tính tự lập tăng dần',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  8, 2, 5, 'SUPPORTED',
  12, 13, 15,
  'Build real-world navigation and travel independence.',
  'Xây dựng khả năng tự di chuyển và tìm đường trong thực tế.',
  'Start with safe familiar routes. Build up gradually.',
  'Bắt đầu với tuyến đường quen an toàn. Tăng dần.',
  'BQ-WORLD-TRAVEL-ROUTE-A13', 'TRAVEL_NAVIGATION', 3,
  true, true, true, 1,
  30, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Give a 5-Minute Presentation', 'Thuyết Trình 5 Phút',
  'Present a researched topic for 5 minutes', 'Thuyết trình một chủ đề đã nghiên cứu trong 5 phút',
  'learning', 'COMMUNICATION', 'challenge', 'choice_pool',
  10, 3, 5, 'INDEPENDENT',
  12, 13, 15,
  'Build confident public speaking and argumentation.',
  'Xây dựng khả năng thuyết trình và lập luận tự tin.',
  'Give constructive feedback. Focus on clarity and structure.',
  'Cho phản hồi xây dựng. Tập trung vào sự rõ ràng và cấu trúc.',
  'BQ-COMM-PRESENT-5-A13', 'COMMUNICATION', 6,
  true, false, true, 1,
  30, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Complete a 7-Day Personal Project', 'Hoàn Thành Dự Án Cá Nhân 7 Ngày',
  'Define, plan and complete a personal project over one week', 'Xác định, lập kế hoạch và hoàn thành dự án cá nhân trong một tuần',
  'learning', 'SELF_MANAGEMENT', 'challenge', 'choice_pool',
  15, 5, 7, 'INDEPENDENT',
  12, 13, 15,
  'Build project management skills through sustained effort.',
  'Xây dựng kỹ năng quản lý dự án qua nỗ lực bền bỉ.',
  'Help define scope. Check in daily but don''t micromanage.',
  'Giúp xác định phạm vi. Kiểm tra hàng ngày nhưng không quản lý vi mô.',
  'BQ-SELF-7DAY-PROJECT-A13', 'PROJECT_EXECUTION', 2,
  true, false, true, 1,
  60, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Interview an Adult About Their Profession', 'Phỏng Vấn Người Lớn Về Nghề Nghiệp',
  'Interview someone about their career path and what they learned', 'Phỏng vấn ai đó về con đường sự nghiệp và điều họ học được',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  10, 3, 5, 'INDEPENDENT',
  12, 13, 15,
  'Explore career possibilities and build interview skills.',
  'Khám phá các khả năng nghề nghiệp và xây dựng kỹ năng phỏng vấn.',
  'Help arrange the interview if needed. Let the child lead.',
  'Giúp sắp xếp buổi phỏng vấn nếu cần. Để con dẫn dắt.',
  'BQ-WORLD-CAREER-INTERVIEW-A13', 'CAREER_EXPLORATION', 1,
  true, false, true, 1,
  45, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Help in a Community or Family Service Activity', 'Giúp Đỡ Hoạt Động Cộng Đồng hoặc Gia Đình',
  'Participate in a community service or family helping activity', 'Tham gia hoạt động phục vụ cộng đồng hoặc giúp đỡ gia đình',
  'family', 'CHARACTER_FAMILY', 'character', 'choice_pool',
  0, 3, 5, 'SUPPORTED',
  12, 13, 15,
  'Experience contributing to the broader community.',
  'Trải nghiệm đóng góp cho cộng đồng rộng lớn hơn.',
  'Find age-appropriate opportunities. Reflect together afterwards.',
  'Tìm cơ hội phù hợp tuổi. Cùng nhìn lại sau đó.',
  'BQ-CHAR-COMMUNITY-SERVICE-A13', 'FAMILY_CONTRIBUTION', 6,
  true, false, true, 1,
  60, 'once',
  true, true
)
ON CONFLICT DO NOTHING;

-- =============================================
-- AGE 14 — "I can make informed decisions" (15 templates)
-- =============================================
INSERT INTO tasks (
  family_id, name, name_vi, description, description_vi,
  category, skill_domain, behavior_type, availability_type,
  coin_reward, star_reward, difficulty, independence_level,
  min_age, recommended_age, max_age,
  development_goal, development_goal_vi, parent_tip, parent_tip_vi,
  template_key, skill_ladder_key, skill_ladder_level,
  requires_approval, requires_supervision, in_pool, pool_max_per_day,
  estimated_minutes, recommended_frequency,
  is_system_template, active
) VALUES
(
  '00000000-0000-0000-0000-000000000000',
  'Manage My Study Schedule', 'Quản Lý Lịch Học',
  'Plan and follow your study schedule independently', 'Tự lên kế hoạch và theo lịch học',
  'responsibility', 'SELF_MANAGEMENT', 'responsibility', 'assigned_only',
  0, 0, 5, 'INDEPENDENT',
  13, 14, 16,
  'Full ownership of academic time management.',
  'Tự chủ hoàn toàn về quản lý thời gian học tập.',
  'Ask about their schedule, don''t set it for them.',
  'Hỏi về lịch của con, không đặt thay con.',
  'BQ-SELF-STUDY-SCHEDULE-A14', 'PLANNING', 6,
  false, false, false, null,
  10, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Cook 2-3 Basic Dishes', 'Nấu 2-3 Món Ăn Cơ Bản',
  'Regularly cook 2-3 different basic dishes for the family', 'Thường xuyên nấu 2-3 món ăn cơ bản khác nhau cho gia đình',
  'responsibility', 'LIFE_HOME', 'habit_building', 'both',
  3, 1, 5, 'INDEPENDENT',
  13, 14, 16,
  'Expand cooking repertoire as a normal contribution.',
  'Mở rộng danh mục món nấu như đóng góp bình thường.',
  'Encourage trying new recipes. Accept failures gracefully.',
  'Khuyến khích thử công thức mới. Chấp nhận thất bại nhẹ nhàng.',
  'BQ-LIFE-COOK-MULTIPLE-A14', 'COOKING', 7,
  true, false, true, 1,
  60, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Participate in Grocery Planning', 'Tham Gia Lên Kế Hoạch Mua Sắm',
  'Help plan the family grocery list and shopping', 'Giúp lên danh sách và kế hoạch mua sắm cho gia đình',
  'responsibility', 'LIFE_HOME', 'responsibility', 'both',
  0, 0, 5, 'INDEPENDENT',
  13, 14, 16,
  'Understand household food planning and procurement.',
  'Hiểu về lên kế hoạch thực phẩm và mua sắm cho gia đình.',
  'Include them in planning discussions. Give real responsibility.',
  'Cho con tham gia thảo luận lập kế hoạch. Giao trách nhiệm thật.',
  'BQ-LIFE-GROCERY-PLAN-A14', 'COOKING', 7,
  false, false, true, 1,
  30, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Own a Shared Household Chore', 'Phụ Trách Một Việc Nhà Chung',
  'Take full responsibility for one major shared household chore', 'Chịu trách nhiệm hoàn toàn một việc nhà chung quan trọng',
  'family', 'CHARACTER_FAMILY', 'responsibility', 'assigned_only',
  0, 0, 5, 'INDEPENDENT',
  13, 14, 16,
  'Contribute substantially to household operations.',
  'Đóng góp đáng kể vào vận hành gia đình.',
  'Agree on standards. Trust them to maintain.',
  'Thống nhất tiêu chuẩn. Tin tưởng con duy trì.',
  'BQ-CHAR-HOUSEHOLD-CHORE-A14', 'FAMILY_CONTRIBUTION', 6,
  false, false, false, null,
  30, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Manage Personal Spending', 'Quản Lý Chi Tiêu Cá Nhân',
  'Track and manage all personal spending responsibly', 'Theo dõi và quản lý tất cả chi tiêu cá nhân có trách nhiệm',
  'responsibility', 'MONEY', 'responsibility', 'both',
  0, 0, 5, 'INDEPENDENT',
  13, 14, 16,
  'Build real-world financial management habits.',
  'Xây dựng thói quen quản lý tài chính thực tế.',
  'Review together monthly if they want. Don''t micro-monitor.',
  'Xem cùng nhau hàng tháng nếu con muốn. Không theo dõi vi mô.',
  'BQ-MONEY-PERSONAL-SPENDING-A14', 'MONEY', 8,
  false, false, true, 1,
  10, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Weekly Planning Without Parent Doing It', 'Tự Lập Kế Hoạch Tuần',
  'Plan your entire week independently without parent input', 'Tự lập kế hoạch toàn bộ tuần mà không cần bố mẹ đóng góp',
  'learning', 'SELF_MANAGEMENT', 'habit_building', 'both',
  3, 1, 5, 'INDEPENDENT',
  13, 14, 16,
  'Full independence in weekly planning.',
  'Tự lập hoàn toàn trong lập kế hoạch tuần.',
  'Only discuss if they ask. Trust the process.',
  'Chỉ thảo luận khi con hỏi. Tin tưởng quá trình.',
  'BQ-SELF-PLAN-INDEPENDENT-A14', 'PLANNING', 6,
  true, false, true, 1,
  15, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Focus Session with Phone Away', 'Tập Trung Với Điện Thoại Cất Đi',
  'Do a focused work session with phone completely put away', 'Làm một buổi tập trung với điện thoại hoàn toàn cất đi',
  'learning', 'DIGITAL', 'habit_building', 'both',
  3, 1, 5, 'INDEPENDENT',
  13, 14, 16,
  'Build discipline around digital distraction management.',
  'Xây dựng kỷ luật trong quản lý sự xao nhãng kỹ thuật số.',
  'Model the same behavior during their focus time.',
  'Làm gương cùng hành vi trong thời gian tập trung của con.',
  'BQ-DIGITAL-PHONE-AWAY-A14', 'DIGITAL_SAFETY', 3,
  true, false, true, 1,
  45, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Read Long-Form Content', 'Đọc Nội Dung Dài',
  'Read a book, long article, or essay for extended periods', 'Đọc sách, bài viết dài hoặc tiểu luận trong thời gian kéo dài',
  'learning', 'LEARNING', 'habit_building', 'choice_pool',
  3, 1, 5, 'INDEPENDENT',
  13, 14, 16,
  'Build sustained reading and deep thinking.',
  'Xây dựng khả năng đọc bền bỉ và tư duy sâu.',
  'Provide access to quality long-form content.',
  'Cung cấp tiếp cận nội dung dài chất lượng.',
  'BQ-LEARN-LONG-READ-A14', 'READING', 6,
  true, false, true, 1,
  45, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Fact-Check 3 Social-Media Claims', 'Kiểm Tra 3 Thông Tin Trên Mạng Xã Hội',
  'Find 3 claims on social media and verify each one', 'Tìm 3 thông tin trên mạng xã hội và kiểm chứng từng cái',
  'learning', 'DIGITAL', 'challenge', 'choice_pool',
  10, 3, 6, 'INDEPENDENT',
  13, 14, 16,
  'Develop systematic media literacy and verification skills.',
  'Phát triển kỹ năng đọc hiểu truyền thông và kiểm chứng có hệ thống.',
  'Discuss findings together. Appreciate skeptical thinking.',
  'Thảo luận phát hiện cùng nhau. Đánh giá cao tư duy hoài nghi.',
  'BQ-DIGITAL-FACT-CHECK-3-A14', 'DIGITAL_SAFETY', 4,
  true, false, true, 1,
  30, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Compare Three Products Before a Purchase', 'So Sánh Ba Sản Phẩm Trước Khi Mua',
  'Research and compare 3 products before making a purchase decision', 'Tìm hiểu và so sánh 3 sản phẩm trước khi quyết định mua',
  'learning', 'MONEY', 'challenge', 'choice_pool',
  10, 3, 5, 'INDEPENDENT',
  13, 14, 16,
  'Practice informed consumer decision-making.',
  'Luyện đưa ra quyết định tiêu dùng thông minh.',
  'Let them use real money for real purchases.',
  'Để con dùng tiền thật cho mua sắm thật.',
  'BQ-MONEY-COMPARE-PRODUCTS-A14', 'MONEY', 8,
  true, false, true, 1,
  30, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Create a Presentation Explaining an Issue', 'Tạo Bài Thuyết Trình Giải Thích Một Vấn Đề',
  'Research an issue and create a presentation explaining it clearly', 'Nghiên cứu một vấn đề và tạo bài thuyết trình giải thích rõ ràng',
  'learning', 'COMMUNICATION', 'challenge', 'choice_pool',
  10, 3, 6, 'INDEPENDENT',
  13, 14, 16,
  'Build argumentation and visual communication skills.',
  'Xây dựng kỹ năng lập luận và truyền đạt bằng hình ảnh.',
  'Provide feedback on clarity, not just content.',
  'Phản hồi về sự rõ ràng, không chỉ nội dung.',
  'BQ-COMM-PRESENT-ISSUE-A14', 'COMMUNICATION', 7,
  true, false, true, 1,
  60, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Interview Two People About a Career', 'Phỏng Vấn Hai Người Về Nghề Nghiệp',
  'Interview two different people about their careers and compare insights', 'Phỏng vấn hai người về nghề nghiệp và so sánh những hiểu biết',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  10, 3, 6, 'INDEPENDENT',
  13, 14, 16,
  'Deepen career exploration through multiple perspectives.',
  'Mở rộng khám phá nghề nghiệp qua nhiều góc nhìn.',
  'Help arrange interviews if needed. Let them prepare questions.',
  'Giúp sắp xếp phỏng vấn nếu cần. Để con chuẩn bị câu hỏi.',
  'BQ-WORLD-CAREER-COMPARE-A14', 'CAREER_EXPLORATION', 2,
  true, false, true, 1,
  60, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Build a Small Software, Art or Science Project', 'Xây Dựng Dự Án Phần Mềm, Nghệ Thuật hoặc Khoa Học Nhỏ',
  'Create a small creative project using your skills and interests', 'Tạo một dự án sáng tạo nhỏ sử dụng kỹ năng và sở thích',
  'learning', 'LEARNING', 'challenge', 'choice_pool',
  15, 5, 7, 'INDEPENDENT',
  13, 14, 16,
  'Apply skills in a self-directed creative project.',
  'Áp dụng kỹ năng trong dự án sáng tạo tự định hướng.',
  'Help with resources but let them define the project.',
  'Giúp tài nguyên nhưng để con tự xác định dự án.',
  'BQ-LEARN-CREATIVE-PROJECT-A14', 'PROJECT_EXECUTION', 3,
  true, false, true, 1,
  120, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Organize a Family Activity', 'Tổ Chức Hoạt Động Gia Đình',
  'Plan and organize a fun activity for the whole family', 'Lên kế hoạch và tổ chức một hoạt động vui cho cả gia đình',
  'family', 'CHARACTER_FAMILY', 'challenge', 'choice_pool',
  10, 3, 5, 'INDEPENDENT',
  13, 14, 16,
  'Practice event planning and family leadership.',
  'Luyện tổ chức sự kiện và lãnh đạo gia đình.',
  'Participate enthusiastically. Let them run the show.',
  'Tham gia nhiệt tình. Để con điều hành.',
  'BQ-CHAR-ORGANIZE-ACTIVITY-A14', 'FAMILY_CONTRIBUTION', 7,
  true, false, true, 1,
  60, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Review My Privacy Settings', 'Kiểm Tra Cài Đặt Riêng Tư',
  'Review and update privacy settings on all your online accounts', 'Kiểm tra và cập nhật cài đặt riêng tư trên tất cả tài khoản trực tuyến',
  'learning', 'DIGITAL', 'challenge', 'choice_pool',
  8, 2, 5, 'SUPPORTED',
  13, 14, 16,
  'Build proactive digital privacy management.',
  'Xây dựng quản lý quyền riêng tư kỹ thuật số chủ động.',
  'Do this together. Explain the importance of each setting.',
  'Làm cùng nhau. Giải thích tầm quan trọng của mỗi cài đặt.',
  'BQ-DIGITAL-PRIVACY-A14', 'DIGITAL_SAFETY', 4,
  true, false, true, 1,
  30, 'once',
  true, true
)
ON CONFLICT DO NOTHING;

-- =============================================
-- AGE 15 — "I can run a project" (15 templates)
-- =============================================
INSERT INTO tasks (
  family_id, name, name_vi, description, description_vi,
  category, skill_domain, behavior_type, availability_type,
  coin_reward, star_reward, difficulty, independence_level,
  min_age, recommended_age, max_age,
  development_goal, development_goal_vi, parent_tip, parent_tip_vi,
  template_key, skill_ladder_key, skill_ladder_level,
  requires_approval, requires_supervision, in_pool, pool_max_per_day,
  estimated_minutes, recommended_frequency,
  is_system_template, active
) VALUES
(
  '00000000-0000-0000-0000-000000000000',
  'Manage Personal Monthly Spending', 'Quản Lý Chi Tiêu Cá Nhân Hàng Tháng',
  'Track and manage your monthly spending within a budget', 'Theo dõi và quản lý chi tiêu hàng tháng trong ngân sách',
  'responsibility', 'MONEY', 'responsibility', 'both',
  0, 0, 6, 'INDEPENDENT',
  14, 15, 17,
  'Build monthly budgeting as a normal responsibility.',
  'Xây dựng lập ngân sách hàng tháng như trách nhiệm bình thường.',
  'Discuss finances openly. Share family budgeting concepts.',
  'Thảo luận tài chính cởi mở. Chia sẻ khái niệm ngân sách gia đình.',
  'BQ-MONEY-MONTHLY-SPENDING-A15', 'MONEY', 9,
  false, false, true, 1,
  15, 'monthly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Help Plan Family Meals', 'Giúp Lên Kế Hoạch Bữa Ăn Gia Đình',
  'Take part in planning family meals for the week', 'Tham gia lên kế hoạch bữa ăn gia đình cho tuần',
  'responsibility', 'LIFE_HOME', 'responsibility', 'both',
  0, 0, 5, 'INDEPENDENT',
  14, 15, 17,
  'Own part of family meal planning as a contributor.',
  'Chịu trách nhiệm một phần lên kế hoạch bữa ăn gia đình.',
  'Include them in planning discussions and decisions.',
  'Cho con tham gia thảo luận và quyết định lên kế hoạch.',
  'BQ-LIFE-MEAL-PLAN-A15', 'COOKING', 7,
  false, false, true, 1,
  20, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Cook for the Family', 'Nấu Ăn Cho Gia Đình',
  'Plan and cook a complete meal for the whole family', 'Lên kế hoạch và nấu bữa ăn hoàn chỉnh cho cả gia đình',
  'responsibility', 'LIFE_HOME', 'challenge', 'both',
  10, 3, 6, 'INDEPENDENT',
  14, 15, 17,
  'Full cooking responsibility for a family meal.',
  'Trách nhiệm nấu ăn hoàn toàn cho bữa ăn gia đình.',
  'Appreciate the effort. Offer to help with cleanup.',
  'Trân trọng nỗ lực. Đề nghị giúp dọn dẹp.',
  'BQ-LIFE-COOK-FAMILY-A15', 'COOKING', 7,
  true, false, true, 1,
  90, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Track School Deadlines Independently', 'Tự Theo Dõi Hạn Chót Trường',
  'Manage all school deadlines without any parent involvement', 'Quản lý tất cả hạn chót trường học mà không cần bố mẹ tham gia',
  'responsibility', 'SELF_MANAGEMENT', 'responsibility', 'assigned_only',
  0, 0, 5, 'INDEPENDENT',
  14, 15, 17,
  'Complete ownership of academic deadline management.',
  'Tự chủ hoàn toàn về quản lý hạn chót học tập.',
  'Do not check their deadlines. Trust their system.',
  'Không kiểm tra hạn chót của con. Tin tưởng hệ thống của con.',
  'BQ-SELF-DEADLINES-INDEPENDENT-A15', 'PLANNING', 7,
  false, false, false, null,
  5, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Maintain Important Personal Items', 'Bảo Quản Đồ Dùng Cá Nhân Quan Trọng',
  'Keep track of and maintain important personal belongings', 'Theo dõi và bảo quản đồ dùng cá nhân quan trọng',
  'responsibility', 'SELF_MANAGEMENT', 'responsibility', 'assigned_only',
  0, 0, 5, 'INDEPENDENT',
  14, 15, 17,
  'Build responsible ownership of valuable items.',
  'Xây dựng quyền sở hữu có trách nhiệm với đồ có giá trị.',
  'Expect responsibility. Don''t replace items carelessly lost.',
  'Kỳ vọng trách nhiệm. Không thay thế đồ mất do bất cẩn.',
  'BQ-SELF-PERSONAL-ITEMS-A15', 'PERSONAL_ORGANIZATION', 7,
  false, false, false, null,
  5, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Set a Monthly Goal', 'Đặt Mục Tiêu Tháng',
  'Define and work toward a meaningful monthly goal', 'Xác định và hướng tới một mục tiêu tháng có ý nghĩa',
  'learning', 'SELF_MANAGEMENT', 'habit_building', 'both',
  3, 1, 6, 'INDEPENDENT',
  14, 15, 17,
  'Build long-term goal-setting and execution skills.',
  'Xây dựng kỹ năng đặt mục tiêu dài hạn và thực hiện.',
  'Help define the goal if asked. Don''t impose your goals.',
  'Giúp xác định mục tiêu nếu con hỏi. Không áp đặt mục tiêu của mình.',
  'BQ-SELF-MONTHLY-GOAL-A15', 'PLANNING', 7,
  true, false, true, 1,
  15, 'monthly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Weekly Review and Reset', 'Nhìn Lại và Thiết Lập Lại Tuần',
  'Do a comprehensive weekly review and plan the next week', 'Nhìn lại tuần toàn diện và lập kế hoạch tuần tiếp theo',
  'learning', 'SELF_MANAGEMENT', 'habit_building', 'both',
  3, 1, 5, 'INDEPENDENT',
  14, 15, 17,
  'Integrate review and planning into a regular cycle.',
  'Tích hợp đánh giá và lập kế hoạch vào chu kỳ thường xuyên.',
  'Available for discussion but don''t initiate.',
  'Sẵn sàng thảo luận nhưng không chủ động bắt đầu.',
  'BQ-SELF-REVIEW-RESET-A15', 'PLANNING', 7,
  true, false, true, 1,
  20, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Manage Digital Distraction', 'Quản Lý Xao Nhãng Kỹ Thuật Số',
  'Actively manage screen time and digital distractions', 'Chủ động quản lý thời gian màn hình và xao nhãng kỹ thuật số',
  'learning', 'DIGITAL', 'habit_building', 'both',
  3, 1, 6, 'INDEPENDENT',
  14, 15, 17,
  'Build self-regulation around digital consumption.',
  'Xây dựng tự điều chỉnh về tiêu thụ kỹ thuật số.',
  'Discuss openly. Share your own screen time challenges.',
  'Thảo luận cởi mở. Chia sẻ thách thức màn hình của mình.',
  'BQ-DIGITAL-DISTRACTION-A15', 'DIGITAL_SAFETY', 5,
  true, false, true, 1,
  10, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Build Something Over 2 Weeks', 'Xây Dựng Điều Gì Đó Trong 2 Tuần',
  'Plan and execute a creative or technical project over 2 weeks', 'Lên kế hoạch và thực hiện dự án sáng tạo hoặc kỹ thuật trong 2 tuần',
  'learning', 'LEARNING', 'challenge', 'choice_pool',
  20, 5, 7, 'INDEPENDENT',
  14, 15, 17,
  'Build sustained project management over longer timeframes.',
  'Xây dựng quản lý dự án bền bỉ trong thời gian dài hơn.',
  'Help scope the project. Check in at milestones.',
  'Giúp xác định phạm vi dự án. Kiểm tra tại các mốc.',
  'BQ-LEARN-2WEEK-BUILD-A15', 'PROJECT_EXECUTION', 4,
  true, false, true, 1,
  120, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Create a Personal Portfolio Project', 'Tạo Dự Án Portfolio Cá Nhân',
  'Create a portfolio showcasing your skills, projects, and interests', 'Tạo portfolio giới thiệu kỹ năng, dự án và sở thích',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  15, 5, 7, 'INDEPENDENT',
  14, 15, 17,
  'Begin building a personal professional identity.',
  'Bắt đầu xây dựng bản sắc chuyên nghiệp cá nhân.',
  'Share examples but let them define their style.',
  'Chia sẻ ví dụ nhưng để con tự định hình phong cách.',
  'BQ-WORLD-PORTFOLIO-A15', 'CAREER_EXPLORATION', 3,
  true, false, true, 1,
  120, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Create a Household Budget Spreadsheet', 'Tạo Bảng Tính Ngân Sách Gia Đình',
  'Build a spreadsheet to track household or personal budget', 'Xây dựng bảng tính để theo dõi ngân sách gia đình hoặc cá nhân',
  'learning', 'MONEY', 'challenge', 'choice_pool',
  10, 3, 7, 'INDEPENDENT',
  14, 15, 17,
  'Apply spreadsheet skills to real financial management.',
  'Áp dụng kỹ năng bảng tính vào quản lý tài chính thực tế.',
  'Show a real family budget as reference if appropriate.',
  'Cho xem ngân sách gia đình thật làm tham khảo nếu phù hợp.',
  'BQ-MONEY-BUDGET-SHEET-A15', 'MONEY', 9,
  true, false, true, 1,
  60, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Give a 5-10 Minute Talk', 'Thuyết Trình 5-10 Phút',
  'Prepare and deliver a well-structured 5-10 minute talk', 'Chuẩn bị và trình bày bài nói 5-10 phút có cấu trúc tốt',
  'learning', 'COMMUNICATION', 'challenge', 'choice_pool',
  10, 3, 7, 'INDEPENDENT',
  14, 15, 17,
  'Build extended public speaking and persuasion skills.',
  'Xây dựng kỹ năng thuyết trình và thuyết phục mở rộng.',
  'Give detailed feedback. Suggest improvements for next time.',
  'Cho phản hồi chi tiết. Đề xuất cải thiện cho lần sau.',
  'BQ-COMM-TALK-10-A15', 'COMMUNICATION', 8,
  true, false, true, 1,
  45, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Research Three Possible Careers', 'Nghiên Cứu Ba Nghề Nghiệp Có Thể',
  'Research 3 careers you''re interested in and compare them', 'Nghiên cứu 3 nghề nghiệp con quan tâm và so sánh',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  10, 3, 6, 'INDEPENDENT',
  14, 15, 17,
  'Begin structured career exploration.',
  'Bắt đầu khám phá nghề nghiệp có hệ thống.',
  'Discuss findings openly. Don''t dismiss unusual choices.',
  'Thảo luận phát hiện cởi mở. Không bác bỏ lựa chọn bất thường.',
  'BQ-WORLD-CAREER-RESEARCH-A15', 'CAREER_EXPLORATION', 3,
  true, false, true, 1,
  60, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Write a Professional Email', 'Viết Email Chuyên Nghiệp',
  'Write a professional email for a real purpose (inquiry, request, etc.)', 'Viết email chuyên nghiệp cho mục đích thực (hỏi thông tin, yêu cầu, v.v.)',
  'learning', 'COMMUNICATION', 'challenge', 'choice_pool',
  8, 2, 6, 'INDEPENDENT',
  14, 15, 17,
  'Build professional written communication skills.',
  'Xây dựng kỹ năng giao tiếp viết chuyên nghiệp.',
  'Review together if they ask. Don''t rewrite it for them.',
  'Xem cùng nếu con hỏi. Không viết lại thay con.',
  'BQ-COMM-PRO-EMAIL-A15', 'COMMUNICATION', 8,
  true, false, true, 1,
  20, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Resolve a Disagreement Calmly', 'Giải Quyết Bất Đồng Một Cách Bình Tĩnh',
  'When a disagreement happens, use calm communication to resolve it', 'Khi có bất đồng, dùng giao tiếp bình tĩnh để giải quyết',
  'family', 'CHARACTER_FAMILY', 'character', 'both',
  0, 3, 6, 'INDEPENDENT',
  14, 15, 17,
  'Build conflict resolution and emotional maturity.',
  'Xây dựng khả năng giải quyết xung đột và trưởng thành cảm xúc.',
  'Model calm disagreement. Acknowledge their perspective.',
  'Làm gương bất đồng bình tĩnh. Công nhận góc nhìn của con.',
  'BQ-CHAR-RESOLVE-DISAGREE-A15', null, null,
  true, false, true, 1,
  15, 'once',
  true, true
)
ON CONFLICT DO NOTHING;

-- =============================================
-- AGE 16 — "I prepare for adult independence" (15 templates)
-- =============================================
INSERT INTO tasks (
  family_id, name, name_vi, description, description_vi,
  category, skill_domain, behavior_type, availability_type,
  coin_reward, star_reward, difficulty, independence_level,
  min_age, recommended_age, max_age,
  development_goal, development_goal_vi, parent_tip, parent_tip_vi,
  template_key, skill_ladder_key, skill_ladder_level,
  requires_approval, requires_supervision, in_pool, pool_max_per_day,
  estimated_minutes, recommended_frequency,
  is_system_template, active
) VALUES
(
  '00000000-0000-0000-0000-000000000000',
  'Cook Several Complete Meals', 'Nấu Nhiều Bữa Ăn Hoàn Chỉnh',
  'Regularly cook complete meals for yourself and the family', 'Thường xuyên nấu bữa ăn hoàn chỉnh cho bản thân và gia đình',
  'responsibility', 'LIFE_HOME', 'responsibility', 'both',
  0, 0, 6, 'INDEPENDENT',
  15, 16, 18,
  'Cooking as a normalized adult life skill.',
  'Nấu ăn như kỹ năng sống trưởng thành bình thường.',
  'This is expected, not rewarded. Acknowledge quality and effort.',
  'Đây là điều kỳ vọng, không phải thưởng. Công nhận chất lượng và nỗ lực.',
  'BQ-LIFE-COOK-SEVERAL-A16', 'COOKING', 8,
  false, false, true, 1,
  60, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Do Grocery Shopping from List and Budget', 'Đi Mua Sắm Theo Danh Sách và Ngân Sách',
  'Do grocery shopping independently with a list and budget', 'Tự đi mua sắm với danh sách và ngân sách',
  'learning', 'MONEY', 'challenge', 'both',
  10, 3, 7, 'INDEPENDENT',
  15, 16, 18,
  'Combine practical shopping, budgeting, and life skills.',
  'Kết hợp kỹ năng mua sắm thực tế, lập ngân sách và kỹ năng sống.',
  'Give real responsibility with real budget.',
  'Giao trách nhiệm thật với ngân sách thật.',
  'BQ-MONEY-GROCERY-BUDGET-A16', 'MONEY', 10,
  true, false, true, 1,
  60, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Manage Laundry Completely', 'Quản Lý Giặt Giũ Hoàn Toàn',
  'Handle all your laundry needs without any help or reminders', 'Tự xử lý tất cả nhu cầu giặt giũ mà không cần giúp đỡ hay nhắc nhở',
  'responsibility', 'LIFE_HOME', 'responsibility', 'assigned_only',
  0, 0, 5, 'INDEPENDENT',
  15, 16, 18,
  'Complete laundry independence as a normal adult skill.',
  'Tự lập hoàn toàn về giặt giũ như kỹ năng người lớn bình thường.',
  'This should be completely autonomous by now.',
  'Đây nên hoàn toàn tự chủ rồi.',
  'BQ-LIFE-LAUNDRY-FULL-A16', 'HOUSEHOLD_CARE', 8,
  false, false, false, null,
  45, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Manage My Personal Schedule', 'Quản Lý Lịch Trình Cá Nhân',
  'Fully manage your personal schedule, appointments, and commitments', 'Hoàn toàn quản lý lịch trình, cuộc hẹn và cam kết cá nhân',
  'responsibility', 'SELF_MANAGEMENT', 'responsibility', 'assigned_only',
  0, 0, 6, 'INDEPENDENT',
  15, 16, 18,
  'Full adult-level schedule management.',
  'Quản lý lịch trình ở mức người lớn.',
  'Stop managing their schedule. Let them manage yours if needed.',
  'Ngừng quản lý lịch của con. Để con quản lý lịch của bạn nếu cần.',
  'BQ-SELF-PERSONAL-SCHEDULE-A16', 'PLANNING', 8,
  false, false, false, null,
  10, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Handle Important Personal Information Safely', 'Bảo Quản Thông Tin Cá Nhân Quan Trọng An Toàn',
  'Manage passwords, personal documents, and sensitive information safely', 'Quản lý mật khẩu, giấy tờ cá nhân và thông tin nhạy cảm an toàn',
  'responsibility', 'DIGITAL', 'responsibility', 'assigned_only',
  0, 0, 7, 'INDEPENDENT',
  15, 16, 18,
  'Build responsible information security habits.',
  'Xây dựng thói quen bảo mật thông tin có trách nhiệm.',
  'Teach password managers and secure practices.',
  'Dạy về phần mềm quản lý mật khẩu và thực hành bảo mật.',
  'BQ-DIGITAL-INFO-SAFETY-A16', 'DIGITAL_SAFETY', 6,
  false, false, false, null,
  15, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Make a Monthly Budget', 'Lập Ngân Sách Tháng',
  'Create and follow a monthly personal budget', 'Tạo và tuân theo ngân sách cá nhân hàng tháng',
  'learning', 'MONEY', 'habit_building', 'both',
  3, 1, 7, 'INDEPENDENT',
  15, 16, 18,
  'Build real monthly budgeting as a sustainable habit.',
  'Xây dựng lập ngân sách tháng thực tế như thói quen bền vững.',
  'Share your budgeting approach if they''re interested.',
  'Chia sẻ cách lập ngân sách nếu con quan tâm.',
  'BQ-MONEY-MONTHLY-BUDGET-A16', 'MONEY', 10,
  true, false, true, 1,
  30, 'monthly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Analyze One Month of Spending', 'Phân Tích Chi Tiêu Một Tháng',
  'Analyze your spending over the past month and identify patterns', 'Phân tích chi tiêu tháng qua và xác định xu hướng',
  'learning', 'MONEY', 'challenge', 'choice_pool',
  10, 3, 7, 'INDEPENDENT',
  15, 16, 18,
  'Build analytical financial skills.',
  'Xây dựng kỹ năng phân tích tài chính.',
  'Discuss insights together if they share.',
  'Thảo luận những nhận xét cùng nhau nếu con chia sẻ.',
  'BQ-MONEY-ANALYZE-SPENDING-A16', 'MONEY', 10,
  true, false, true, 1,
  30, 'monthly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Explain Compound Interest', 'Giải Thích Lãi Suất Kép',
  'Research and explain compound interest with examples', 'Nghiên cứu và giải thích lãi suất kép với ví dụ',
  'learning', 'MONEY', 'challenge', 'choice_pool',
  10, 3, 7, 'INDEPENDENT',
  15, 16, 18,
  'Understand foundational financial concepts.',
  'Hiểu các khái niệm tài chính nền tảng.',
  'Connect to real savings accounts if possible.',
  'Kết nối với tài khoản tiết kiệm thật nếu có thể.',
  'BQ-MONEY-COMPOUND-INTEREST-A16', 'MONEY', 11,
  true, false, true, 1,
  30, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Compare Cash, Debit and Credit', 'So Sánh Tiền Mặt, Thẻ Ghi Nợ và Thẻ Tín Dụng',
  'Research and compare the pros and cons of cash, debit, and credit', 'Nghiên cứu và so sánh ưu nhược điểm của tiền mặt, thẻ ghi nợ và thẻ tín dụng',
  'learning', 'MONEY', 'challenge', 'choice_pool',
  10, 3, 7, 'INDEPENDENT',
  15, 16, 18,
  'Understand different payment methods and their implications.',
  'Hiểu các phương thức thanh toán khác nhau và hệ quả.',
  'Discuss real-world examples from your own experience.',
  'Thảo luận ví dụ thực tế từ kinh nghiệm của bạn.',
  'BQ-MONEY-PAYMENT-METHODS-A16', 'MONEY', 11,
  true, false, true, 1,
  30, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Identify a Financial Scam', 'Nhận Biết Lừa Đảo Tài Chính',
  'Study examples of financial scams and explain how to identify them', 'Nghiên cứu ví dụ lừa đảo tài chính và giải thích cách nhận biết',
  'learning', 'DIGITAL', 'challenge', 'choice_pool',
  10, 3, 7, 'INDEPENDENT',
  15, 16, 18,
  'Build practical financial fraud awareness.',
  'Xây dựng nhận thức thực tế về gian lận tài chính.',
  'Share real examples. Discuss how to protect yourself.',
  'Chia sẻ ví dụ thật. Thảo luận cách tự bảo vệ.',
  'BQ-DIGITAL-FINANCIAL-SCAM-A16', 'DIGITAL_SAFETY', 6,
  true, false, true, 1,
  30, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Create My First CV', 'Tạo CV Đầu Tiên',
  'Create your first CV or resume highlighting skills and experiences', 'Tạo CV đầu tiên nêu bật kỹ năng và kinh nghiệm',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  15, 5, 7, 'INDEPENDENT',
  15, 16, 18,
  'Begin building a professional identity.',
  'Bắt đầu xây dựng bản sắc chuyên nghiệp.',
  'Review together. Offer honest constructive feedback.',
  'Xem cùng nhau. Cho phản hồi xây dựng trung thực.',
  'BQ-WORLD-FIRST-CV-A16', 'CAREER_EXPLORATION', 4,
  true, false, true, 1,
  60, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Practice a Job Interview', 'Luyện Tập Phỏng Vấn Xin Việc',
  'Practice a mock job interview with a family member or friend', 'Luyện tập phỏng vấn xin việc giả với thành viên gia đình hoặc bạn',
  'learning', 'COMMUNICATION', 'challenge', 'choice_pool',
  10, 3, 7, 'SUPPORTED',
  15, 16, 18,
  'Build interview skills and professional confidence.',
  'Xây dựng kỹ năng phỏng vấn và sự tự tin chuyên nghiệp.',
  'Take the interview seriously. Give real feedback.',
  'Coi phỏng vấn nghiêm túc. Cho phản hồi thật.',
  'BQ-COMM-JOB-INTERVIEW-A16', 'CAREER_EXPLORATION', 4,
  true, false, true, 1,
  30, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Research University or Education Routes', 'Nghiên Cứu Hướng Đại Học hoặc Giáo Dục',
  'Research and compare educational pathways that interest you', 'Nghiên cứu và so sánh các con đường giáo dục con quan tâm',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  10, 3, 7, 'INDEPENDENT',
  15, 16, 18,
  'Make informed decisions about future education.',
  'Đưa ra quyết định thông minh về giáo dục tương lai.',
  'Support exploration. Don''t push a single path.',
  'Ủng hộ khám phá. Không ép theo một con đường duy nhất.',
  'BQ-WORLD-EDUCATION-ROUTES-A16', 'CAREER_EXPLORATION', 4,
  true, false, true, 1,
  60, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Complete a 30-Day Personal Project', 'Hoàn Thành Dự Án Cá Nhân 30 Ngày',
  'Define, plan and complete a significant personal project over 30 days', 'Xác định, lập kế hoạch và hoàn thành dự án cá nhân quan trọng trong 30 ngày',
  'learning', 'SELF_MANAGEMENT', 'challenge', 'choice_pool',
  25, 8, 8, 'INDEPENDENT',
  15, 16, 18,
  'Build major project management and sustained execution.',
  'Xây dựng quản lý dự án lớn và thực hiện bền bỉ.',
  'Help scope at the start. Support at milestones only.',
  'Giúp xác định phạm vi lúc đầu. Chỉ hỗ trợ tại các mốc.',
  'BQ-SELF-30DAY-PROJECT-A16', 'PROJECT_EXECUTION', 5,
  true, false, true, 1,
  120, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Use AI, Then Verify the Result', 'Dùng AI, Sau Đó Xác Minh Kết Quả',
  'Use an AI tool for a task, then verify the output against trusted sources', 'Dùng công cụ AI cho một nhiệm vụ, sau đó xác minh kết quả với nguồn đáng tin',
  'learning', 'DIGITAL', 'challenge', 'choice_pool',
  10, 3, 7, 'INDEPENDENT',
  15, 16, 18,
  'Build responsible AI usage and verification habits.',
  'Xây dựng thói quen sử dụng AI có trách nhiệm và kiểm chứng.',
  'Discuss where AI is helpful and where it can mislead.',
  'Thảo luận AI hữu ích ở đâu và có thể gây nhầm lẫn ở đâu.',
  'BQ-DIGITAL-AI-VERIFY-A16', 'AI_LITERACY', 2,
  true, false, true, 1,
  30, 'weekly',
  true, true
)
ON CONFLICT DO NOTHING;

-- =============================================
-- AGE 17 — "I can run much of my life" (15 templates)
-- =============================================
INSERT INTO tasks (
  family_id, name, name_vi, description, description_vi,
  category, skill_domain, behavior_type, availability_type,
  coin_reward, star_reward, difficulty, independence_level,
  min_age, recommended_age, max_age,
  development_goal, development_goal_vi, parent_tip, parent_tip_vi,
  template_key, skill_ladder_key, skill_ladder_level,
  requires_approval, requires_supervision, in_pool, pool_max_per_day,
  estimated_minutes, recommended_frequency,
  is_system_template, active
) VALUES
(
  '00000000-0000-0000-0000-000000000000',
  'Manage My Schedule Without Reminders', 'Quản Lý Lịch Trình Không Cần Nhắc',
  'Handle all scheduling, appointments and commitments without any reminders', 'Tự xử lý mọi lịch trình, cuộc hẹn và cam kết mà không cần nhắc nhở',
  'responsibility', 'SELF_MANAGEMENT', 'responsibility', 'assigned_only',
  0, 0, 7, 'INDEPENDENT',
  16, 17, 18,
  'Adult-level autonomous schedule management.',
  'Quản lý lịch trình tự chủ ở mức người lớn.',
  'This is now their responsibility. Intervene only in emergencies.',
  'Đây giờ là trách nhiệm của con. Chỉ can thiệp trong trường hợp khẩn cấp.',
  'BQ-SELF-SCHEDULE-AUTONOMOUS-A17', 'PLANNING', 9,
  false, false, false, null,
  10, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Prepare Family Meals Independently', 'Tự Nấu Bữa Ăn Gia Đình',
  'Plan and prepare family meals completely on your own', 'Tự lên kế hoạch và nấu bữa ăn gia đình hoàn toàn',
  'responsibility', 'LIFE_HOME', 'responsibility', 'both',
  0, 0, 7, 'INDEPENDENT',
  16, 17, 18,
  'Full cooking independence for the household.',
  'Tự lập hoàn toàn về nấu ăn cho gia đình.',
  'Appreciate their cooking. Offer to help with cleanup.',
  'Trân trọng việc nấu ăn của con. Đề nghị giúp dọn dẹp.',
  'BQ-LIFE-COOK-INDEPENDENT-A17', 'COOKING', 8,
  false, false, true, 1,
  90, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Manage Laundry and Room Maintenance', 'Quản Lý Giặt Giũ và Dọn Phòng',
  'Handle all laundry and room maintenance autonomously', 'Tự xử lý toàn bộ giặt giũ và duy trì phòng',
  'responsibility', 'LIFE_HOME', 'responsibility', 'assigned_only',
  0, 0, 6, 'INDEPENDENT',
  16, 17, 18,
  'Complete domestic autonomy.',
  'Tự chủ sinh hoạt hoàn toàn.',
  'This should be completely autonomous.',
  'Đây nên hoàn toàn tự chủ.',
  'BQ-LIFE-LAUNDRY-ROOM-A17', 'HOUSEHOLD_CARE', 9,
  false, false, false, null,
  60, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Manage a Personal Budget', 'Quản Lý Ngân Sách Cá Nhân',
  'Maintain a monthly personal budget and track against it', 'Duy trì ngân sách cá nhân hàng tháng và theo dõi',
  'responsibility', 'MONEY', 'responsibility', 'both',
  0, 0, 7, 'INDEPENDENT',
  16, 17, 18,
  'Independent financial management.',
  'Quản lý tài chính tự lập.',
  'Available for financial advice. Don''t impose.',
  'Sẵn sàng tư vấn tài chính. Không áp đặt.',
  'BQ-MONEY-PERSONAL-BUDGET-A17', 'MONEY', 11,
  false, false, true, 1,
  15, 'monthly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Plan My Transport', 'Lên Kế Hoạch Phương Tiện Di Chuyển',
  'Plan your own transportation for activities and appointments', 'Tự lên kế hoạch phương tiện cho hoạt động và cuộc hẹn',
  'responsibility', 'WORLD_INDEPENDENCE', 'responsibility', 'both',
  0, 0, 6, 'INDEPENDENT',
  16, 17, 18,
  'Build transport planning and navigation independence.',
  'Xây dựng tính tự lập trong lập kế hoạch di chuyển.',
  'Let them figure it out. Help only if asked.',
  'Để con tự tìm cách. Chỉ giúp khi được hỏi.',
  'BQ-WORLD-TRANSPORT-A17', 'TRAVEL_NAVIGATION', 4,
  false, false, true, 1,
  15, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Organize Personal Documents', 'Sắp Xếp Giấy Tờ Cá Nhân',
  'Organize and maintain your personal documents and records', 'Sắp xếp và bảo quản giấy tờ và hồ sơ cá nhân',
  'responsibility', 'SELF_MANAGEMENT', 'responsibility', 'assigned_only',
  0, 0, 7, 'INDEPENDENT',
  16, 17, 18,
  'Adult-level document management.',
  'Quản lý giấy tờ ở mức người lớn.',
  'Help set up a system. Then let them maintain it.',
  'Giúp thiết lập hệ thống. Sau đó để con tự duy trì.',
  'BQ-SELF-DOCUMENTS-A17', 'PERSONAL_ORGANIZATION', 8,
  false, false, false, null,
  30, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Plan a 3-Day Trip Itinerary and Budget', 'Lập Lịch Trình và Ngân Sách Chuyến Đi 3 Ngày',
  'Plan a complete 3-day trip including itinerary, budget and logistics', 'Lên kế hoạch hoàn chỉnh chuyến đi 3 ngày gồm lịch trình, ngân sách và hậu cần',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  20, 5, 8, 'INDEPENDENT',
  16, 17, 18,
  'Build comprehensive travel planning skills.',
  'Xây dựng kỹ năng lập kế hoạch du lịch toàn diện.',
  'Let them plan everything. Offer budget if it''s a real trip.',
  'Để con lên kế hoạch mọi thứ. Cấp ngân sách nếu là chuyến thật.',
  'BQ-WORLD-3DAY-TRIP-A17', 'TRAVEL_NAVIGATION', 5,
  true, false, true, 1,
  120, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Cook a Complete Dinner for the Family', 'Nấu Bữa Tối Hoàn Chỉnh Cho Gia Đình',
  'Plan, shop for and cook a complete dinner for the whole family', 'Lên kế hoạch, mua sắm và nấu bữa tối hoàn chỉnh cho cả gia đình',
  'responsibility', 'LIFE_HOME', 'challenge', 'choice_pool',
  10, 3, 8, 'INDEPENDENT',
  16, 17, 18,
  'Full dinner production as an adult-level skill.',
  'Nấu bữa tối hoàn chỉnh như kỹ năng cấp độ người lớn.',
  'Be a grateful dinner guest. Compliment their cooking.',
  'Làm khách mời bữa tối biết ơn. Khen nấu ăn của con.',
  'BQ-LIFE-FULL-DINNER-A17', 'COOKING', 8,
  true, false, true, 1,
  120, 'weekly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Create an Education/Career Decision Matrix', 'Tạo Ma Trận Quyết Định Học Tập/Nghề Nghiệp',
  'Create a structured decision matrix comparing education or career options', 'Tạo ma trận quyết định có cấu trúc so sánh các lựa chọn học tập hoặc nghề nghiệp',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  15, 5, 8, 'INDEPENDENT',
  16, 17, 18,
  'Build structured decision-making for major life choices.',
  'Xây dựng ra quyết định có cấu trúc cho lựa chọn lớn trong đời.',
  'Share your decision-making approach. Don''t make the decision for them.',
  'Chia sẻ cách ra quyết định. Không quyết định thay con.',
  'BQ-WORLD-DECISION-MATRIX-A17', 'CAREER_EXPLORATION', 5,
  true, false, true, 1,
  60, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Complete a One-Month Independent Project', 'Hoàn Thành Dự Án Độc Lập Một Tháng',
  'Plan and execute a significant project over one month independently', 'Lên kế hoạch và thực hiện dự án quan trọng trong một tháng',
  'learning', 'SELF_MANAGEMENT', 'challenge', 'choice_pool',
  30, 10, 9, 'INDEPENDENT',
  16, 17, 18,
  'Execute large-scale independent projects.',
  'Thực hiện dự án quy mô lớn một cách độc lập.',
  'Check in at milestones only. Celebrate completion.',
  'Kiểm tra chỉ tại các mốc. Chúc mừng hoàn thành.',
  'BQ-SELF-1MONTH-PROJECT-A17', 'PROJECT_EXECUTION', 6,
  true, false, true, 1,
  120, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Lead a Family or Community Activity', 'Dẫn Dắt Hoạt Động Gia Đình hoặc Cộng Đồng',
  'Take the lead in organizing and running a family or community event', 'Chủ động tổ chức và điều hành sự kiện gia đình hoặc cộng đồng',
  'family', 'CHARACTER_FAMILY', 'challenge', 'choice_pool',
  15, 5, 8, 'INDEPENDENT',
  16, 17, 18,
  'Build leadership and organizational skills.',
  'Xây dựng kỹ năng lãnh đạo và tổ chức.',
  'Follow their lead. Participate as a team member.',
  'Theo sự dẫn dắt của con. Tham gia như thành viên.',
  'BQ-CHAR-LEAD-ACTIVITY-A17', 'FAMILY_CONTRIBUTION', 8,
  true, false, true, 1,
  120, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Teach a Younger Person a Useful Skill', 'Dạy Một Người Trẻ Hơn Kỹ Năng Hữu Ích',
  'Choose a skill you know well and teach it patiently to someone younger', 'Chọn một kỹ năng con giỏi và kiên nhẫn dạy cho người trẻ hơn',
  'family', 'COMMUNICATION', 'character', 'choice_pool',
  0, 3, 6, 'INDEPENDENT',
  16, 17, 18,
  'Develop mentoring and teaching abilities.',
  'Phát triển khả năng cố vấn và dạy dỗ.',
  'Notice their teaching approach and give constructive feedback.',
  'Chú ý cách dạy của con và cho phản hồi xây dựng.',
  'BQ-COMM-TEACH-YOUNGER-A17', 'COMMUNICATION', 9,
  true, false, true, 1,
  30, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Write a Formal Request or Email', 'Viết Yêu Cầu hoặc Email Chính Thức',
  'Write a formal request or business email for a real purpose', 'Viết yêu cầu chính thức hoặc email công việc cho mục đích thực',
  'learning', 'COMMUNICATION', 'challenge', 'choice_pool',
  8, 2, 7, 'INDEPENDENT',
  16, 17, 18,
  'Build formal written communication for professional contexts.',
  'Xây dựng giao tiếp viết chính thức cho bối cảnh chuyên nghiệp.',
  'Help review if asked. Don''t write it for them.',
  'Giúp xem lại nếu được hỏi. Không viết thay con.',
  'BQ-COMM-FORMAL-WRITE-A17', 'COMMUNICATION', 9,
  true, false, true, 1,
  20, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Compare 3 University or Career Routes', 'So Sánh 3 Hướng Đại Học hoặc Nghề Nghiệp',
  'Research and compare 3 potential paths with pros, cons and requirements', 'Nghiên cứu và so sánh 3 con đường tiềm năng với ưu nhược điểm và yêu cầu',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  10, 3, 8, 'INDEPENDENT',
  16, 17, 18,
  'Make informed decisions about future directions.',
  'Đưa ra quyết định thông minh về hướng đi tương lai.',
  'Listen and discuss. Support their exploration.',
  'Lắng nghe và thảo luận. Ủng hộ sự khám phá.',
  'BQ-WORLD-COMPARE-ROUTES-A17', 'CAREER_EXPLORATION', 5,
  true, false, true, 1,
  60, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Present a Recommendation to Parents', 'Trình Bày Đề Xuất Với Bố Mẹ',
  'Prepare and present a well-argued recommendation about a family decision', 'Chuẩn bị và trình bày đề xuất có lập luận tốt về quyết định gia đình',
  'learning', 'COMMUNICATION', 'challenge', 'choice_pool',
  8, 2, 7, 'INDEPENDENT',
  16, 17, 18,
  'Build persuasion and structured advocacy skills.',
  'Xây dựng kỹ năng thuyết phục và vận động có cấu trúc.',
  'Take the presentation seriously. Respond thoughtfully.',
  'Coi bài trình bày nghiêm túc. Phản hồi chu đáo.',
  'BQ-COMM-RECOMMEND-A17', 'COMMUNICATION', 9,
  true, false, true, 1,
  30, 'once',
  true, true
)
ON CONFLICT DO NOTHING;

-- =============================================
-- AGE 18 — "Adult readiness" (15 templates)
-- =============================================
INSERT INTO tasks (
  family_id, name, name_vi, description, description_vi,
  category, skill_domain, behavior_type, availability_type,
  coin_reward, star_reward, difficulty, independence_level,
  min_age, recommended_age, max_age,
  development_goal, development_goal_vi, parent_tip, parent_tip_vi,
  template_key, skill_ladder_key, skill_ladder_level,
  requires_approval, requires_supervision, in_pool, pool_max_per_day,
  estimated_minutes, recommended_frequency,
  is_system_template, active
) VALUES
(
  '00000000-0000-0000-0000-000000000000',
  'Plan and Cook Meals Independently', 'Tự Lên Kế Hoạch và Nấu Ăn',
  'Plan, shop for and cook meals independently as a regular routine', 'Tự lên kế hoạch, mua sắm và nấu ăn như thói quen thường xuyên',
  'responsibility', 'LIFE_HOME', 'responsibility', 'both',
  0, 0, 7, 'INDEPENDENT',
  17, 18, 21,
  'Cooking as a fully independent adult life skill.',
  'Nấu ăn như kỹ năng sống hoàn toàn tự lập của người lớn.',
  'This is now a life skill, not a task. Appreciate their independence.',
  'Đây giờ là kỹ năng sống, không phải nhiệm vụ. Trân trọng sự tự lập.',
  'BQ-LIFE-COOK-ADULT-A18', 'COOKING', 9,
  false, false, true, 1,
  60, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Maintain Clothing and Living Space', 'Bảo Quản Quần Áo và Không Gian Sống',
  'Keep your clothing and living space clean and organized autonomously', 'Tự giữ quần áo và không gian sống sạch sẽ và ngăn nắp',
  'responsibility', 'LIFE_HOME', 'responsibility', 'assigned_only',
  0, 0, 6, 'INDEPENDENT',
  17, 18, 21,
  'Full domestic autonomy as preparation for independent living.',
  'Tự chủ sinh hoạt hoàn toàn như chuẩn bị cho cuộc sống độc lập.',
  'This should be assumed, not monitored.',
  'Đây nên là điều đương nhiên, không cần giám sát.',
  'BQ-LIFE-MAINTAIN-SPACE-A18', 'HOUSEHOLD_CARE', 9,
  false, false, false, null,
  30, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Manage Appointments and Schedule', 'Quản Lý Cuộc Hẹn và Lịch Trình',
  'Manage all your appointments, deadlines and schedule independently', 'Tự quản lý mọi cuộc hẹn, hạn chót và lịch trình',
  'responsibility', 'SELF_MANAGEMENT', 'responsibility', 'both',
  0, 0, 7, 'INDEPENDENT',
  17, 18, 21,
  'Adult-level time and commitment management.',
  'Quản lý thời gian và cam kết ở mức người lớn.',
  'They should be managing this entirely on their own.',
  'Con nên hoàn toàn tự quản lý điều này.',
  'BQ-SELF-MANAGE-SCHEDULE-A18', 'PLANNING', 10,
  false, false, true, 1,
  10, 'daily',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Run a One-Month Personal Budget', 'Chạy Ngân Sách Cá Nhân Một Tháng',
  'Create and strictly follow a one-month personal budget', 'Tạo và tuân thủ chặt chẽ ngân sách cá nhân một tháng',
  'learning', 'MONEY', 'challenge', 'choice_pool',
  15, 5, 8, 'INDEPENDENT',
  17, 18, 21,
  'Real-world independent budgeting practice.',
  'Luyện tập lập ngân sách độc lập trong thực tế.',
  'Discuss results if they want to share. Don''t judge spending.',
  'Thảo luận kết quả nếu con muốn chia sẻ. Không phán xét chi tiêu.',
  'BQ-MONEY-1MONTH-BUDGET-A18', 'MONEY', 12,
  true, false, true, 1,
  30, 'monthly',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Plan One Week of Meals and Grocery Cost', 'Lập Kế Hoạch Bữa Ăn và Chi Phí Mua Sắm Một Tuần',
  'Plan all meals for one week including grocery list and total cost', 'Lập kế hoạch tất cả bữa ăn cho một tuần gồm danh sách mua sắm và tổng chi phí',
  'responsibility', 'LIFE_HOME', 'challenge', 'choice_pool',
  15, 5, 9, 'INDEPENDENT',
  17, 18, 21,
  'Combine meal planning with real budget management.',
  'Kết hợp lập kế hoạch bữa ăn với quản lý ngân sách thực.',
  'Give them the full grocery budget for the week.',
  'Giao cho con toàn bộ ngân sách mua sắm tuần.',
  'BQ-LIFE-MEAL-WEEK-A18', 'COOKING', 9,
  true, false, true, 1,
  60, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Build an Emergency-Budget Simulation', 'Xây Dựng Mô Phỏng Ngân Sách Khẩn Cấp',
  'Create a simulation of how you would handle an emergency budget', 'Tạo mô phỏng cách xử lý ngân sách khẩn cấp',
  'learning', 'MONEY', 'challenge', 'choice_pool',
  15, 5, 9, 'INDEPENDENT',
  17, 18, 21,
  'Prepare for financial emergencies and unexpected expenses.',
  'Chuẩn bị cho tình huống tài chính khẩn cấp và chi phí bất ngờ.',
  'Share real-world examples from your experience.',
  'Chia sẻ ví dụ thực tế từ kinh nghiệm.',
  'BQ-MONEY-EMERGENCY-BUDGET-A18', 'MONEY', 12,
  true, false, true, 1,
  45, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Compare Two Education or Job Offers', 'So Sánh Hai Lựa Chọn Học Tập hoặc Việc Làm',
  'Analyze and compare two real education or job offers systematically', 'Phân tích và so sánh có hệ thống hai lựa chọn học tập hoặc việc làm thực',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  15, 5, 9, 'INDEPENDENT',
  17, 18, 21,
  'Build structured decision-making for major life choices.',
  'Xây dựng ra quyết định có cấu trúc cho lựa chọn lớn.',
  'Help analyze but respect their final decision.',
  'Giúp phân tích nhưng tôn trọng quyết định cuối cùng.',
  'BQ-WORLD-COMPARE-OFFERS-A18', 'CAREER_EXPLORATION', 6,
  true, false, true, 1,
  60, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Create a CV and Portfolio', 'Tạo CV và Portfolio',
  'Build a complete professional CV and portfolio of your work', 'Xây dựng CV chuyên nghiệp hoàn chỉnh và portfolio công việc',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  15, 5, 8, 'INDEPENDENT',
  17, 18, 21,
  'Build professional self-presentation skills.',
  'Xây dựng kỹ năng giới thiệu bản thân chuyên nghiệp.',
  'Review and suggest improvements if asked.',
  'Xem và đề xuất cải thiện nếu được hỏi.',
  'BQ-WORLD-CV-PORTFOLIO-A18', 'CAREER_EXPLORATION', 6,
  true, false, true, 1,
  120, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Complete a Long-Term Personal Project', 'Hoàn Thành Dự Án Cá Nhân Dài Hạn',
  'Plan and complete a significant long-term personal project', 'Lên kế hoạch và hoàn thành dự án cá nhân dài hạn quan trọng',
  'learning', 'SELF_MANAGEMENT', 'challenge', 'choice_pool',
  30, 10, 10, 'INDEPENDENT',
  17, 18, 21,
  'Demonstrate sustained project execution at an adult level.',
  'Thể hiện khả năng thực hiện dự án bền bỉ ở mức người lớn.',
  'Be available as a sounding board. Celebrate completion.',
  'Sẵn sàng lắng nghe ý tưởng. Chúc mừng hoàn thành.',
  'BQ-SELF-LONGTERM-PROJECT-A18', 'PROJECT_EXECUTION', 7,
  true, false, true, 1,
  120, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Organize an Important Appointment', 'Tổ Chức Một Cuộc Hẹn Quan Trọng',
  'Handle scheduling, preparation and follow-up for an important appointment', 'Xử lý lịch hẹn, chuẩn bị và theo dõi sau cuộc hẹn quan trọng',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  10, 3, 8, 'INDEPENDENT',
  17, 18, 21,
  'Build real-world appointment and professional meeting skills.',
  'Xây dựng kỹ năng hẹn gặp và họp chuyên nghiệp thực tế.',
  'Let them handle it end to end.',
  'Để con tự xử lý từ đầu đến cuối.',
  'BQ-WORLD-APPOINTMENT-A18', null, null,
  true, false, true, 1,
  30, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Plan Independent Travel', 'Lên Kế Hoạch Du Lịch Tự Lập',
  'Plan and execute independent travel (local trip or further)', 'Lên kế hoạch và thực hiện chuyến du lịch tự lập (gần hoặc xa)',
  'learning', 'WORLD_INDEPENDENCE', 'challenge', 'choice_pool',
  15, 5, 9, 'INDEPENDENT',
  17, 18, 21,
  'Full travel independence as an adult skill.',
  'Tự lập du lịch hoàn toàn như kỹ năng người lớn.',
  'Agree on safety communication. Trust them with logistics.',
  'Thống nhất về liên lạc an toàn. Tin tưởng con với hậu cần.',
  'BQ-WORLD-INDEPENDENT-TRAVEL-A18', 'TRAVEL_NAVIGATION', 6,
  true, false, true, 1,
  120, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Lead a Volunteer or Community Project', 'Dẫn Dắt Dự Án Tình Nguyện hoặc Cộng Đồng',
  'Take leadership of a volunteer or community service project', 'Dẫn dắt một dự án tình nguyện hoặc phục vụ cộng đồng',
  'family', 'CHARACTER_FAMILY', 'character', 'choice_pool',
  0, 5, 9, 'INDEPENDENT',
  17, 18, 21,
  'Build community leadership and social responsibility.',
  'Xây dựng khả năng lãnh đạo cộng đồng và trách nhiệm xã hội.',
  'Support their initiative. Help with connections if needed.',
  'Ủng hộ sáng kiến. Giúp kết nối nếu cần.',
  'BQ-CHAR-VOLUNTEER-LEAD-A18', 'FAMILY_CONTRIBUTION', 9,
  true, false, true, 1,
  120, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Learn One Adult Skill from a Parent', 'Học Một Kỹ Năng Người Lớn Từ Bố Mẹ',
  'Learn a practical adult skill from a parent (taxes, repairs, cooking specialty, etc.)', 'Học một kỹ năng thực tế người lớn từ bố mẹ (thuế, sửa chữa, nấu ăn đặc biệt, v.v.)',
  'family', 'CHARACTER_FAMILY', 'challenge', 'choice_pool',
  10, 3, 7, 'INDEPENDENT',
  17, 18, 21,
  'Knowledge transfer between generations.',
  'Truyền đạt kiến thức giữa các thế hệ.',
  'Teach patiently. Value the opportunity to pass on knowledge.',
  'Dạy kiên nhẫn. Trân trọng cơ hội truyền đạt kiến thức.',
  'BQ-CHAR-LEARN-FROM-PARENT-A18', null, null,
  true, false, true, 1,
  60, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Protect My Professional Digital Identity', 'Bảo Vệ Bản Sắc Số Chuyên Nghiệp',
  'Review and clean up your online presence for professional readiness', 'Xem xét và dọn dẹp sự hiện diện trực tuyến cho sự sẵn sàng chuyên nghiệp',
  'learning', 'DIGITAL', 'habit_building', 'both',
  3, 1, 8, 'INDEPENDENT',
  17, 18, 21,
  'Build awareness of professional digital reputation.',
  'Xây dựng nhận thức về danh tiếng kỹ thuật số chuyên nghiệp.',
  'Help them Google themselves and discuss what they find.',
  'Giúp con tìm kiếm tên mình trên Google và thảo luận kết quả.',
  'BQ-DIGITAL-PRO-IDENTITY-A18', 'DIGITAL_SAFETY', 7,
  true, false, true, 1,
  30, 'once',
  true, true
),
(
  '00000000-0000-0000-0000-000000000000',
  'Create My 1-Year Personal Development Plan', 'Tạo Kế Hoạch Phát Triển Cá Nhân 1 Năm',
  'Create a comprehensive 1-year plan for personal growth and goals', 'Tạo kế hoạch toàn diện 1 năm cho phát triển và mục tiêu cá nhân',
  'learning', 'SELF_MANAGEMENT', 'challenge', 'choice_pool',
  20, 8, 10, 'INDEPENDENT',
  17, 18, 21,
  'Capstone: long-term independent life planning.',
  'Đỉnh cao: lập kế hoạch cuộc sống dài hạn tự lập.',
  'This is their plan for their life. Respect their choices.',
  'Đây là kế hoạch của con cho cuộc sống của con. Tôn trọng lựa chọn.',
  'BQ-SELF-1YEAR-PLAN-A18', null, null,
  true, false, true, 1,
  120, 'once',
  true, true
)
ON CONFLICT DO NOTHING;
