-- 0036_rebalance_economy_age_spread.sql — Real-price coin economy, quest evidence,
-- and an even spread of quest/reward templates across ages 6–17.
--
-- Economy: 1 coin ≈ 1,000đ. Reward template coin_cost = current Vietnamese
-- retail price (Oct 2026) ÷ 1,000; family experiences are priced at one
-- child's share (family cost ÷ 4); privileges are priced by value.
-- Quest coin_reward is derived from effort (minutes, frequency, habit fading)
-- so an 8-year-old earns ~100 coins/week and an 11-year-old ~150 coins/week at
-- full engagement — matching the family's real weekly spend per child.
-- Responsibilities and character/kindness quests stay at 0 coins; stars are
-- unchanged. Only system templates are touched here; family copies are synced
-- by supabase/scripts/sync-family-copies-with-templates.sql (opt-in).

-- =========================================================
-- 0. Backup the template rows this migration rewrites
-- =========================================================
create table if not exists backup_0036_task_templates as
  select * from tasks where is_system_template = true;
create table if not exists backup_0036_reward_templates as
  select * from rewards where is_system_template = true;
create table if not exists backup_0036_family_quest_templates as
  select * from family_quests where is_system_template = true;

-- =========================================================
-- 1. Quest coins + evidence (system templates)
--    Matched by template_key, or by name for legacy templates without a key.
-- =========================================================
update tasks t set
  coin_reward = v.coin,
  evidence_type = v.ev,
  evidence_required = v.req,
  max_audio_seconds = v.sec
from (values
  (null, 'Choose a healthy snack', 3, 'photo', false, 30),
  (null, 'Design a greeting card', 10, 'photo', true, 30),
  ('BQ-COMM-DRAW-EXPLAIN-A07', null, 8, 'audio', false, 60),
  (null, 'Draw something new', 10, 'photo', true, 30),
  (null, 'Healthy Snack Choice', 3, 'photo', false, 30),
  ('BQ-LIFE-PREP-FRUIT-A07', null, 5, 'photo', false, 30),
  ('BQ-LEARN-ANIMAL-FACTS-A07', null, 8, 'text', false, 30),
  ('BQ-LEARN-ENG-WORDS-A07', null, 5, 'text', false, 30),
  (null, 'Learn 5 New English Words', 5, 'text', false, 30),
  (null, 'Learn 5 new words', 5, 'text', false, 30),
  (null, 'Learn a fun fact and share it', 5, 'audio', false, 60),
  (null, 'Make something with your hands', 10, 'photo', true, 30),
  ('BQ-MONEY-NEEDS-WANTS-A07', null, 5, 'text', false, 30),
  (null, 'Outdoor play', 10, 'choice', false, 30),
  ('BQ-COMM-READ-ALOUD-A07', null, 5, 'audio', false, 60),
  ('BQ-CHAR-KIND-THING-A07', null, 0, 'parent_observation', false, 30),
  (null, 'Do a Kind Act', 0, 'parent_observation', false, 30),
  (null, 'Help Set the Table', 0, 'parent_observation', false, 30),
  (null, 'Help Someone', 0, 'parent_observation', false, 30),
  (null, 'Help With Dishes', 0, 'parent_observation', false, 30),
  (null, 'Help someone today', 0, 'parent_observation', false, 30),
  (null, 'Say Thank You', 0, 'parent_observation', false, 30),
  (null, 'Drink enough water today', 2, 'choice', false, 30),
  ('BQ-SELF-SCHOOL-BAG-A07', null, 3, 'choice', false, 30),
  ('BQ-LEARN-READ-15-A07', null, 3, 'choice', false, 30),
  ('BQ-MONEY-SAVE-GOAL-A07', null, 5, 'choice', false, 30),
  (null, 'Brush Teeth', 0, 'none', false, 30),
  ('BQ-LIFE-CLEAR-PLATE-A07', null, 0, 'none', false, 30),
  ('BQ-LIFE-MAKE-BED-A07', null, 0, 'none', false, 30),
  (null, 'Put Away Belongings', 0, 'none', false, 30),
  (null, 'Put Dirty Clothes Away', 0, 'none', false, 30),
  ('BQ-LIFE-DIRTY-CLOTHES-A07', null, 0, 'none', false, 30),
  ('BQ-SELF-TIDY-TOYS-A07', null, 0, 'none', false, 30),
  (null, 'Set the table for dinner', 0, 'none', false, 30),
  (null, 'Take Care of Plants', 0, 'none', false, 30),
  (null, 'Tidy one space', 0, 'none', false, 30),
  ('BQ-LIFE-WATER-PLANTS-A07', null, 0, 'none', false, 30),
  (null, 'Water the plants', 0, 'none', false, 30),
  (null, 'Beautiful Handwriting', 5, 'photo', false, 30),
  (null, 'Bike Ride', 10, 'choice', false, 30),
  ('BQ-MONEY-COMPARE-PRICE-A08', null, 5, 'text', false, 30),
  (null, 'Draw Something Creative', 10, 'photo', true, 30),
  (null, 'English Reading', 5, 'choice', false, 30),
  (null, 'English Speaking Practice', 8, 'audio', false, 60),
  (null, 'English speaking practice', 8, 'audio', false, 60),
  (null, 'Exercise 20 Minutes', 8, 'choice', false, 30),
  (null, 'Exercise for 20 minutes', 8, 'choice', false, 30),
  (null, 'Go for a walk or bike ride', 10, 'choice', false, 30),
  ('BQ-WORLD-COUNTRY-A08', null, 8, 'text', false, 30),
  ('BQ-LIFE-SANDWICH-A08', null, 5, 'photo', false, 30),
  ('BQ-MONEY-SHOP-LIST-A08', null, 5, 'photo', false, 30),
  (null, 'Math Practice', 8, 'choice', false, 30),
  (null, 'Music Practice', 8, 'audio', false, 60),
  (null, 'Music practice', 8, 'audio', false, 60),
  (null, 'Outdoor Play', 10, 'choice', false, 30),
  (null, 'Read 20 Minutes', 8, 'choice', false, 30),
  (null, 'Read for fun', 8, 'choice', false, 30),
  ('BQ-COMM-ENG-SPEAK-A08', null, 3, 'audio', false, 60),
  (null, 'Swimming Practice', 15, 'parent_observation', false, 30),
  (null, 'Tell Me What You Learned', 3, 'audio', false, 60),
  ('BQ-COMM-TELL-LEARNED-A08', null, 5, 'audio', false, 60),
  (null, 'Try something new today', 8, 'choice', false, 30),
  (null, 'Watch a nature documentary', 5, 'text', false, 30),
  (null, 'Call Grandparents', 0, 'parent_observation', false, 30),
  (null, 'Call or chat with grandparents', 0, 'parent_observation', false, 30),
  (null, 'Do a random act of kindness', 0, 'parent_observation', false, 30),
  ('BQ-CHAR-FEED-PET-A08', null, 0, 'none', false, 30),
  (null, 'Help Family Without Being Asked', 0, 'parent_observation', false, 30),
  (null, 'Help Sister', 0, 'parent_observation', false, 30),
  (null, 'Help a sibling', 0, 'parent_observation', false, 30),
  (null, 'Write a thank-you note', 0, 'photo', false, 30),
  ('BQ-SELF-RESP-FIRST-A08', null, 2, 'choice', false, 30),
  (null, 'Keep Desk Organized', 3, 'photo', false, 30),
  (null, 'Prepare School Bag', 3, 'choice', false, 30),
  ('BQ-SELF-SCHOOL-BAG-A08', null, 3, 'choice', false, 30),
  (null, 'Prepare tomorrow''s school bag', 3, 'choice', false, 30),
  ('BQ-LEARN-READ-20-A08', null, 4, 'choice', false, 30),
  (null, 'Sleep on Time', 10, 'parent_observation', false, 30),
  ('BQ-LIFE-WEEKLY-TIDY-A08', null, 5, 'photo', false, 30),
  ('BQ-LIFE-TIDY-DESK-A08', null, 0, 'none', false, 30),
  ('BQ-LIFE-PUT-CLOTHES-A08', null, 0, 'photo', false, 30),
  ('BQ-LIFE-SET-TABLE-A08', null, 0, 'none', false, 30),
  ('BQ-LIFE-SORT-LAUNDRY-A08', null, 0, 'photo', false, 30),
  (null, 'Cook or bake something simple', 15, 'photo', true, 30),
  ('BQ-MONEY-BUDGET-LIST-A09', null, 8, 'photo', false, 30),
  ('BQ-COMM-PRESENT-2-A09', null, 5, 'parent_observation', false, 30),
  (null, 'Learn About a Country', 10, 'text', true, 30),
  ('BQ-HEALTH-FIRST-AID-A09', null, 8, 'parent_observation', false, 30),
  (null, 'Learn about a country', 10, 'text', true, 30),
  ('BQ-WORLD-MAP-NAV-A09', null, 10, 'parent_observation', false, 30),
  (null, 'Prepare for Tomorrow', 5, 'choice', false, 30),
  ('BQ-LEARN-RESEARCH-Q-A09', null, 10, 'text', true, 30),
  (null, 'Review Today''s Lessons', 8, 'text', false, 30),
  (null, 'Write a short story', 15, 'photo', true, 30),
  ('BQ-CHAR-INTERVIEW-GRANDPARENTS-A09', null, 0, 'audio', false, 60),
  (null, 'Vacuum a Room', 0, 'parent_observation', false, 30),
  ('BQ-SELF-FOCUS-25-A09', null, 5, 'choice', false, 30),
  (null, 'Finish Homework', 3, 'choice', false, 30),
  (null, 'Fold My Clothes', 3, 'photo', false, 30),
  ('BQ-SELF-PREP-TOMORROW-A09', null, 3, 'choice', false, 30),
  (null, 'Screen Time Self-Control', 2, 'choice', false, 30),
  (null, 'Screen time self-control', 2, 'choice', false, 30),
  ('BQ-SELF-HW-NO-REMIND-A09', null, 2, 'choice', false, 30),
  ('BQ-LEARN-WEEKLY-READ-A09', null, 5, 'choice', false, 30),
  ('BQ-LIFE-FOLD-CLOTHES-A09', null, 0, 'photo', false, 30),
  ('BQ-SELF-SCHOOL-SUPPLIES-A09', null, 0, 'photo', false, 30),
  ('BQ-CHAR-OWN-AREA-A09', null, 0, 'photo', false, 30),
  ('BQ-LIFE-OWN-SNACK-A09', null, 0, 'none', false, 30),
  ('BQ-LIFE-VACUUM-A09', null, 0, 'photo', false, 30),
  ('BQ-MONEY-COMPARE-3-A10', null, 8, 'text', false, 30),
  ('BQ-LEARN-STEM-EXP-A10', null, 15, 'photo', true, 30),
  ('BQ-LIFE-COOK-SIMPLE-A10', null, 15, 'photo', true, 30),
  (null, 'Finish One Book', 50, 'photo', true, 30),
  ('BQ-COMM-PRESENT-3-A10', null, 8, 'parent_observation', false, 30),
  (null, 'Learn 10 New English Words', 10, 'text', true, 30),
  (null, 'Mini research project', 20, 'photo', true, 30),
  ('BQ-WORLD-PACK-TRIP-A10', null, 8, 'photo', false, 30),
  (null, 'Read 30 Minutes', 10, 'choice', false, 30),
  (null, 'Admit a Mistake Honestly', 0, 'parent_observation', false, 30),
  ('BQ-CHAR-GAME-NIGHT-A10', null, 0, 'parent_observation', false, 30),
  (null, 'Resolve a Conflict Calmly', 0, 'parent_observation', false, 30),
  ('BQ-COMM-TEACH-SKILL-A10', null, 0, 'parent_observation', false, 30),
  (null, 'Teach someone something', 0, 'parent_observation', false, 30),
  (null, 'Clean My Room', 5, 'photo', false, 30),
  ('BQ-SELF-TOP3-A10', null, 2, 'text', false, 30),
  ('BQ-LIFE-LAUNDRY-HELP-A10', null, 5, 'photo', false, 30),
  ('BQ-LEARN-READ-30-A10', null, 5, 'text', false, 30),
  ('BQ-DIGITAL-SCREEN-FREE-A10', null, 5, 'choice', false, 30),
  ('BQ-LIFE-ROOM-RESET-A10', null, 5, 'photo', false, 30),
  ('BQ-LIFE-CLEAN-SHARED-A10', null, 0, 'photo', false, 30),
  ('BQ-LIFE-HELP-DINNER-A10', null, 0, 'none', false, 30),
  ('BQ-SELF-SCHOOL-MATERIALS-A10', null, 0, 'photo', false, 30),
  ('BQ-LIFE-COOK-MEAL-A11', null, 15, 'photo', true, 30),
  ('BQ-LEARN-COMPARE-SOURCES-A11', null, 10, 'text', true, 30),
  ('BQ-DIGITAL-FACT-CHECK-A11', null, 8, 'text', false, 30),
  ('BQ-LEARN-TWO-SOURCES-A11', null, 10, 'text', true, 30),
  (null, 'Mini Research Project', 20, 'photo', true, 30),
  ('BQ-MONEY-PURCHASE-BUDGET-A11', null, 10, 'photo', true, 30),
  ('BQ-COMM-EXPLAIN-YOUNGER-A11', null, 0, 'parent_observation', false, 30),
  (null, 'Help Sister With Homework', 0, 'parent_observation', false, 30),
  ('BQ-CHAR-HELP-SIBLING-A11', null, 0, 'parent_observation', false, 30),
  (null, 'Teach Sister Something', 0, 'parent_observation', false, 30),
  ('BQ-LIFE-FULL-LAUNDRY-A11', null, 8, 'photo', false, 30),
  ('BQ-MONEY-SPENDING-LOG-A11', null, 2, 'text', false, 30),
  ('BQ-SELF-HW-INDEPENDENT-A11', null, 2, 'choice', false, 30),
  ('BQ-SELF-PLAN-WEEK-A11', null, 5, 'text', false, 30),
  ('BQ-SELF-TRACK-DEADLINES-A11', null, 3, 'text', false, 30),
  ('BQ-LIFE-CHANGE-SHEETS-A11', null, 0, 'photo', false, 30),
  ('BQ-LIFE-CLEAN-BATH-A11', null, 0, 'photo', false, 30),
  ('BQ-LIFE-CLEAN-KITCHEN-A11', null, 0, 'none', false, 30),
  ('BQ-LEARN-STEM-PROJECT-A12', null, 20, 'photo', true, 30),
  ('BQ-DIGITAL-AI-VERIFY-A12', null, 8, 'text', false, 30),
  ('BQ-LIFE-COOK-BASIC-A12', null, 20, 'photo', true, 30),
  ('BQ-LEARN-7DAY-SKILL-A12', null, 50, 'text', true, 30),
  ('BQ-LEARN-READ-NONFICTION-A12', null, 20, 'text', true, 30),
  ('BQ-DIGITAL-PHISHING-A12', null, 8, 'text', false, 30),
  ('BQ-CHAR-CREATE-USEFUL-A12', null, 0, 'photo', false, 30),
  ('BQ-SELF-FOCUS-45-A12', null, 8, 'choice', false, 30),
  ('BQ-MONEY-SAVINGS-GOAL-A12', null, 5, 'text', false, 30),
  ('BQ-SELF-WEEKLY-PLAN-A12', null, 5, 'text', false, 30),
  ('BQ-SELF-WEEKLY-REFLECT-A12', null, 5, 'text', false, 30),
  ('BQ-LIFE-CLEAN-ROOM-A12', null, 0, 'photo', false, 30),
  ('BQ-LIFE-PERSONAL-LAUNDRY-A12', null, 0, 'photo', false, 30),
  ('BQ-CHAR-SHARED-SPACE-A12', null, 0, 'photo', false, 30),
  ('BQ-SELF-SCHOOL-PREP-A12', null, 0, 'none', false, 30),
  ('BQ-SELF-7DAY-PROJECT-A13', null, 50, 'photo', true, 30),
  ('BQ-COMM-PRESENT-5-A13', null, 10, 'parent_observation', false, 30),
  ('BQ-WORLD-CAREER-INTERVIEW-A13', null, 15, 'text', true, 30),
  ('BQ-MONEY-MEAL-BUDGET-A13', null, 20, 'photo', true, 30),
  ('BQ-WORLD-TRAVEL-ROUTE-A13', null, 10, 'parent_observation', false, 30),
  ('BQ-CHAR-COMMUNITY-SERVICE-A13', null, 0, 'parent_observation', false, 30),
  ('BQ-SELF-PRIORITIES-A13', null, 2, 'text', false, 30),
  ('BQ-HEALTH-EMOTIONS-A13', null, 3, 'choice', false, 30),
  ('BQ-HEALTH-EXERCISE-A13', null, 5, 'choice', false, 30),
  ('BQ-SELF-WEEKLY-REVIEW-A13', null, 5, 'text', false, 30),
  ('BQ-LIFE-LAUNDRY-INDEPENDENT-A13', null, 0, 'photo', false, 30),
  ('BQ-LIFE-COOK-BASIC-MEAL-A13', null, 0, 'photo', false, 30),
  ('BQ-SELF-STUDY-AREA-A13', null, 0, 'none', false, 30),
  ('BQ-MONEY-ALLOWANCE-A13', null, 0, 'text', false, 30),
  ('BQ-CHAR-WEEKLY-CHORE-A13', null, 0, 'photo', false, 30),
  ('BQ-LEARN-CREATIVE-PROJECT-A14', null, 30, 'photo', true, 30),
  ('BQ-MONEY-COMPARE-PRODUCTS-A14', null, 10, 'text', true, 30),
  ('BQ-COMM-PRESENT-ISSUE-A14', null, 20, 'parent_observation', false, 30),
  ('BQ-DIGITAL-FACT-CHECK-3-A14', null, 10, 'text', true, 30),
  ('BQ-WORLD-CAREER-COMPARE-A14', null, 20, 'text', true, 30),
  ('BQ-DIGITAL-PRIVACY-A14', null, 10, 'text', true, 30),
  ('BQ-CHAR-ORGANIZE-ACTIVITY-A14', null, 0, 'parent_observation', false, 30),
  ('BQ-LIFE-COOK-MULTIPLE-A14', null, 10, 'photo', false, 30),
  ('BQ-DIGITAL-PHONE-AWAY-A14', null, 8, 'choice', false, 30),
  ('BQ-LEARN-LONG-READ-A14', null, 8, 'text', false, 30),
  ('BQ-SELF-PLAN-INDEPENDENT-A14', null, 5, 'text', false, 30),
  ('BQ-SELF-STUDY-SCHEDULE-A14', null, 0, 'none', false, 30),
  ('BQ-MONEY-PERSONAL-SPENDING-A14', null, 0, 'text', false, 30),
  ('BQ-CHAR-HOUSEHOLD-CHORE-A14', null, 0, 'photo', false, 30),
  ('BQ-LIFE-GROCERY-PLAN-A14', null, 0, 'text', false, 30),
  ('BQ-LEARN-2WEEK-BUILD-A15', null, 75, 'photo', true, 30),
  ('BQ-LIFE-COOK-FAMILY-A15', null, 25, 'photo', true, 30),
  ('BQ-MONEY-BUDGET-SHEET-A15', null, 20, 'photo', true, 30),
  ('BQ-WORLD-PORTFOLIO-A15', null, 30, 'photo', true, 30),
  ('BQ-COMM-TALK-10-A15', null, 15, 'parent_observation', false, 30),
  ('BQ-WORLD-CAREER-RESEARCH-A15', null, 20, 'text', true, 30),
  ('BQ-COMM-PRO-EMAIL-A15', null, 8, 'text', false, 30),
  ('BQ-CHAR-RESOLVE-DISAGREE-A15', null, 0, 'parent_observation', false, 30),
  ('BQ-DIGITAL-DISTRACTION-A15', null, 3, 'choice', false, 30),
  ('BQ-SELF-MONTHLY-GOAL-A15', null, 10, 'text', false, 30),
  ('BQ-SELF-REVIEW-RESET-A15', null, 5, 'text', false, 30),
  ('BQ-LIFE-MEAL-PLAN-A15', null, 0, 'text', false, 30),
  ('BQ-SELF-PERSONAL-ITEMS-A15', null, 0, 'none', false, 30),
  ('BQ-MONEY-MONTHLY-SPENDING-A15', null, 0, 'text', false, 30),
  ('BQ-SELF-DEADLINES-INDEPENDENT-A15', null, 0, 'none', false, 30),
  ('BQ-MONEY-ANALYZE-SPENDING-A16', null, 15, 'text', true, 30),
  ('BQ-MONEY-PAYMENT-METHODS-A16', null, 10, 'text', true, 30),
  ('BQ-SELF-30DAY-PROJECT-A16', null, 120, 'photo', true, 30),
  ('BQ-WORLD-FIRST-CV-A16', null, 20, 'photo', true, 30),
  ('BQ-MONEY-GROCERY-BUDGET-A16', null, 20, 'photo', true, 30),
  ('BQ-MONEY-COMPOUND-INTEREST-A16', null, 10, 'audio', true, 60),
  ('BQ-DIGITAL-FINANCIAL-SCAM-A16', null, 10, 'text', true, 30),
  ('BQ-COMM-JOB-INTERVIEW-A16', null, 10, 'parent_observation', false, 30),
  ('BQ-WORLD-EDUCATION-ROUTES-A16', null, 20, 'text', true, 30),
  ('BQ-DIGITAL-AI-VERIFY-A16', null, 10, 'text', true, 30),
  ('BQ-MONEY-MONTHLY-BUDGET-A16', null, 10, 'text', false, 30),
  ('BQ-LIFE-COOK-SEVERAL-A16', null, 0, 'photo', false, 30),
  ('BQ-DIGITAL-INFO-SAFETY-A16', null, 0, 'none', false, 30),
  ('BQ-LIFE-LAUNDRY-FULL-A16', null, 0, 'photo', false, 30),
  ('BQ-SELF-PERSONAL-SCHEDULE-A16', null, 0, 'none', false, 30),
  ('BQ-WORLD-COMPARE-ROUTES-A17', null, 20, 'text', true, 30),
  ('BQ-SELF-1MONTH-PROJECT-A17', null, 120, 'photo', true, 30),
  ('BQ-LIFE-FULL-DINNER-A17', null, 30, 'photo', true, 30),
  ('BQ-WORLD-DECISION-MATRIX-A17', null, 20, 'photo', true, 30),
  ('BQ-WORLD-3DAY-TRIP-A17', null, 30, 'photo', true, 30),
  ('BQ-COMM-RECOMMEND-A17', null, 10, 'parent_observation', false, 30),
  ('BQ-COMM-FORMAL-WRITE-A17', null, 8, 'text', false, 30),
  ('BQ-CHAR-LEAD-ACTIVITY-A17', null, 0, 'parent_observation', false, 30),
  ('BQ-COMM-TEACH-YOUNGER-A17', null, 0, 'parent_observation', false, 30),
  ('BQ-LIFE-LAUNDRY-ROOM-A17', null, 0, 'photo', false, 30),
  ('BQ-SELF-SCHEDULE-AUTONOMOUS-A17', null, 0, 'none', false, 30),
  ('BQ-MONEY-PERSONAL-BUDGET-A17', null, 0, 'text', false, 30),
  ('BQ-SELF-DOCUMENTS-A17', null, 0, 'photo', false, 30),
  ('BQ-WORLD-TRANSPORT-A17', null, 0, 'none', false, 30),
  ('BQ-LIFE-COOK-INDEPENDENT-A17', null, 0, 'photo', false, 30),
  ('BQ-MONEY-EMERGENCY-BUDGET-A18', null, 15, 'photo', true, 30),
  ('BQ-WORLD-COMPARE-OFFERS-A18', null, 20, 'text', true, 30),
  ('BQ-SELF-LONGTERM-PROJECT-A18', null, 150, 'photo', true, 30),
  ('BQ-SELF-1YEAR-PLAN-A18', null, 50, 'text', true, 30),
  ('BQ-WORLD-CV-PORTFOLIO-A18', null, 30, 'photo', true, 30),
  ('BQ-WORLD-APPOINTMENT-A18', null, 10, 'parent_observation', false, 30),
  ('BQ-WORLD-INDEPENDENT-TRAVEL-A18', null, 30, 'text', true, 30),
  ('BQ-LIFE-MEAL-WEEK-A18', null, 20, 'photo', true, 30),
  ('BQ-MONEY-1MONTH-BUDGET-A18', null, 75, 'text', true, 30),
  ('BQ-CHAR-VOLUNTEER-LEAD-A18', null, 0, 'parent_observation', false, 30),
  ('BQ-CHAR-LEARN-FROM-PARENT-A18', null, 0, 'parent_observation', false, 30),
  ('BQ-DIGITAL-PRO-IDENTITY-A18', null, 5, 'text', false, 30),
  ('BQ-LIFE-MAINTAIN-SPACE-A18', null, 0, 'none', false, 30),
  ('BQ-SELF-MANAGE-SCHEDULE-A18', null, 0, 'none', false, 30),
  ('BQ-LIFE-COOK-ADULT-A18', null, 0, 'none', false, 30)
) as v(key, name, coin, ev, req, sec)
where t.is_system_template = true
  and ((v.key is not null and t.template_key = v.key)
    or (v.key is null and t.template_key is null and t.name = v.name));

-- =========================================================
-- 2. Spread legacy templates' recommended age across 6–17
-- =========================================================
update tasks t set min_age = v.min_age, recommended_age = v.rec_age, max_age = v.max_age
from (values
  ('Choose a healthy snack', 5, 6, 12),
  ('Design a greeting card', 5, 6, 14),
  ('Draw something new', 5, 6, 14),
  ('Learn 5 new words', 6, 6, 12),
  ('Learn a fun fact and share it', 5, 6, 14),
  ('Make something with your hands', 5, 6, 14),
  ('Outdoor play', 5, 6, 14),
  ('Help someone today', 5, 6, 18),
  ('Drink enough water today', 5, 6, 14),
  ('Set the table for dinner', 5, 6, 14),
  ('Tidy one space', 5, 6, 14),
  ('Water the plants', 5, 6, 18),
  ('English speaking practice', 7, 9, 14),
  ('Exercise for 20 minutes', 5, 12, 18),
  ('Go for a walk or bike ride', 6, 14, 18),
  ('Music practice', 6, 10, 18),
  ('Try something new today', 6, 13, 16),
  ('Watch a nature documentary', 6, 9, 14),
  ('Call or chat with grandparents', 6, 11, 18),
  ('Do a random act of kindness', 6, 15, 18),
  ('Help a sibling', 6, 16, 18),
  ('Write a thank-you note', 6, 10, 14),
  ('Cook or bake something simple', 7, 11, 14),
  ('Write a short story', 7, 13, 15),
  ('Screen time self-control', 7, 16, 17),
  ('Mini research project', 8, 14, 15),
  ('Teach someone something', 8, 17, 18)
) as v(name, min_age, rec_age, max_age)
where t.is_system_template = true and t.template_key is null and t.name = v.name;

-- =========================================================
-- 3. New quest templates (age 6, teen habits)
-- =========================================================
insert into tasks (
  family_id, template_key, name, name_vi, description, description_vi,
  category, skill_domain, behavior_type, availability_type,
  coin_reward, star_reward, difficulty, independence_level,
  min_age, recommended_age, max_age,
  development_goal, development_goal_vi, parent_tip, parent_tip_vi,
  estimated_minutes, recommended_frequency, in_pool, evidence_type,
  requires_approval, requires_supervision, is_system_template, active
) values
  ('00000000-0000-0000-0000-000000000000', 'BQ-SELF-GET-DRESSED-A06', 'Get Dressed by Myself', 'Tự Mặc Quần Áo', 'Put on your clothes, socks and shoes without help', 'Tự mặc quần áo, mang tất và giày không cần giúp', 'responsibility', 'SELF_MANAGEMENT', 'responsibility', 'assigned_only', 0, 0, 1, 'GUIDED', 5, 6, 7, 'Build early self-care independence.', 'Xây dựng sự tự lập trong chăm sóc bản thân.', 'Lay clothes out the night before; praise effort, not speed.', 'Chuẩn bị quần áo từ tối hôm trước; khen sự cố gắng, không khen tốc độ.', 10, 'daily', false, 'none', true, false, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-HEALTH-WASH-HANDS-A06', 'Wash Hands Before Meals', 'Rửa Tay Trước Khi Ăn', 'Wash your hands with soap before every meal', 'Rửa tay bằng xà phòng trước mỗi bữa ăn', 'health', 'HEALTH', 'responsibility', 'assigned_only', 0, 0, 1, 'GUIDED', 5, 6, 8, 'Make hygiene an automatic habit.', 'Biến vệ sinh cá nhân thành thói quen tự nhiên.', 'Sing a short song together so the washing lasts 20 seconds.', 'Hát cùng con một bài ngắn để rửa tay đủ 20 giây.', 2, 'daily', false, 'none', true, false, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-LEARN-PICTURE-BOOK-A06', 'Read a Picture Book with a Parent', 'Đọc Truyện Tranh Cùng Ba Mẹ', 'Read or look through a picture book together for 10 minutes', 'Cùng ba mẹ đọc một cuốn truyện tranh trong 10 phút', 'learning', 'LEARNING', 'habit_building', 'both', 3, 1, 1, 'GUIDED', 5, 6, 7, 'Grow a love of reading before reading alone.', 'Nuôi dưỡng tình yêu đọc sách trước khi con tự đọc.', 'Let the child pick the book and turn the pages.', 'Để con tự chọn sách và tự lật trang.', 10, 'daily', true, 'choice', true, false, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-SELF-BEDTIME-ROUTINE-A06', 'Follow My Bedtime Routine Chart', 'Làm Theo Bảng Thói Quen Trước Khi Ngủ', 'Bath, pajamas, teeth and story by following your picture chart', 'Tắm, thay đồ ngủ, đánh răng và nghe truyện theo bảng hình', 'responsibility', 'SELF_MANAGEMENT', 'habit_building', 'assigned_only', 3, 1, 1, 'GUIDED', 5, 6, 7, 'Learn to follow a sequence of steps independently.', 'Tập làm theo một chuỗi các bước một cách tự lập.', 'Use pictures, not words, on the chart for young children.', 'Dùng hình ảnh thay vì chữ trên bảng cho trẻ nhỏ.', 10, 'daily', false, 'choice', true, false, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-HEALTH-SLEEP-8H-A16', 'Sleep 8 Hours on School Nights', 'Ngủ Đủ 8 Tiếng Vào Đêm Đi Học', 'Be in bed with the phone away early enough to sleep 8 hours', 'Lên giường và cất điện thoại đủ sớm để ngủ 8 tiếng', 'health', 'HEALTH', 'habit_building', 'both', 2, 1, 6, 'INDEPENDENT', 15, 16, 17, 'Protect sleep as the base of focus and mood.', 'Bảo vệ giấc ngủ – nền tảng của sự tập trung và cảm xúc.', 'Agree on a phone parking spot outside the bedroom.', 'Thống nhất một chỗ để điện thoại bên ngoài phòng ngủ.', 5, 'daily', true, 'choice', true, false, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-LEARN-EXAM-PLAN-A16', 'Weekly Exam Study Plan', 'Kế Hoạch Ôn Thi Hằng Tuần', 'Plan which subjects and topics to review this week before tests', 'Lên kế hoạch môn và nội dung cần ôn trong tuần trước các bài kiểm tra', 'learning', 'LEARNING', 'habit_building', 'both', 5, 1, 6, 'INDEPENDENT', 15, 16, 17, 'Own exam preparation instead of cramming.', 'Chủ động ôn thi thay vì học dồn.', 'Ask what is hardest this week, not how many hours.', 'Hỏi con phần nào khó nhất tuần này, đừng hỏi học bao nhiêu giờ.', 20, 'weekly', true, 'text', true, false, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-LEARN-LANG-DAILY-A17', 'Daily Language Practice', 'Luyện Ngoại Ngữ Mỗi Ngày', 'Practise a foreign language for 20 minutes (app, podcast or reading)', 'Luyện ngoại ngữ 20 phút (ứng dụng, podcast hoặc đọc)', 'learning', 'LEARNING', 'habit_building', 'both', 4, 1, 6, 'INDEPENDENT', 16, 17, 18, 'Keep a skill alive through small daily practice.', 'Duy trì kỹ năng bằng luyện tập nhỏ mỗi ngày.', 'Let the teen choose the method; check consistency, not content.', 'Để con tự chọn cách học; chỉ quan tâm sự đều đặn.', 20, 'daily', true, 'choice', true, false, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-HEALTH-EXERCISE-3X-A17', 'Exercise Three Times a Week', 'Tập Thể Dục 3 Lần Mỗi Tuần', 'Do at least three 30-minute workouts or sports sessions this week', 'Tập thể dục hoặc chơi thể thao ít nhất 3 buổi, mỗi buổi 30 phút trong tuần', 'health', 'HEALTH', 'habit_building', 'both', 5, 1, 6, 'INDEPENDENT', 16, 17, 18, 'Build a self-managed fitness routine for adult life.', 'Xây dựng thói quen vận động tự quản cho tuổi trưởng thành.', 'Join one session occasionally instead of reminding.', 'Thỉnh thoảng tập cùng con thay vì nhắc nhở.', 30, 'weekly', true, 'choice', true, false, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-MONEY-SAVE-MONTHLY-A17', 'Save Part of My Money Every Month', 'Tiết Kiệm Một Phần Tiền Mỗi Tháng', 'Move a planned share of your money into savings at the start of the month', 'Chuyển một phần tiền đã định vào tiết kiệm vào đầu mỗi tháng', 'learning', 'MONEY', 'habit_building', 'both', 10, 2, 7, 'INDEPENDENT', 16, 17, 18, 'Pay yourself first before spending.', 'Tiết kiệm trước, chi tiêu sau.', 'Discuss the percentage once; do not ask about the amount.', 'Thống nhất tỉ lệ một lần; không hỏi số tiền cụ thể.', 10, 'monthly', true, 'text', true, false, true, true)
on conflict do nothing;

-- =========================================================
-- 4. Reward templates: real price, coins, category, age range
-- =========================================================
update rewards r set
  coin_cost = v.coin,
  reference_price_vnd = v.vnd,
  category = v.cat,
  dream_eligible = v.dream,
  min_age = v.min_age, recommended_age = v.rec_age, max_age = v.max_age,
  name_vi = v.name_vi,
  description = coalesce(v.descr, r.description),
  description_vi = coalesce(v.descr_vi, r.description_vi),
  template_key = v.key
from (values
  ('Sticker', 'BQ-RWD-STICKER', 'Nhãn Dán', null, null, 'small', 20000, 20, 6, 7, 10, false),
  ('Favorite snack', 'BQ-RWD-FAVORITE-SNACK', 'Đồ Ăn Vặt Yêu Thích', null, null, 'small', 15000, 15, 6, 9, 17, false),
  ('Choose tonight''s dessert', 'BQ-RWD-CHOOSE-TONIGHT-S-DESSERT', 'Chọn Món Tráng Miệng', null, null, 'small', null, 20, 6, 9, 17, false),
  ('Ice cream', 'BQ-RWD-ICE-CREAM', 'Kem', null, null, 'small', 25000, 25, 6, 9, 17, false),
  ('Choose family movie', 'BQ-RWD-CHOOSE-FAMILY-MOVIE', 'Chọn Phim Gia Đình', null, null, 'small', null, 20, 6, 10, 17, false),
  ('Extra 20 min screen time', 'BQ-RWD-EXTRA-20-MIN-SCREEN-TIME', 'Thêm 20 Phút Màn Hình', null, null, 'small', null, 30, 6, 10, 17, false),
  ('Small stationery item', 'BQ-RWD-SMALL-STATIONERY-ITEM', 'Đồ Dùng Học Tập Nhỏ', null, null, 'small', 15000, 15, 6, 9, 14, false),
  ('Cute notebook', 'BQ-RWD-CUTE-NOTEBOOK', 'Sổ Tay Dễ Thương', null, null, 'small', 40000, 40, 7, 10, 15, false),
  ('Bubble tea', 'BQ-RWD-BUBBLE-TEA', 'Trà Sữa Trân Châu', null, null, 'small', 50000, 50, 7, 12, 17, false),
  ('Choose weekend breakfast', 'BQ-RWD-CHOOSE-WEEKEND-BREAKFAST', 'Chọn Bữa Sáng Cuối Tuần', null, null, 'small', null, 50, 6, 10, 17, false),
  ('Small toy', 'BQ-RWD-SMALL-TOY', 'Đồ Chơi Nhỏ', null, null, 'medium', 120000, 120, 6, 7, 10, false),
  ('New book', 'BQ-RWD-NEW-BOOK', 'Sách Mới', null, null, 'small', 90000, 90, 6, 10, 17, false),
  ('Movie theater', 'BQ-RWD-MOVIE-THEATER', 'Đi Rạp Chiếu Phim', 'Cinema trip (your share: ticket + popcorn)', 'Đi xem phim ở rạp (phần của con: vé + bắp nước)', 'experience', 130000, 130, 6, 11, 17, false),
  ('Small LEGO set', 'BQ-RWD-SMALL-LEGO-SET', 'Bộ LEGO Nhỏ', null, null, 'medium', 420000, 420, 6, 9, 14, false),
  ('Art supplies', 'BQ-RWD-ART-SUPPLIES', 'Đồ Vẽ / Mỹ Thuật', null, null, 'medium', 120000, 120, 6, 9, 15, false),
  ('Eat at favorite restaurant', 'BQ-RWD-EAT-AT-FAVORITE-RESTAURANT', 'Đi Ăn Nhà Hàng Yêu Thích', 'Family dinner at a favorite restaurant (your share)', 'Cả nhà đi ăn nhà hàng yêu thích (phần của con)', 'experience', 190000, 190, 6, 11, 17, false),
  ('Toy or accessory', 'BQ-RWD-TOY-OR-ACCESSORY', 'Đồ Chơi Hoặc Phụ Kiện', null, 'Một món đồ chơi hoặc phụ kiện tự chọn', 'medium', 350000, 350, 7, 10, 13, false),
  ('New T-shirt', 'BQ-RWD-NEW-T-SHIRT', 'Áo Mới', null, null, 'medium', 200000, 200, 6, 12, 17, false),
  ('Family activity of choice', 'BQ-RWD-FAMILY-ACTIVITY-OF-CHOICE', 'Hoạt Động Gia Đình Tự Chọn', 'Choose a family activity such as bowling or a playground (your share)', 'Chọn hoạt động gia đình như bowling, khu vui chơi (phần của con)', 'experience', 140000, 140, 6, 10, 17, false),
  ('Large LEGO set', 'BQ-RWD-LARGE-LEGO-SET', 'Bộ LEGO Lớn', null, null, 'large', 2200000, 2200, 8, 11, 16, true),
  ('Day trip', 'BQ-RWD-DAY-TRIP', 'Chuyến Đi Ngày', 'Family day trip chosen by you (your share)', 'Chuyến đi chơi trong ngày do con chọn (phần của con)', 'experience', 750000, 750, 6, 11, 17, true),
  ('Nice headphones', 'BQ-RWD-NICE-HEADPHONES', 'Tai Nghe', 'Kid-safe headphones (volume limited)', 'Tai nghe an toàn cho trẻ (giới hạn âm lượng)', 'medium', 900000, 900, 9, 13, 17, true),
  ('Theme park', 'BQ-RWD-THEME-PARK', 'Công Viên Giải Trí', 'Theme park day (your ticket + share of food)', 'Một ngày ở công viên giải trí (vé của con + phần ăn uống)', 'experience', 280000, 280, 6, 10, 15, false),
  ('Bicycle', 'BQ-RWD-BICYCLE', 'Xe Đạp', null, null, 'large', 2200000, 2200, 6, 9, 14, true),
  ('Smart watch', 'BQ-RWD-SMART-WATCH', 'Đồng Hồ Định Vị Trẻ Em', 'Kids smartwatch with GPS and calls', 'Đồng hồ định vị trẻ em có nghe gọi', 'large', 2000000, 2000, 6, 8, 11, true),
  ('Apple Watch', 'BQ-RWD-APPLE-WATCH', 'Apple Watch', 'Apple Watch SE', 'Apple Watch SE', 'dream', 6400000, 6400, 12, 14, 17, true),
  ('iPad', 'BQ-RWD-IPAD', 'iPad', 'An iPad (A16)', 'Một chiếc iPad (A16)', 'dream', 12000000, 12000, 8, 12, 17, true),
  ('Special family resort trip', 'BQ-RWD-SPECIAL-FAMILY-RESORT-TRIP', 'Chuyến Nghỉ Dưỡng Gia Đình', '2–3 night family resort trip (your share)', 'Chuyến nghỉ dưỡng 2–3 đêm cùng gia đình (phần của con)', 'dream', 5000000, 5000, 6, 11, 17, true),
  ('Singapore Adventure', 'BQ-RWD-SINGAPORE-ADVENTURE', 'Phiêu Lưu Singapore', '4-day family trip to Singapore (your share)', 'Chuyến du lịch Singapore 4 ngày cùng gia đình (phần của con)', 'dream', 12500000, 12500, 6, 12, 17, true)
) as v(name, key, name_vi, descr, descr_vi, cat, vnd, coin, min_age, rec_age, max_age, dream)
where r.is_system_template = true and r.name = v.name;

insert into rewards (
  family_id, template_key, name, name_vi, description, description_vi, category,
  reference_price_vnd, coin_cost, min_age, recommended_age, max_age, dream_eligible,
  requires_approval, is_system_template, active
) values
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-PLAY-DOUGH-SET', 'Play dough set', 'Bộ Đất Nặn', 'A set of play dough or slime', 'Một bộ đất nặn hoặc slime', 'small', 80000, 80, 6, 6, 9, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-COLORING-BOOK', 'Coloring book', 'Sách Tô Màu', 'A new coloring book', 'Một cuốn sách tô màu mới', 'small', 35000, 35, 6, 6, 9, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-EXTRA-BEDTIME-STORY', 'Extra bedtime story', 'Thêm Một Truyện Trước Khi Ngủ', 'One more story at bedtime', 'Thêm một câu chuyện trước giờ ngủ', 'small', null, 10, 6, 6, 8, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-INDOOR-PLAYGROUND-VISIT', 'Indoor playground visit', 'Đi Khu Vui Chơi Trẻ Em', 'Play at an indoor playground such as tiNiWorld', 'Đi chơi khu vui chơi trong nhà như tiNiWorld', 'experience', 130000, 130, 6, 6, 10, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-STUFFED-ANIMAL', 'Stuffed animal', 'Thú Bông', 'A soft stuffed animal', 'Một chú thú bông', 'medium', 150000, 150, 6, 7, 10, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-PARK-PICNIC', 'Park picnic', 'Đi Picnic Công Viên', 'A family picnic at the park (your share)', 'Cả nhà đi picnic ở công viên (phần của con)', 'experience', 50000, 50, 6, 7, 12, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-BOARD-GAME', 'Board game', 'Trò Chơi Board Game', 'A new family board game', 'Một bộ board game mới cho cả nhà', 'medium', 250000, 250, 8, 10, 14, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-COMIC-OR-MANGA-VOLUME', 'Comic or manga volume', 'Một Tập Truyện Tranh', 'One comic or manga volume', 'Một tập truyện tranh hoặc manga', 'small', 30000, 30, 8, 11, 17, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-BRACELET-MAKING-KIT', 'Bracelet-making kit', 'Bộ Làm Vòng Tay', 'A bead and bracelet craft kit', 'Bộ hạt cườm để tự làm vòng tay', 'medium', 120000, 120, 8, 10, 13, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-SCIENCE-EXPERIMENT-KIT', 'Science experiment kit', 'Bộ Thí Nghiệm Khoa Học', 'A kids science experiment kit', 'Bộ thí nghiệm khoa học cho trẻ', 'medium', 250000, 250, 8, 10, 13, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-SWIMMING-POOL-OUTING', 'Swimming pool outing', 'Đi Bơi Hồ Bơi', 'An afternoon at the swimming pool', 'Một buổi chiều đi bơi', 'experience', 80000, 80, 7, 10, 15, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-FRIEND-SLEEPOVER', 'Friend sleepover', 'Rủ Bạn Ngủ Lại Nhà', 'Invite a friend to sleep over (with parent agreement)', 'Rủ một bạn ngủ lại nhà (khi ba mẹ đồng ý)', 'experience', 100000, 100, 9, 11, 15, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-NEW-BACKPACK', 'New backpack', 'Ba Lô Mới', 'A new school backpack', 'Một chiếc ba lô đi học mới', 'medium', 400000, 400, 9, 13, 17, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-CAF-WITH-FRIENDS', 'Café with friends', 'Đi Cà Phê Cùng Bạn', 'A drink out with friends', 'Đi uống nước cùng bạn bè', 'small', 60000, 60, 12, 14, 17, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-MOVIE-WITH-FRIENDS', 'Movie with friends', 'Đi Xem Phim Cùng Bạn', 'Cinema with friends (ticket + popcorn)', 'Đi xem phim cùng bạn (vé + bắp nước)', 'experience', 150000, 150, 12, 14, 17, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-APP-STORE-GIFT-CARD', 'App store gift card', 'Thẻ Quà Tặng App Store', 'A 100,000đ app or game store gift card', 'Thẻ quà tặng kho ứng dụng/trò chơi 100.000đ', 'medium', 100000, 100, 12, 14, 17, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-PLAN-THE-FAMILY-WEEKEND', 'Plan the family weekend', 'Chọn Kế Hoạch Cuối Tuần', 'Decide the family''s weekend plan', 'Được quyết định kế hoạch cuối tuần của cả nhà', 'small', null, 60, 12, 15, 17, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-ONLINE-COURSE', 'Online course', 'Khóa Học Online', 'An online course of your choice', 'Một khóa học online tự chọn', 'medium', 300000, 300, 12, 15, 17, false, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-CONCERT-OR-EVENT-TICKET', 'Concert or event ticket', 'Vé Ca Nhạc / Sự Kiện', 'A ticket to a concert or event', 'Vé xem ca nhạc hoặc sự kiện', 'experience', 800000, 800, 13, 16, 17, true, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-BLUETOOTH-SPEAKER', 'Bluetooth speaker', 'Loa Bluetooth', 'A portable Bluetooth speaker', 'Một chiếc loa Bluetooth di động', 'large', 1000000, 1000, 12, 15, 17, true, true, true, true),
  ('00000000-0000-0000-0000-000000000000', 'BQ-RWD-NEW-SNEAKERS', 'New sneakers', 'Giày Thể Thao Mới', 'A pair of new sneakers', 'Một đôi giày thể thao mới', 'large', 1200000, 1200, 11, 14, 17, true, true, true, true)
on conflict do nothing;

-- =========================================================
-- 5. Family quest templates (coins per child)
-- =========================================================
update family_quests f set coin_reward = v.coin
from (values
  ('Read 5 Books Together', 50),
  ('Family Walk Week', 30),
  ('Screen-Free Evening', 25),
  ('Math Masters', 100),
  ('English Conversation Week', 25),
  ('Game Night x4', 20),
  ('Cook Together', 45),
  ('Family Reading Week', 35),
  ('Tidy House Challenge', 0),
  ('Morning Routine Streak', 0)
) as v(title, coin)
where f.is_system_template = true and f.title = v.title;
